"""Real Q1a closure: common reference, complete cases, bounded sensitivity."""
from __future__ import annotations

from collections import Counter
import hashlib
import json
import platform
import sys

import numpy as np
from scipy.stats import ks_2samp, wasserstein_distance

from src.interfaces import Provenance
from src.paths import ATT_A, CONFIGS, TABLES, PROBLEM_F_DERIVED, REPO_ROOT, ensure, require
from src.mixture.data import load_mixture, MIXTURE_FILES
from src.mixture.mapping import load_mapping, mapped_quality, mass_weighted_coverage
from . import scalarize as sc
from .analysis import conflict_analysis, domain_ranking, overlapping_sample_comparison
from .pipeline import aggregate, rank_corr
from .realdata import load_population, fit_population, transform_population, preprocessing_hash, file_hash
from .uncertainty import structured_estimates
from .handoff import build_if1, encode_if1, write_if1


def dump(path, value):
    path.write_text(json.dumps(value, sort_keys=True, indent=2, allow_nan=False) + '\n', encoding='utf-8', newline='\n')


def table(title, columns, rows, notes=()):
    def cell(v):
        if v is None:
            return 'undefined'
        if isinstance(v, float):
            return f'{v:.9g}'
        return str(v).replace('|', '/')
    return '\n'.join(['# '+title, '', 'Generated by `python scripts/q1_quality.py`; do not edit.', '',
                       *notes, '', '| '+' | '.join(columns)+' |',
                       '| '+' | '.join(['---']*len(columns))+' |',
                       *['| '+' | '.join(map(cell, row))+' |' for row in rows], ''])


def conflict(matrix, settings):
    report = conflict_analysis(matrix, thresholds=settings['conflict_thresholds'],
                               material_rho=settings['material_rank_correlation'], families=settings['families'])
    pairs = matrix.shape[1] * (matrix.shape[1]-1) / 2
    # Opposite sides of the common reference median, not negative correlation.
    disagreement = (matrix < .5).sum(axis=1) * (matrix > .5).sum(axis=1) / pairs
    coefficients = 2*np.arange(matrix.shape[1]) - matrix.shape[1] + 1
    discordance = (np.sort(matrix, axis=1) * coefficients).sum(axis=1) / pairs
    report['mean_record_sd'] = float(matrix.std(axis=1).mean())
    report['mean_pairwise_absolute_ecdf_gap'] = float(discordance.mean())
    report['mean_pairwise_median_direction_disagreement'] = float(disagreement.mean())
    report['association_counts'] = dict(Counter(p['association'] for p in report['all_pairs']))
    return report


def extension_comparison(populations, values, matrices, summaries, method, uncertainty, settings):
    result = {}
    for name, domain in [('A2', 'arxiv'), ('A3', 'github')]:
        a, b = populations['A1'], populations[name]
        _, ma = matrices['A1']
        _, mb = matrices[name]
        within = a.domains[ma] == domain
        ka = [key for key, keep in zip(a.keys, ma) if keep]
        kb = [key for key, keep in zip(b.keys, mb) if keep]
        qa, qb = values['A1'][within], values[name]
        report = overlapping_sample_comparison(qa, qb, [key for key, keep in zip(ka, within) if keep], kb, **uncertainty)
        report['ks_distance_descriptive'] = float(ks_2samp(qa, qb).statistic)
        report['wasserstein_distance'] = float(wasserstein_distance(qa, qb))
        report['quantile_shift_extension_minus_sample'] = dict(zip(map(str, settings['quantiles']),
                         map(float, np.quantile(qb, settings['quantiles'])-np.quantile(qa, settings['quantiles']))))
        reference = summaries['A1'][method]
        substituted = {**reference['domains'], domain: summaries[name][method]['domains'][domain]}
        report['original_ranking'] = domain_ranking(reference)
        report['substituted_ranking'] = domain_ranking({'domains': substituted})
        report['single_source_limitation'] = 'union-record bootstrap preserves overlap, but not unknown within-shard dependence'
        result[name] = report
    return result


def run_quality_closure(seed, settings):
    if settings['normalization'] != 'midrank_ecdf_A1_complete_cases':
        raise ValueError('unsupported normalization')
    print('seed:', seed, 'interpreter:', sys.executable, flush=True)
    config_hash = file_hash(CONFIGS/'q1.yaml')
    paths = {'A1': require(ATT_A/'slimpajama_quality_signal_sample.jsonl.xz')}
    for name, domain in [('A2', 'arxiv'), ('A3', 'github')]:
        matches = sorted((ATT_A/'slimpajama_quality_extended').glob(domain+'_*.jsonl.xz'))
        if len(matches) != 1:
            raise ValueError('extension file missing or ambiguous')
        paths[name] = matches[0]
    populations = {}
    for name, path in paths.items():
        populations[name] = load_population(path, name, settings['allowed_missing_fields'],
                                            {'A2':'arxiv', 'A3':'github'}.get(name))
        pop = populations[name]
        if len(pop.defects) != settings['expected_missing_records'][name]:
            raise ValueError('raw defect count differs from the secured audit')
        print(name, 'read', len(pop.values), 'complete', int(pop.complete.sum()),
              'source shards', len(set(pop.clusters)), flush=True)
    directions = {**sc.DIRECTIONS, **settings['direction_overrides']}
    prep = fit_population(populations['A1'], directions, settings['desirability_intervals'])
    frozen = preprocessing_hash(prep)
    uncertainty = dict(seed=seed, replicates=settings['bootstrap_replicates'], confidence=settings['confidence'])
    root = ensure(PROBLEM_F_DERIVED/'q1')
    tables = ensure(TABLES)
    primary = settings['primary_aggregator']
    all_summaries, all_conflicts, all_comparisons, scenario_values = {}, {}, {}, {}
    raw_defects = [d for pop in populations.values() for d in pop.defects]
    scenarios = [('complete_case', None)] + [('missing_'+str(v), v) for v in settings['missingness_scenarios']]
    primary_matrices = None
    for scenario, missing_value in scenarios:
        matrices = {name: transform_population(prep, pop, missing_value=missing_value) for name, pop in populations.items()}
        summaries, conflicts, scores = {}, {}, {}
        for name, (matrix, mask) in matrices.items():
            pop = populations[name]
            scores[name], summaries[name] = {}, {}
            for method in settings['aggregators']:
                scores[name][method] = aggregate(matrix, method, families=settings['families'])
                summaries[name][method] = structured_estimates(scores[name][method], pop.domains[mask], pop.clusters[mask], **uncertainty)
            conflicts[name] = conflict(matrix, settings)
            # Source-mix differences remain visible rather than being ECDF-normalized away.
            conflicts[name]['by_domain'] = {domain: conflict(matrix[pop.domains[mask] == domain], settings)
                                            for domain in sorted(set(pop.domains[mask]))}
        comparisons = {method: extension_comparison(populations, {n:scores[n][method] for n in scores},
                                                    matrices, summaries, method, uncertainty, settings)
                       for method in settings['aggregators']}
        all_summaries[scenario], all_conflicts[scenario], all_comparisons[scenario] = summaries, conflicts, comparisons
        scenario_values[scenario] = {n:scores[n][primary] for n in scores}
        if missing_value is None:
            primary_matrices = matrices
        print('quality scenario finished:', scenario, flush=True)
    if preprocessing_hash(prep) != frozen:
        raise ValueError('normalization changed while scoring extensions/scenarios')
    # Predeclared scientific-method sensitivities, never selected on Loss.
    method_sensitivity = {}
    for label in settings['sensitivity_transforms']:
        varied = dict(directions)
        intervals = dict(settings['desirability_intervals'])
        if label == 'word_length_increasing':
            varied['rps_doc_mean_word_length'] = 'higher_better'
            intervals.pop('rps_doc_mean_word_length')
        variant = fit_population(populations['A1'], varied, intervals,
                                 ordinal='argmax' if label == 'ordinal_argmax' else 'expected')
        method_sensitivity[label] = {}
        for name, pop in populations.items():
            matrix, mask = transform_population(variant, pop, neutral_fields=['rps_lines_numerical_chars_fraction'] if label == 'numeric_neutral' else [])
            q = aggregate(matrix, primary, families=settings['families'])
            method_sensitivity[label][name] = structured_estimates(q, pop.domains[mask], pop.clusters[mask], **uncertainty)
    family_sensitivity = {}
    for name, (matrix, mask) in primary_matrices.items():
        family_scores = {f:matrix[:, [sc.INDICATORS.index(k) for k in fields]].mean(axis=1)
                         for f, fields in settings['families'].items()}
        family_sensitivity[name] = {}
        for removed in family_scores:
            q = np.mean([v for f,v in family_scores.items() if f != removed], axis=0)
            family_sensitivity[name][removed] = {d:float(q[populations[name].domains[mask] == d].mean())
                                                 for d in sorted(set(populations[name].domains[mask]))}
    # Quality mapping uses mixture fractions only; this module never reads Loss.
    from .configuration import load_settings
    _, mixsettings = load_settings('mixture')
    designs = {aid:load_mixture(require(ATT_A/'regmix_tables'/filename), aid,
                                row_sum_tolerance=mixsettings['row_sum_tolerance'])
               for aid,filename in MIXTURE_FILES.items()}
    mapping, kinds = load_mapping(require(ATT_A/'domain_mapping_guide.csv'), designs['A4'].domains)
    reference = all_summaries['complete_case']
    q_by_domain = {d:v['q'] for d,v in reference['A1'][primary]['domains'].items()}
    coverage = {}
    for name, mix in designs.items():
        mass, qm = mapped_quality(mix, mapping, q_by_domain)
        coverage[name] = {'n':len(mass), 'coverage_fraction':mass_weighted_coverage(mix, mapping),
                          'min':float(mass.min()), 'median':float(np.median(mass)), 'max':float(mass.max()),
                          'zero_mass_n':int(np.sum(mass == 0)), 'q_mapped_mean_defined':float(np.nanmean(qm))}
    checks = {}
    for scenario, _ in scenarios[1:]:
        delta_q, delta_ci, delta_rate, mapped_delta = [], [], [], []
        ranks = {}
        for name in populations:
            for method in settings['aggregators']:
                base = reference[name][method]
                other = all_summaries[scenario][name][method]
                delta_q.append(abs(base['overall']['q']-other['overall']['q']))
                delta_ci.extend(np.abs(np.asarray(base['overall']['ci'])-other['overall']['ci']).tolist())
                for domain, item in base['domains'].items():
                    delta_q.append(abs(item['q']-other['domains'][domain]['q']))
                    delta_ci.extend(np.abs(np.asarray(item['ci'])-other['domains'][domain]['ci']).tolist())
                ranks[name+'/'+method] = domain_ranking(base)['ranks'] == domain_ranking(other)['ranks']
            for domain in [None, *all_conflicts['complete_case'][name]['by_domain']]:
                old = all_conflicts['complete_case'][name] if domain is None else all_conflicts['complete_case'][name]['by_domain'][domain]
                new = all_conflicts[scenario][name] if domain is None else all_conflicts[scenario][name]['by_domain'][domain]
                delta_rate.extend(abs(old['threshold_rate'][t]-new['threshold_rate'][t]) for t in old['threshold_rate'])
        for mix in designs.values():
            other_q = {d:v['q'] for d,v in all_summaries[scenario]['A1'][primary]['domains'].items()}
            mass, qa = mapped_quality(mix, mapping, q_by_domain)
            _, qb = mapped_quality(mix, mapping, other_q)
            mapped_delta.extend(np.abs(qa[mass > 0]-qb[mass > 0]).tolist())
        extension_delta = max(abs(all_comparisons[scenario][m][n]['extension_minus_sample']-
                                  all_comparisons['complete_case'][m][n]['extension_minus_sample'])
                              for m in settings['aggregators'] for n in ('A2','A3'))
        checks[scenario] = {'max_absolute_Q_change_all_aggregators':max(delta_q),
                            'max_CI_endpoint_change':max(delta_ci), 'max_conflict_curve_rate_change':max(delta_rate),
                            'max_mapped_Q_change':max(mapped_delta), 'mapped_mass_change':0.0,
                            'max_extension_difference_change':extension_delta, 'ranks_unchanged':ranks}
    sensitivity_pass = all(c['max_absolute_Q_change_all_aggregators'] <= settings['material_missingness_q'] and
                           c['max_CI_endpoint_change'] <= settings['material_missingness_q'] and
                           c['max_mapped_Q_change'] <= settings['material_missingness_q'] and
                           c['max_extension_difference_change'] <= settings['material_missingness_q'] and
                           c['max_conflict_curve_rate_change'] <= settings['material_missingness_conflict_rate'] and
                           all(c['ranks_unchanged'].values()) for c in checks.values())
    extension_pass = all(abs(all_comparisons['complete_case'][primary][n]['extension_minus_sample']) <= settings['material_extension_q']
                         for n in ('A2','A3'))
    acceptance = {'missingness_pass':sensitivity_pass, 'extension_effect_size_pass':extension_pass,
                  'thresholds':{k:v for k,v in settings.items() if k.startswith('material_')},
                  'scope':'relative declared proxy; not universal quality, causal effect or whole 17-domain corpus'}
    ranking_sensitivity = {method:domain_ranking(summary)
                           for method,summary in reference['A1'].items()}
    ranking_sensitivity.update({label:domain_ranking(pops['A1'])
                                for label,pops in method_sensitivity.items()})
    ranking_sensitivity.update({'omit_family_'+family:domain_ranking({'domains':{d:{'q':q} for d,q in values.items()}})
                                for family,values in family_sensitivity['A1'].items()})
    provenance = Provenance('mixed', [pop.source for pop in populations.values()] +
                            ['data_local/problem-f/raw/real_attachments/A_data_value/domain_mapping_guide.csv', 'configs/q1.yaml'],
                            'Observed quality signals; A16 reference mapping; complete-case A1 domain estimates only.')
    notes = {'q_definition':'equal weight of six upstream families, equal indicator weights within family',
             'directions':directions, 'normalization':'midrank ECDF on A1 complete cases only; constant/tied values receive midrank',
             'normalization_sha256':frozen, 'missing_signal_policy':settings['missing_signal_policy'],
             'stability':acceptance, 'missingness_sensitivity':checks, 'configuration_sha256':config_hash,
             'sample_dependence':reference['A1'][primary], 'desirability_intervals':settings['desirability_intervals'],
             'mapping_source':'A16 domain_mapping_guide.csv; original mapping_type retained',
             'A1_domain_ranking_by_declared_method':ranking_sensitivity,
             'A1_overall_calibration':'linear aggregation mean 0.5 is implied by the A1 midrank reference, not external quality evidence',
             'scientific_limitations':['single-shard uncertainty cannot estimate between-source variation',
                 'normalization and heuristic-choice uncertainty not covered by sampling intervals',
                 'natural-language heuristic can disadvantage code/math', 'composition effects are not quality effects',
                 'middle-domain rankings depend on aggregation and family weights; sampling CI is not method uncertainty']}
    interface = None
    if sensitivity_pass and extension_pass:
        interface = build_if1(reference['A1'][primary], designs['A4'], mapping, kinds, provenance=provenance, processing_notes=notes)
        interface.validate()
        output = write_if1(interface)
        release = {'status':'READY FOR REVIEW', 'path':output.relative_to(REPO_ROOT).as_posix(), 'sha256':file_hash(output), 'validate':'PASS'}
    else:
        release = {'status':'BLOCKED', 'path':None, 'sha256':None, 'validate':'not released', 'acceptance':acceptance}
    report = {'configuration_sha256':config_hash, 'preprocessing_sha256':frozen, 'settings':settings,
              'summaries':all_summaries, 'conflict':all_conflicts, 'comparisons':all_comparisons,
              'missingness_checks':checks, 'method_sensitivity':method_sensitivity, 'family_sensitivity':family_sensitivity,
              'ranking_sensitivity':ranking_sensitivity,
              'defects':raw_defects, 'coverage':coverage, 'acceptance':acceptance, 'release':release,
              'runtime':{'python':platform.python_version(), 'numpy':np.__version__},
              'raw_sha256':{p.source:p.sha256 for p in populations.values()}}
    dump(root/'quality-analysis.json', report)
    for name, (matrix, mask) in primary_matrices.items():
        pop = populations[name]
        np.savez_compressed(root/(name+'-standardized.npz'), indicators=np.array(sc.INDICATORS),
                            standardized=matrix, q=scenario_values['complete_case'][name],
                            primary_lines=pop.lines[mask], primary_domains=pop.domains[mask],
                            all_missing_flags=pop.missing, all_lines=pop.lines,
                            sensitivity_q=np.array([scenario_values[label][name] for label,_ in scenarios[1:]]))
    render_reports(tables, report, mapping, kinds, q_by_domain, primary)
    for name, path in paths.items():
        if file_hash(path) != populations[name].sha256:
            raise ValueError('raw file changed during scientific analysis')
    if file_hash(CONFIGS/'q1.yaml') != config_hash:
        raise ValueError('configuration changed during run')
    print('IF1:', release['status'], 'sensitivity:', checks, flush=True)
    return 0 if interface is not None else 2


def render_reports(tables, report, mapping, kinds, q_by_domain, primary):
    settings = report['settings']
    def write(name, title, columns, rows, notes=()):
        (tables/name).write_text(table(title, columns, rows, notes), encoding='utf-8', newline='\n')
    rows = []
    for pop, methods in report['summaries']['complete_case'].items():
        for method, summary in methods.items():
            for domain, e in [*summary['domains'].items(), ('OVERALL',summary['overall'])]:
                rows.append([pop,method,domain,e['n'],e['q'],*e['ci'],e.get('source_shards'),e.get('effective_source_count_kish')])
    write('q1-quality-analysis.md','Q1 complete-case quality and conditional uncertainty',
          ['Input','Aggregator','Domain','n','Q','CI low','CI high','Source shards','Kish effective sources'],rows,
          ['Primary: six-family balanced. All 22 standardized fields are higher-is-better.',
           'CI: 1000 deterministic source-shard bootstrap draws within domain; single-shard domains use conditional document bootstrap.',
           'Intervals condition on fitted A1 normalization and the Q rule. They exclude method-choice and unidentified within-shard dependence.',
           'A1 mean 0.5 for linear aggregators is a consequence of midrank calibration, not independent quality evidence.',
           'OVERALL uses observed domain shares; unequal counts are preserved. No whole-population unbiasedness claim.'])
    rows=[]
    for pop, details in report['conflict']['complete_case'].items():
        for domain, c in [('ALL',details),*details['by_domain'].items()]:
            for threshold, rate in c['threshold_rate'].items():
                rows.append([pop,domain,threshold,rate,c['mean_record_sd'],c['mean_pairwise_absolute_ecdf_gap'],
                             c['mean_pairwise_median_direction_disagreement'],c['association_counts'].get('antagonistic',0)])
    write('q1-conflict-analysis.md','Q1 conflict threshold curves',
          ['Input','Domain','Threshold','P(range >= threshold)','Mean record SD','Mean pair gap','Median-direction disagreement','Antagonistic pairs'],rows,
          ['Threshold grid is predeclared and unchanged. Pair counts use descriptive Spearman <= -0.3; no significance claim.',
           'Conflict also measures ECDF gaps and record dispersion; it is not defined only by negative associations.',
           'Family-balanced aggregation prevents field multiplicity from becoming family weight; it does not erase disagreement.'])
    rows=[]
    for method, comparisons in report['comparisons']['complete_case'].items():
        for pop,c in comparisons.items():
            rows.append([pop,method,c['sample_n'],c['extension_n'],c['overlap_n'],c['extension_minus_sample'],
                         *c['difference_ci'],c['ks_distance_descriptive'],c['wasserstein_distance'],
                         c['original_ranking']['ranks']==c['substituted_ranking']['ranks']])
    conflict_replication={}
    for pop,domain in [('A2','arxiv'),('A3','github')]:
        sampled=report['conflict']['complete_case']['A1']['by_domain'][domain]
        extended=report['conflict']['complete_case'][pop]
        conflict_replication[pop]={'maximum_threshold_curve_change':max(abs(v-extended['threshold_rate'][t]) for t,v in sampled['threshold_rate'].items()),
                                 'mean_pair_gap_change':extended['mean_pairwise_absolute_ecdf_gap']-sampled['mean_pairwise_absolute_ecdf_gap'],
                                 'antagonistic_pairs_sample':sampled['association_counts'].get('antagonistic',0),
                                 'antagonistic_pairs_extension':extended['association_counts'].get('antagonistic',0)}
    write('q1-a1-a3-comparison.md','Q1 same-source extension comparison',
          ['Extension','Aggregator','A1 n','Extension n','Overlap n','Delta Q','CI low','CI high','KS distance','Wasserstein','Ranks unchanged'],rows,
          ['A2 is entirely arxiv; A3 entirely github. They overlap A1 and are not independent causal replications.',
           'Difference intervals resample union-record identities with shared membership and fixed A1 normalization.',
           'KS is a descriptive distance; no independent-sample p-value is used. Source-shard dependence remains a limitation.',
           'Conflict replication: '+json.dumps(conflict_replication,sort_keys=True)])
    rows=[]
    for scenario,pops in report['summaries'].items():
        for pop,methods in pops.items():
            for domain,e in [*methods[primary]['domains'].items(),('OVERALL',methods[primary]['overall'])]:
                rows.append([scenario,pop,domain,e['n'],e['q'],*e['ci']])
    notes=['Only complete_case is primary. Other rows are missing-final-indicator bounds; they are not recovered observations.',
           'Exact excluded locators, fields, six literal NaNs each and raw hashes are in q1-input-audit.md.',
           'Normalization remains the same A1 complete-case reference in every missingness scenario.',
           'Sensitivity checks: '+json.dumps(report['missingness_checks'],sort_keys=True)]
    write('q1-missingness-sensitivity.md','Q1 confirmed-NaN sensitivity',['Scenario','Input','Domain','n','Q','CI low','CI high'],rows,notes)
    rows=[[d,mapping[d] or 'UNMAPPED',kinds[d],q_by_domain.get(mapping[d])] for d in mapping]
    write('q1-a16-coverage.md','A16 partial quality mapping',['Mixture domain','Quality domain','Mapping type','Q'],rows,
          ['Coverage is empirical mapped mixture mass, never mapped-domain count / 17.',
           'Per-design coverage summaries: '+json.dumps(report['coverage'],sort_keys=True),
           'At zero mapped mass Q_mapped is undefined. No quality is assigned to unmapped domains.'])
    rows=[]
    for name in sc.INDICATORS:
        native=sc.DIRECTIONS[name]
        direction={**sc.DIRECTIONS,**settings['direction_overrides']}[name]
        transform=('negative distance from [3,10], then frozen midrank ECDF' if name in settings['desirability_intervals'] else
                   'mean of four frozen criterion midrank ECDFs' if name=='qurater' else
                   '1 - frozen midrank ECDF' if direction=='lower_better' else 'frozen midrank ECDF')
        rows.append([name,sc.EXPECTED_DIM.get(name,1),native,transform,'higher is better'])
    write('q1-transform-contract.md','Q1 native and final indicator semantics',
          ['Indicator','Raw width','Native direction','Declared transform','Final interpretation'],rows,
          ['Exactly 14 native scalars + 8 reduced lists = 22; native direction totals 15/4/3 are unchanged.',
           'All marginal references come from A1 complete cases. Midranks handle ties symmetrically; no per-domain reference is fitted.',
           'Entropy diversity semantics: https://github.com/togethercomputer/RedPajama-Data/blob/main/app/src/core/quality_signals/natural_language.py',
           'Word-length [3,10] heuristic: Gopher Appendix A.1, https://arxiv.org/html/2112.11446 . Transfer to code/math is a limitation.',
           'Numeric fraction penalty is a declared prose heuristic, not a universal quality law. Neutralization is a sensitivity.',
           'No interior optimum or transform is fitted to Loss. Non-monotone native classification remains in IF1.'])
    rows=[]
    baseline=report['summaries']['complete_case']
    for label,pops in report['method_sensitivity'].items():
        for pop,summary in pops.items():
            for d,e in summary['domains'].items():
                rows.append([label,pop,d,e['q'],e['q']-baseline[pop][primary]['domains'][d]['q']])
    for pop,families in report['family_sensitivity'].items():
        for family,domains in families.items():
            for d,q in domains.items():
                rows.append(['omit_family_'+family,pop,d,q,q-baseline[pop][primary]['domains'][d]['q']])
    write('q1-method-sensitivity.md','Q1 predeclared method and family sensitivity',
          ['Variant','Input','Domain','Q','Delta from primary'],rows,
          ['All variants are sensitivities, never outcome-selected replacements for the primary.',
           'Method-choice variation is not included in conditional bootstrap confidence intervals; ranking changes must be retained.',
           'Descending A1 orders: '+json.dumps({k:v['order_with_lexical_tie_break'] for k,v in report['ranking_sensitivity'].items()},sort_keys=True)])
    write('q1-if1-summary.md','IF1 release status',['Property','Value'],
          [[k,json.dumps(v,sort_keys=True) if isinstance(v,dict) else v] for k,v in report['release'].items()],
          ['Config SHA-256: '+report['configuration_sha256'], 'Frozen normalization SHA-256: '+report['preprocessing_sha256'],
           'Primary Q is measured from complete cases. Sensitivity imputation is not used in IF1.',
           'Source dependence and method limitations travel in provenance. Acceptance: '+json.dumps(report['acceptance'],sort_keys=True)])
