"""Frozen real-data response evaluation; post-validation fits are diagnostics."""
from __future__ import annotations

from dataclasses import asdict
import json
import platform
import sys

import numpy as np
from scipy.optimize import least_squares

from src.interfaces import Provenance
from src.paths import ATT_A, CONFIGS, TABLES, PROBLEM_F_DERIVED, REPO_ROOT, ensure, require
from src.quality.realdata import file_hash
from src.quality.pipeline import rank_corr
from .data import MIXTURE_FILES, LOSS_FILES, MixtureTable, load_pair, normalised_proportions, check_decimal_grid, diagnostics
from .model import response_matrix, _ridge_fit
from .validation import (VALIDATION_ROLES, select_training_model, evaluate, paired_scale_analysis,
                         prediction_matrix, compare_estimated_reference)
from .handoff import build_if2, encode_if2, write_if2


def dump(path, value):
    path.write_text(json.dumps(value, sort_keys=True, indent=2, allow_nan=False)+'\n',encoding='utf-8',newline='\n')


def table(title, columns, rows, notes=()):
    def cell(value):
        if value is None:
            return 'undefined'
        if isinstance(value,float):
            return f'{value:.9g}'
        return str(value).replace('|','/')
    return '\n'.join(['# '+title,'','Generated by `python scripts/q1_mixture.py`; do not edit.','',*notes,'',
                       '| '+' | '.join(columns)+' |','| '+' | '.join(['---']*len(columns))+' |',
                       *['| '+' | '.join(map(cell,row))+' |' for row in rows],''])


def validation_intervals(observed, predicted, *, seed, replicates, confidence):
    if (observed.shape != predicted.shape or observed.ndim != 2 or not len(observed)
            or not np.isfinite(observed).all() or not np.isfinite(predicted).all()):
        raise ValueError('validation intervals require paired finite matrices')
    rng=np.random.default_rng(seed)
    draws=np.empty((replicates,observed.shape[1]))
    error=(predicted-observed)**2
    for b in range(replicates):
        idx=rng.integers(0,len(observed),len(observed))
        draws[b]=np.sqrt(error[idx].mean(axis=0))
    tail=(1-confidence)/2
    return np.quantile(draws,[tail,1-tail],axis=0).T.tolist()


def acceptance_checks(frozen, reports, baseline, pairs, settings):
    thresholds=settings['acceptance']
    r=reports['A6_A7']['absolute']['macro']
    ratio=r['rmse']['mean']/baseline['A6_A7']['absolute']['macro']['rmse']['mean']
    observed=pairs['A10'][1].values
    predicted=prediction_matrix(frozen,pairs['A10'][0])
    spread=observed.std(axis=0)
    if (spread==0).any():
        raise ValueError('out-of-design shape is undefined for a constant Loss target')
    nrmse=np.sqrt(np.mean(((predicted-predicted.mean(axis=0))-(observed-observed.mean(axis=0)))**2,axis=0))/spread
    in_design=(r['r2']['mean'] is not None and r['r2']['mean']>=thresholds['in_design_min_macro_r2'] and
               ratio<=thresholds['in_design_max_baseline_rmse_ratio'])
    out_rank=reports['A10_A11']['absolute']['macro']['spearman']['mean']
    out_shape=(out_rank is not None and out_rank>=thresholds['out_design_min_macro_spearman'] and
               float(nrmse.mean())<=thresholds['out_design_max_centered_nrmse'])
    absolute={key:report['absolute']['macro']['mean_absolute_relative_error']['mean']<=thresholds['absolute_transfer_max_relative_error']
              for key,report in reports.items()}
    return {'in_design_pass':bool(in_design),'out_of_design_shape_pass':bool(out_shape),
            'in_design_baseline_rmse_ratio':float(ratio),'out_design_macro_centered_nrmse':float(nrmse.mean()),
            'out_design_macro_spearman':out_rank,'absolute_transfer_pass':absolute,'thresholds':thresholds,
            'release_pass':bool(in_design and out_shape),
            'scale_invariance_supported':bool(all(absolute.values()) and out_shape),
            'scope':'1M absolute response; larger-scale ranking/shape validation cannot certify absolute scale transfer'}


def scope_release_receipt(frozen, reports, acceptance):
    """Record the narrow 1M IF2 decision without changing broad validation."""
    frozen.check_unchanged()
    for partition, role in VALIDATION_ROLES.items():
        report=reports.get(partition,{})
        if report.get('role')!=role or report.get('model_sha256')!=frozen.model_sha256:
            raise ValueError('scope release requires every validation role on the frozen model')
    absolute=acceptance.get('absolute_transfer_pass',{})
    limitations={'absolute_use_outside_1M':'PROHIBITED','scale_invariance_supported':False,
                 'A8_A9_absolute_transfer_certified':False,'A10_A11_out_of_design_shape_certified':False,
                 'fitted_10B_70B_extrapolation':'NOT RELEASED'}
    passed=bool(acceptance.get('in_design_pass') and not acceptance.get('release_pass')
                and absolute.get('A8_A9') is False and absolute.get('A10_A11') is False
                and acceptance.get('out_of_design_shape_pass') is False
                and acceptance.get('scale_invariance_supported') is False)
    return {'scope_release_pass':passed,'fit_scale':'1M','fit_sources':['A4','A5'],
            'release_validation_partition':'A6_A7','release_validation_role':VALIDATION_ROLES['A6_A7'],
            'frozen_model_sha256':frozen.model_sha256,
            'broad_transfer_pass':bool(acceptance.get('release_pass')),
            'a8_a9_absolute_transfer_pass':absolute.get('A8_A9'),
            'a10_a11_out_of_design_shape_pass':bool(acceptance.get('out_of_design_shape_pass')),
            'limitations':limitations}


def fixed_parameters(x, y, alphas):
    """Refit a frozen basis/penalty for descriptive uncertainty, never tuning."""
    xmean=x.mean(axis=0)
    ymean=y.mean(axis=0)
    centered=x-xmean
    gram=centered.T@centered
    rhs=centered.T@(y-ymean)
    beta=np.empty((x.shape[1],y.shape[1]))
    for alpha in sorted(set(alphas)):
        columns=np.flatnonzero(np.asarray(alphas)==alpha)
        beta[:,columns]=np.linalg.solve(gram+alpha*np.eye(x.shape[1]),rhs[:,columns])
    return np.vstack((ymean-xmean@beta,beta))


def effect_diagnostics(frozen, pairs, settings, seed):
    """Same basis, reference, penalties and perturbations at every scale.

    A6/A8 refits are a paired descriptive diagnostic after all predictions are
    frozen. They never replace IF2's A4/A5 parameters or its validation scores.
    """
    center=normalised_proportions(pairs['A4'][0]).mean(axis=0)
    domains=list(frozen.domains)
    base=MixtureTable('A4 centroid',np.array([0]),domains,center[None,:])
    x0,_=response_matrix(base,frozen.reference,frozen.kind)
    contrast_domains=[d for d in domains if d!=frozen.reference]
    mass=settings['substitution_mass']
    changed=np.tile(center,(len(contrast_domains),1))
    for i,d in enumerate(contrast_domains):
        changed[i,domains.index(d)]+=mass
        changed[i,domains.index(frozen.reference)]-=mass
    if (changed<0).any():
        raise ValueError('predeclared perturbation outside A4 centroid simplex')
    xp,_=response_matrix(MixtureTable('substitutions',np.arange(len(changed)),domains,changed),frozen.reference,frozen.kind)
    change=np.column_stack((np.zeros(len(changed)),xp-x0))
    alphas=[fit.alpha for fit in frozen.fits]
    tail=(1-settings['confidence'])/2
    result={}
    # Shared seed and same length produce identical resampled design indices for A6/A8.
    for source in ('A4','A6','A8','A10'):
        mix,loss=pairs[source]
        x,_=response_matrix(mix,frozen.reference,frozen.kind)
        params=fixed_parameters(x,loss.values,alphas)
        effect=change@params
        rng=np.random.default_rng(seed)
        samples=[]
        for _ in range(settings['coefficient_bootstrap_replicates']):
            draw=rng.integers(0,len(x),len(x))
            samples.append(change@fixed_parameters(x[draw],loss.values[draw],alphas))
        lo,hi=np.quantile(samples,[tail,1-tail],axis=0)
        result[source]={'effect':effect.tolist(),'ci_low':lo.tolist(),'ci_high':hi.tolist(),
                        'design_rank':int(np.linalg.matrix_rank(x-x.mean(axis=0))), 'features':x.shape[1], 'n':len(x),
                        'role':'training parameter uncertainty' if source=='A4' else 'post-validation descriptive refit; NOT a new predictor',
                        'bootstrap_parameters':params.tolist() if source=='A4' else None}
    comparisons={}
    for left,right in [('A4','A6'),('A6','A8'),('A6','A10')]:
        a,b=np.asarray(result[left]['effect']),np.asarray(result[right]['effect'])
        la,ha=np.asarray(result[left]['ci_low']),np.asarray(result[left]['ci_high'])
        lb,hb=np.asarray(result[right]['ci_low']),np.asarray(result[right]['ci_high'])
        resolved=(la*ha>0)&(lb*hb>0)
        reverse=(np.sign(a)!=np.sign(b))
        correlations=[rank_corr(np.abs(a[:,j]),np.abs(b[:,j])) for j in range(a.shape[1])]
        comparisons[left+'_'+right]={'sign_agreement':float(np.mean(~reverse)),
              'jointly_resolved_effects':int(resolved.sum()),'resolved_sign_reversals':int(np.sum(resolved&reverse)),
              'mean_importance_rank_correlation':float(np.mean([v for v in correlations if v is not None])),
              'paired_design':left=='A6' and right=='A8',
              'limitation':'A10 scale and design changes are confounded; high-dimensional ridge diagnostics are penalty-conditional'}
    return {'domains':contrast_domains,'targets':list(frozen.targets),'reference':frozen.reference,
            'base_composition':center.tolist(),'substitution_mass':mass,'per_source':result,'comparisons':comparisons,
            'uncertainty':'paired design-row bootstrap with frozen form and penalty; conditional, not post-selection inference',
            'bootstrap_replicates':settings['coefficient_bootstrap_replicates']}


def limited_extrapolation(frozen, pairs, settings):
    """One prespecified nonnegative scale-offset power law after validation.

    L(N,p) = a + b*(N/1M)^(-c) + g(p)-g(A4 centroid).
    Equal scale weighting; three observed scales and three parameters are weak
    extrapolation evidence. Estimated A13/A15 values are never passed here.
    """
    if set(pairs) != {'A4', 'A6', 'A8', 'A10'}:
        raise ValueError('scale diagnostics accept only the four observed source pairs')
    scales=np.asarray(settings['extrapolation']['scales'],float)
    if list(scales)!=[1e6,60e6,1e9]:
        raise ValueError('unexpected observed scale roles')
    centroid=normalised_proportions(pairs['A4'][0]).mean(axis=0)
    center=MixtureTable('A4 centroid',np.array([0]),list(frozen.domains),centroid[None,:])
    anchor=prediction_matrix(frozen,center)[0]
    residuals={key:pairs[key][1].values-prediction_matrix(frozen,pairs[key][0])+anchor for key in ('A4','A6','A8','A10')}
    levels=np.vstack((np.concatenate((residuals['A4'],residuals['A6'])).mean(axis=0),
                      residuals['A8'].mean(axis=0),residuals['A10'].mean(axis=0)))
    fits={}
    logscale=np.log(scales/scales[0])
    for j,target in enumerate(frozen.targets):
        y=levels[:,j]
        if (y<=0).any():
            raise ValueError('nonpositive scale offset; prescribed extrapolation is unsupported')
        # Fixed analytic initialization, not a searched model family.
        start=[0.,float(y[0]),max(0.,float(np.log(y[0]/y[-1])/logscale[-1]))]
        fun=lambda theta: theta[0]+theta[1]*np.exp(-theta[2]*logscale)-y
        fit=least_squares(fun,start,bounds=(0,np.inf))
        if not fit.success or not np.isfinite(fit.x).all():
            raise ValueError('prespecified scale offset did not converge')
        fits[target]={'a':float(fit.x[0]),'b':float(fit.x[1]),'c':float(fit.x[2]),
                       'scale_means':y.tolist(),'scale_mean_rmse':float(np.sqrt(np.mean(fun(fit.x)**2)))}
    return {'form':'a + b*(N/1000000)^(-c) + frozen_g(p)-frozen_g(A4_centroid)',
            'parameters':fits,'anchor':anchor.tolist(),'fitted_sources':['A4/A5','A6/A7','A8/A9','A10/A11'],
            'excluded_estimated_sources':['A13','A15'],
            'limitation':'post-validation Q1-only diagnostic; three observed scales, no independent validation at 10B/70B; composition shape held fixed'}


def run_mixture_closure(seed,settings):
    print('seed:',seed,'interpreter:',sys.executable,flush=True)
    root=ATT_A/'regmix_tables'
    out=ensure(PROBLEM_F_DERIVED/'q1')
    tables=ensure(TABLES)
    config_hash=file_hash(CONFIGS/'q1.yaml')
    hashes={f:file_hash(require(root/f)) for f in [*MIXTURE_FILES.values(),*LOSS_FILES.values()]}
    check_decimal_grid(root/MIXTURE_FILES['A4'],settings['stored_decimal_places'],settings['row_sum_tolerance'])
    train,loss=load_pair(root,'A4',row_sum_tolerance=settings['row_sum_tolerance'])
    selection={'minimum_relative_gain':settings['nonlinear_min_relative_gain'],'minimum_fold_wins':settings['nonlinear_min_fold_wins']}
    frozen=select_training_model(train,loss,source_pair=('A4','A5'),seed=seed,alphas=settings['ridge_alphas'],
                                  folds=settings['cv_folds'],candidates=settings['candidates'],selection=selection)
    baseline=select_training_model(train,loss,source_pair=('A4','A5'),seed=seed,alphas=settings['ridge_alphas'],
                                    folds=settings['cv_folds'],candidates=['linear'])
    # Written before any held-out Loss is loaded; immutable through all later diagnostics.
    dump(out/'mixture-frozen.json',{'model_sha256':frozen.model_sha256,'training_sha256':frozen.training_sha256,
                                  'domain_order':list(frozen.domains),'fits':[asdict(f) for f in frozen.fits],
                                  'selection':frozen.cv,'configuration_sha256':config_hash})
    print('A4/A5 selection FROZEN:',frozen.kind,frozen.model_sha256,frozen.cv['decision'],flush=True)
    pairs={'A4':(train,loss)}
    reports,baselines={},{}
    for source in ('A6','A8','A10'):
        check_decimal_grid(root/MIXTURE_FILES[source],settings['stored_decimal_places'],settings['row_sum_tolerance'])
        pairs[source]=load_pair(root,source,row_sum_tolerance=settings['row_sum_tolerance'])
        key=source+'_A'+str(int(source[1:])+1)
        reports[key]=evaluate(frozen,*pairs[source],partition=key)
        baselines[key]=evaluate(baseline,*pairs[source],partition=key)
        intervals=validation_intervals(pairs[source][1].values,prediction_matrix(frozen,pairs[source][0]),
                                       seed=seed,replicates=settings['bootstrap_replicates'],confidence=settings['confidence'])
        reports[key]['rmse_ci_by_target']=dict(zip(frozen.targets,intervals))
        print('frozen validation:',key,reports[key]['absolute']['macro'],flush=True)
    paired=paired_scale_analysis(*pairs['A6'],*pairs['A8'])
    difference=pairs['A8'][1].values-pairs['A6'][1].values
    rng=np.random.default_rng(seed)
    draws=np.array([difference[rng.integers(0,len(difference),len(difference))].mean(axis=0)
                    for _ in range(settings['bootstrap_replicates'])])
    tail=(1-settings['confidence'])/2
    ci=np.quantile(draws,[tail,1-tail],axis=0).T
    for j,t in enumerate(frozen.targets):
        paired['per_target'][t]['paired_mean_shift_ci']=ci[j].tolist()
    acceptance=acceptance_checks(frozen,reports,baselines,pairs,settings)
    scope_release=scope_release_receipt(frozen,reports,acceptance)
    # Freeze all validation metrics before post-validation descriptive fits.
    dump(out/'mixture-frozen-validation.json',{'validation':reports,'baseline':baselines,'paired':paired,
                                               'acceptance':acceptance,'scope_release':scope_release})
    effects=effect_diagnostics(frozen,pairs,settings,seed)
    references={}
    extrapolation=None
    if acceptance['release_pass']:
        extrapolation=limited_extrapolation(frozen,pairs,settings)
    # Estimated references are loaded only after the validation/scale model freeze.
    for source,scale in zip(('A12','A14'),settings['extrapolation']['target_scales']):
        mix,estimated=load_pair(root,source,row_sum_tolerance=settings['row_sum_tolerance'])
        by_index=dict(zip(train.indices,train.values))
        if not all(i in by_index and np.array_equal(v,by_index[i]) for i,v in zip(mix.indices,mix.values)):
            raise ValueError('estimated design is not the audited training subset')
        predicted=prediction_matrix(frozen,mix)
        if extrapolation is not None:
            for j,target in enumerate(frozen.targets):
                param=extrapolation['parameters'][target]
                level=param['a']+param['b']*(scale/settings['extrapolation']['scales'][0])**(-param['c'])
                predicted[:,j]+=level-extrapolation['anchor'][j]
        label='A'+str(int(source[1:])+1)
        references[label]=compare_estimated_reference(estimated,predicted,source=label)
        references[label]['design_role']='indexed subset of A4; not independent validation'
        references[label]['prediction_role']='limited scale extrapolation' if extrapolation else 'unscaled 1M stress diagnostic; extrapolation blocked by frozen validation'
        references[label]['target_scale']=scale
        references[label]['nonpositive_predictions']=int(np.sum(predicted<=0))
    provenance=Provenance('observed',['data_local/problem-f/raw/real_attachments/A_data_value/regmix_tables/'+f for f in hashes],
                         'A4/A5 fit; observed validation kept separate from A13/A15 estimated agreement; no quality effect is inferred.')
    release={'status':'BLOCKED','display_status':'BLOCKED','reason':'same-scale 1M scope-release receipt failed',
             'fit_scale':None,'path':None,'sha256':None}
    if scope_release['scope_release_pass']:
        interface=build_if2(frozen,reports,references,
                             renormalisation='divide each nonnegative row by its positive stored sum; 0.0085 nearest-rounding bound; exact zeros retained',
                             provenance=provenance,scope_release=scope_release)
        interface.validation['acceptance']=acceptance
        interface.validation['scale_applicability']={'absolute':'1M only; absolute use outside 1M is prohibited',
             'scale_invariance_supported':False,
             'larger_scale':'A8/A9 absolute transfer and A10/A11 out-of-design shape failed; no correction or reselection applied'}
        interface.validation['parameter_uncertainty']=effects
        interface.validation['limited_extrapolation_NOT_validation']=extrapolation
        interface.validation['configuration_sha256']=config_hash
        interface.validation['simplex']={'order':list(frozen.domains),'nonnegative':True,'sum_after_normalization':1.0,
                'inverse_reference':'p_reference = 1 - sum(nonreference proportions)',
                'quality_vs_composition':'composition model; no coefficient estimates a causal quality effect'}
        interface.validate()
        path=write_if2(interface)
        release={'status':'READY FOR REVIEW','display_status':'READY FOR REVIEW — 1M SCOPE ONLY',
                 'fit_scale':'1M','path':path.relative_to(REPO_ROOT).as_posix(),'sha256':file_hash(path),'validate':'PASS',
                 'scope_release':scope_release}
    frozen.check_unchanged()
    report={'configuration_sha256':config_hash,'frozen':{'kind':frozen.kind,'reference':frozen.reference,
                   'domain_order':list(frozen.domains),'model_sha256':frozen.model_sha256,'training_sha256':frozen.training_sha256,
                   'selection':frozen.cv,'fits':[asdict(f) for f in frozen.fits]},
            'validation':reports,'baseline_validation':baselines,'paired':paired,'effects':effects,
            'acceptance':acceptance,'scope_release':scope_release,'extrapolation':extrapolation,'estimated_references':references,
            'release':release,'structure':diagnostics(pairs),'raw_sha256':hashes,
            'runtime':{'python':platform.python_version(),'numpy':np.__version__}}
    dump(out/'mixture-analysis.json',report)
    render_reports(tables,report)
    if any(file_hash(root/f)!=h for f,h in hashes.items()) or file_hash(CONFIGS/'q1.yaml')!=config_hash:
        raise ValueError('raw inputs or configuration changed during run')
    print('IF2:',release,'acceptance:',acceptance,flush=True)
    return 0 if release['status']=='READY FOR REVIEW' else 2


def render_reports(tables,report):
    def write(filename,title,columns,rows,notes=()):
        (tables/filename).write_text(table(title,columns,rows,notes),encoding='utf-8',newline='\n')
    frozen=report['frozen']
    selection=frozen['selection']
    rows=[]
    for kind,item in selection['candidates'].items():
        rows.append([kind,item['selection_score'],item['features'],item['centered_rank'],item['condition_number'],item.get('fold_normalized_rmse')])
    write('q1-mixture-selection.md','Q1 training-only model selection',
          ['Candidate','Normalized CV RMSE','Features','Centered rank','Condition number','Fold scores'],rows,
          ['Selection statistic, not unbiased nested-CV performance. A4/A5 only.',
           'Selected: '+frozen['kind']+'; dropped reference: '+frozen['reference'],
           'Decision: '+json.dumps(selection['decision'],sort_keys=True),
           'Model SHA-256 frozen before validation: '+frozen['model_sha256'],
           'Alphas by target: '+json.dumps({fit['target']:fit['alpha'] for fit in frozen['fits']},sort_keys=True)])
    rows=[]
    for partition,v in report['validation'].items():
        for target,m in v['absolute']['per_target'].items():
            rows.append([partition,v['role'],target,m['n'],m['mae'],m['rmse'],*v['rmse_ci_by_target'][target],m['r2'],m['mean_absolute_relative_error'],m['spearman']])
    write('q1-mixture-validation.md','Q1 frozen validation by role',
          ['Partition','Role','Target','n','MAE','RMSE','RMSE CI low','RMSE CI high','R2','Mean absolute relative error','Spearman'],rows,
          ['A6/A8 are the same design at different scales; never pooled as independent validation sets.',
           'No correction was fitted before these predictions. RMSE intervals resample design rows with the model fixed.',
           'Acceptance: '+json.dumps(report['acceptance'],sort_keys=True)])
    rows=[]
    for target,c in report['paired']['per_target'].items():
        rows.append([target,c['mean_loss_shift_60m_minus_1m'],*c['paired_mean_shift_ci'],c['ordering_spearman'],c['standard_deviation_ratio'],c['centered_difference_rmse']])
    write('q1-cross-scale.md','Q1 paired and descriptive cross-scale diagnostics',
          ['Target','60M minus 1M','CI low','CI high','Paired ordering Spearman','SD ratio','Centered difference RMSE'],rows,
          ['A6/A8 comparisons preserve paired design indices. A10 has a different design; scale and design cannot be separated there.',
           'Coefficient/effect diagnostics use frozen form, reference and penalty after validation; they do not replace the validated predictor.',
           'Effect stability: '+json.dumps(report['effects']['comparisons'],sort_keys=True),
           'Centered shape by partition: '+json.dumps({p:v['centered_shape']['macro'] for p,v in report['validation'].items()},sort_keys=True)])
    rows=[]
    effects=report['effects']
    for source,e in effects['per_source'].items():
        for i,d in enumerate(effects['domains']):
            for j,t in enumerate(effects['targets']):
                rows.append([source,d,t,e['effect'][i][j],e['ci_low'][i][j],e['ci_high'][i][j]])
    write('q1-mixture-effects.md','Q1 reference-mass substitution effects',
          ['Source','Increased domain','Loss target','Delta Loss','Conditional CI low','Conditional CI high'],rows,
          ['Reference: '+effects['reference']+'; mass transferred: '+str(effects['substitution_mass'])+' at the A4 centroid.',
           'A4 is training parameter uncertainty. A6/A8/A10 are post-validation descriptive refits, not held-out prediction results.',
           effects['uncertainty'],'No raw coefficient is an absolute or causal domain-quality effect.'])
    rows=[]
    for source,r in report['estimated_references'].items():
        for target,m in r['comparison']['per_target'].items():
            rows.append([source,r['prediction_role'],target,m['mae'],m['rmse'],m['r2'],m['mean_absolute_relative_error'],m['spearman']])
    write('q1-extrapolation.md','Q1 estimated-reference diagnostics',
          ['Reference','Prediction role','Target','MAE','RMSE','R2','Mean absolute relative error','Spearman'],rows,
          ['A12/A14 are repeated training-design subsets. A13/A15 are estimated surfaces, NOT independent observed validation.',
           'Scale model: '+json.dumps(report['extrapolation'],sort_keys=True),
           'Estimated-reference agreement cannot establish genuine prediction accuracy at 10B/70B. Negative findings retained.'])
    write('q1-if2-summary.md','IF2 release status',['Property','Value'],
          [[k,v] for k,v in report['release'].items()],
          ['Scope release: '+json.dumps(report['scope_release'],sort_keys=True),
           'Broad cross-scale scientific acceptance remains: '+str(report['acceptance']['release_pass']),
           'A8/A9 absolute transfer pass: '+str(report['acceptance']['absolute_transfer_pass']['A8_A9'])+
           '; A10/A11 out-of-design shape pass: '+str(report['acceptance']['out_of_design_shape_pass'])+
           '; scale invariance supported: '+str(report['acceptance']['scale_invariance_supported']),
           'Config SHA-256: '+report['configuration_sha256'],
           'Zero policy: exact boundary zeros, no pseudocount. Renormalization: divide by observed row sum.',
           'Domain order: '+json.dumps(frozen['domain_order']),
           'Contrast reference: '+frozen['reference']+'; model: '+frozen['kind'],
           'Fit source: A4/A5 at 1M only. Observed validation and estimated agreement remain distinct.',
           'No fitted 10B/70B extrapolation is released.'])
