"""Configured Q1b training/CV and frozen validation; no test-set tuning.

With the approved Q1 selection rule, this entry point emits IF2 only after a
narrow 1M scope receipt. Cross-scale transfer and extrapolation remain blocked
unless the separate broad validation gate passes. Missing approved configuration
is a hard gate, not an invitation to install defaults.
"""
from __future__ import annotations

import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.paths import ATT_A, TABLES, ensure, REPO_ROOT
from src.quality.configuration import load_settings, require_settings
from src.mixture.data import load_pair, diagnostics, check_decimal_grid, MIXTURE_FILES
from src.mixture.validation import select_training_model, evaluate, paired_scale_analysis


def render_validation(frozen, reports: dict, structural: dict, paired: dict) -> str:
    lines = ['# Q1 mixture selection and frozen validation', '',
             'Generated by `python scripts/q1_mixture.py` using `configs/q1.yaml`.',
             'Stage: frozen validation with a possible narrow 1M IF2 scope receipt. No cross-scale',
             'transfer or extrapolation is certified.', '',
             f'Model SHA-256 frozen before held-out evaluation: `{frozen.model_sha256}`.',
             f'Training fingerprint: `{frozen.training_sha256}`.',
             f'Chosen candidate: `{frozen.kind}`; dropped reference: `{frozen.reference}`.',
             'Rows are divided by their stored sum. Zeros remain valid boundary proportions.',
             'Coefficients describe replacing reference-domain mass. Interaction effects',
             'depend on the starting composition; no causal interpretation is established.', '',
             '## Training-only selection', '',
             'A4/A5 alone supplies fitting and deterministic CV. The CV score is a model',
             'selection statistic, not an unbiased nested-CV generalization estimate.', '',
             '| Candidate | Mean normalized CV RMSE | Features | Centered rank | Condition number |',
             '| --- | ---: | ---: | ---: | ---: |']
    for kind, item in frozen.cv['candidates'].items():
        condition = item['condition_number']
        lines.append(f"| {kind} | {item['selection_score']:.6g} | {item['features']} | {item['centered_rank']} | {condition if condition is not None else 'rank deficient'} |")
    lines += ['', '## Held-out partitions', '',
              '| Partition | Target | MAE | RMSE | R2 | Mean absolute relative error | Spearman |',
              '| --- | --- | ---: | ---: | ---: | ---: | ---: |']
    def fmt(value):
        return 'undefined' if value is None else f'{value:.6g}'
    for partition, report in reports.items():
        for target, values in report['absolute']['per_target'].items():
            lines.append('| ' + partition + ' | ' + target + ' | ' + ' | '.join(fmt(values[k]) for k in ('mae', 'rmse', 'r2', 'mean_absolute_relative_error', 'spearman')) + ' |')
    lines += ['', '## Complete reproducible diagnostics', '',
              'The JSON block includes per-target and macro errors, centered shape descriptions,',
              'level shifts, negative-prediction counts, paired A6/A8 scale diagnostics,',
              'renormalization and candidate conditioning. Centering is descriptive, not a',
              'fitted test-set correction. No estimated reference enters fitting or validation.', '',
              '```json', json.dumps({'selection': frozen.cv, 'validation': reports,
                                     'paired_scale': paired, 'structure': structural},
                                    indent=2, sort_keys=True, allow_nan=False), '```', '',
              'Next stage: retain failed cross-scale findings. An IF2 may be ready for review only',
              'under an explicit A6/A7-backed 1M scope receipt; A13/A15 remain estimated',
              'references only and do not enter selection or validation.', '']
    return '\n'.join(lines)


def main() -> int:
    seed, settings = load_settings('mixture')
    if settings.get('selection_rule') == 'nonlinear_requires_relative_gain_and_fold_consistency':
        from src.mixture.closure import run_mixture_closure
        return run_mixture_closure(seed, settings)
    require_settings(settings, ['row_sum_tolerance', 'cv_folds', 'ridge_alphas', 'candidates', 'stored_decimal_places'])
    print('seed:', seed, flush=True)
    root = ATT_A / 'regmix_tables'
    check_decimal_grid(root / MIXTURE_FILES['A4'], settings['stored_decimal_places'], settings['row_sum_tolerance'])
    train, loss = load_pair(root, 'A4', row_sum_tolerance=settings['row_sum_tolerance'])
    frozen = select_training_model(train, loss, source_pair=('A4', 'A5'), seed=seed,
                                   alphas=settings['ridge_alphas'], folds=settings['cv_folds'],
                                   candidates=settings['candidates'])
    print('model frozen before validation:', frozen.model_sha256, flush=True)
    pairs = {'A4': (train, loss)}
    reports = {}
    for name in ('A6', 'A8', 'A10'):
        check_decimal_grid(root / MIXTURE_FILES[name], settings['stored_decimal_places'], settings['row_sum_tolerance'])
        pairs[name] = load_pair(root, name, row_sum_tolerance=settings['row_sum_tolerance'])
        key = name + '_A' + str(int(name[1:]) + 1)
        reports[key] = evaluate(frozen, *pairs[name], partition=key)
    paired = paired_scale_analysis(*pairs['A6'], *pairs['A8'])
    frozen.check_unchanged()
    report = render_validation(frozen, reports, diagnostics(pairs), paired)
    out = ensure(TABLES) / 'q1-mixture-validation.md'
    out.write_text(report, encoding='utf-8', newline='\n')
    print('wrote', out.relative_to(REPO_ROOT).as_posix(), flush=True)
    print('validation stage complete; any IF2 requires the explicit 1M scope-release closure path')
    return 0


if __name__ == '__main__':
    try:
        raise SystemExit(main())
    except (ValueError, KeyError, FileNotFoundError) as error:
        print('STOP:', error, file=sys.stderr)
        raise SystemExit(2)
