"""Configured full-record quality analysis, with strict raw-finiteness gating.

No missing-signal treatment is implemented or inferred here. The current raw
inputs cannot pass this gate. IF1 release needs the subsequent scientific
stability/sensitivity assessment and is intentionally a separate operation.
"""
from __future__ import annotations

import json
from pathlib import Path
import sys
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.paths import ATT_A, TABLES, REPO_ROOT, ensure, require
from src.quality import scalarize as sc
from src.quality.configuration import load_settings, require_settings
from src.quality.pipeline import QualityPreprocessor, stream_quality, aggregate
from src.quality.analysis import domain_estimates, domain_ranking, conflict_analysis, overlapping_sample_comparison


def collect(preprocessor, path, domain=None):
    keys = []
    def records():
        for row in stream_quality(path, domain):
            keys.append((row['_source_domain'], row['sub_path'], row['id']))
            yield row
    matrix, domains = preprocessor.transform(records())
    if len(set(keys)) != len(keys):
        raise ValueError('duplicate source/record identities in quality population')
    return matrix, domains, keys


def render_quality(analyses: dict, comparisons: dict, settings: dict) -> str:
    lines = ['# Q1 quality analysis', '',
             'Generated by `python scripts/q1_quality.py` using approved settings in',
             '`configs/q1.yaml`. This analysis is not by itself an IF1 release.',
             'All preprocessing is fitted on A1 and applied unchanged to A2/A3.',
             'No Loss target is read. A2/A3 are same-source extensions with overlapping',
             'records, not independent external replications.', '',
             '## Explicit settings', '', '```json',
             json.dumps(settings, indent=2, sort_keys=True, allow_nan=False), '```', '',
             '## Domain estimates and uncertainty', '',
             '| Population | Aggregator | Domain | Q | CI low | CI high | n |',
             '| --- | --- | --- | ---: | ---: | ---: | ---: |']
    for population, report in analyses.items():
        for method, summary in report['aggregators'].items():
            for domain, values in summary['domains'].items():
                lines.append(f"| {population} | {method} | {domain} | {values['q']:.6f} | {values['ci'][0]:.6f} | {values['ci'][1]:.6f} | {values['n']} |")
    lines += ['', '## Conflict and sampling stability', '',
              'The following compact evidence includes threshold curves, all 231 descriptive',
              'indicator associations, aggregation changes, and overlap-preserving uncertainty.',
              'No significance claim is made. Intervals condition on the fitted preprocessing.', '',
              '```json', json.dumps({'conflict': {k: v['conflict'] for k, v in analyses.items()},
                                     'sampling_comparisons': comparisons},
                                    sort_keys=True, indent=2, allow_nan=False), '```', '',
              'Primary Q selection is still subject to stability, semantic and sensitivity',
              'assessment; it is never selected using downstream Loss regression.', '']
    return '\n'.join(lines)


def main() -> int:
    seed, settings = load_settings('quality')
    if settings.get('missing_signal_policy') == 'complete_case_confirmed_literal_nan':
        from src.quality.closure import run_quality_closure
        return run_quality_closure(seed, settings)
    require_settings(settings, ['bootstrap_replicates', 'confidence', 'conflict_thresholds',
                                'material_rank_correlation', 'aggregators', 'families',
                                'direction_overrides', 'desirability_intervals', 'missing_signal_policy'])
    if settings['missing_signal_policy'] != 'reject':
        raise ValueError('only reject is implemented; missing-signal treatment still needs M1 guidance')
    print('seed:', seed, flush=True)
    directions = {**sc.DIRECTIONS, **settings['direction_overrides']}
    source = require(ATT_A / 'slimpajama_quality_signal_sample.jsonl.xz')
    prep = QualityPreprocessor.fit(stream_quality(source), directions=directions,
                                   intervals=settings['desirability_intervals'])
    populations = {'A1': collect(prep, source)}
    for name, domain in [('A2', 'arxiv'), ('A3', 'github')]:
        matches = sorted((ATT_A / 'slimpajama_quality_extended').glob(domain + '_*.jsonl.xz'))
        if len(matches) != 1:
            raise ValueError('extension files are absent or ambiguous')
        populations[name] = collect(prep, matches[0], domain)
    uncertainty = dict(seed=seed, replicates=settings['bootstrap_replicates'], confidence=settings['confidence'])
    analyses, scores = {}, {}
    for name, (matrix, domains, keys) in populations.items():
        scores[name], summaries = {}, {}
        for method in settings['aggregators']:
            q = aggregate(matrix, method, families=settings['families'])
            scores[name][method] = q
            summaries[method] = domain_estimates(q, domains, **uncertainty)
        analyses[name] = {'aggregators': summaries,
                          'conflict': conflict_analysis(matrix, thresholds=settings['conflict_thresholds'],
                                                        material_rho=settings['material_rank_correlation'],
                                                        families=settings['families'])}
    comparisons = {}
    for name, domain in [('A2', 'arxiv'), ('A3', 'github')]:
        mask = np.asarray(populations['A1'][1]) == domain
        subset_keys = [k for k, keep in zip(populations['A1'][2], mask) if keep]
        comparisons[name] = {method: overlapping_sample_comparison(scores['A1'][method][mask], scores[name][method],
                                                                  subset_keys, populations[name][2], **uncertainty)
                             for method in settings['aggregators']}
        for method in settings['aggregators']:
            baseline = analyses['A1']['aggregators'][method]
            substituted = {**baseline['domains'], domain: analyses[name]['aggregators'][method]['domains'][domain]}
            comparisons[name][method]['A1_domain_ranking'] = domain_ranking(baseline)
            comparisons[name][method]['ranking_after_extension_substitution'] = domain_ranking({'domains': substituted})
    out = ensure(TABLES) / 'q1-quality-analysis.md'
    out.write_text(render_quality(analyses, comparisons, settings), encoding='utf-8', newline='\n')
    print('wrote', out.relative_to(REPO_ROOT).as_posix())
    print('IF1 release remains subject to scientific stability/sensitivity assessment')
    return 0


if __name__ == '__main__':
    try:
        raise SystemExit(main())
    except (ValueError, KeyError, FileNotFoundError) as error:
        print('STOP:', error, file=sys.stderr)
        raise SystemExit(2)
