"""Q2 end-to-end reproduction: every generator twice, byte-identical artifacts.

Runs the complete Q2 generator surface in two full passes, hashes every
artifact after each pass, and requires the two passes to agree byte for byte.
It also snapshots the raw attachment trees before and after both passes and
requires them unchanged, so a generator that wrote into its own inputs would
fail here.

Writes `results/tables/q2-reproduction.md`. Regenerate; do not edit by hand.

    conda run -n modeling-research-2026 --no-capture-output python scripts/q2_reproduce.py

Artifact hashes are of the bytes as generated (LF line endings). A checkout on
a machine that converts line endings will hash differently on disk; compare
against the generated bytes or normalise CRLF to LF first.
"""

from __future__ import annotations

import hashlib
import json
import platform
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from src.paths import ATT_A, ATT_B, PROBLEM_F_INTERFACES, TABLES, ensure  # noqa: E402

GENERATORS = [
    "q2_fit_classic.py",
    "q2_uncertainty.py",
    "q2_substitution.py",
    "q2_audit_quality_data.py",
    "q2_final_closure.py",
]

ARTIFACTS = [
    TABLES / "q2-classic-fit.md",
    TABLES / "q2-uncertainty-robustness.md",
    TABLES / "q2-substitution.md",
    TABLES / "q2-quality-data-audit.md",
    TABLES / "q2-final-closure.md",
    PROBLEM_F_INTERFACES / "IF3_classic.json",
]

RAW_ROOTS = [ATT_B, ATT_A / "regmix_tables"]


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def raw_digest():
    out = {}
    for root in RAW_ROOTS:
        for p in sorted(root.rglob("*")):
            if p.is_file():
                st = p.stat()
                out[p.relative_to(REPO).as_posix()] = (sha(p), st.st_size, st.st_mtime_ns)
    return out


def run_pass(label: str):
    for script in GENERATORS:
        print(label + ": " + script, flush=True)
        subprocess.run([sys.executable, str(REPO / "scripts" / script)], cwd=REPO, check=True,
                       stdout=subprocess.DEVNULL)
    return {p.relative_to(REPO).as_posix(): sha(p) for p in ARTIFACTS}


def main() -> int:
    before = raw_digest()
    first = run_pass("pass 1")
    second = run_pass("pass 2")
    after = raw_digest()

    identical = first == second
    raw_unchanged = before == after and len(before) > 0

    import numpy
    import pandas
    import scipy
    import yaml
    runtime = {"python": platform.python_version(), "numpy": numpy.__version__,
               "scipy": scipy.__version__, "pandas": pandas.__version__, "pyyaml": yaml.__version__}

    lines = [
        "# Q2 reproduction",
        "",
        "Generated by `scripts/q2_reproduce.py`. Do not edit by hand.",
        "",
        "Every Q2 generator was run in two complete passes. Hashes are of the bytes as",
        "generated (LF line endings).",
        "",
        "Runtime: " + json.dumps(runtime, sort_keys=True),
        "",
        "| Artifact | SHA-256, pass 1 | Pass 2 identical |",
        "| --- | --- | --- |",
    ]
    for key in first:
        lines.append("| `" + key + "` | `" + first[key] + "` | "
                     + ("yes" if first[key] == second[key] else "**NO**") + " |")
    lines += [
        "",
        "Generators, in order: " + ", ".join("`scripts/" + g + "`" for g in GENERATORS) + ".",
        "",
        "Two passes byte-identical: **" + ("PASS" if identical else "FAIL") + "**.",
        "",
        "Raw attachment trees (" + str(len(before)) + " files under `"
        + "`, `".join(r.relative_to(REPO).as_posix() for r in RAW_ROOTS)
        + "`) unchanged in content, size and modification time across both passes: **"
        + ("PASS" if raw_unchanged else "FAIL") + "**.",
    ]
    out = ensure(TABLES) / "q2-reproduction.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("wrote " + out.relative_to(REPO).as_posix())
    print("two passes identical: " + str(identical) + "; raw trees unchanged: " + str(raw_unchanged))
    return 0 if identical and raw_unchanged else 1


if __name__ == "__main__":
    raise SystemExit(main())
