"""Marginal effects and iso-loss substitution for the quality-aware law.

Answers, for the adopted form
``L = E + A N^(-alpha) + B (Q^gamma D)^(-beta)``:

* how much does loss move per unit of N, D and Q;
* what is the elasticity of loss, and of *excess* loss, in each;
* along a curve of constant loss, how does required N trade against Q.

The sign of that last quantity is the load-bearing one. Both L_Q and L_N are
negative, so ``dN/dQ = -L_Q/L_N`` is negative: better data needs FEWER
parameters for the same loss. The common error is to report it positive.

PROVENANCE. The quality exponent used here is estimated from a designed,
unreplicated grid (see `q2-quality-data-audit.md`). Everything below therefore
describes the supplied quality mechanism, not a measured property of real
models. The numbers are reported as calibration, and are labelled as such in
the output.

Writes `results/tables/q2-substitution.md`. Regenerate; do not edit.

    python scripts/q2_substitution.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.paths import ATT_B, TABLES, ensure, require  # noqa: E402
from src.scaling.quality import (  # noqa: E402
    InfeasibleEquivalent,
    elasticities,
    equivalent_capacity,
    fit_quality_law,
    iso_loss_dn_dq,
    parameter_saving,
    partials,
)

SOURCE = "supplementary_NQ_experiment_expanded.csv"   # B7: the superset of B6


def fmt(x, digits=5):
    return format(float(x), "." + str(digits) + "g")


def main() -> int:
    frame = pd.read_csv(require(ATT_B / SOURCE))
    n = frame["N_params_B"].to_numpy(float)
    d = frame["D_tokens_B"].to_numpy(float)
    q = frame["Q_score"].to_numpy(float)
    loss = frame["val_loss"].to_numpy(float)

    fit = fit_quality_law(n, d, q, loss)
    theta = fit.raw
    p = fit.params

    # Evaluation points inside the fitted box: small / mid / large.
    eval_n = np.array([0.41, 2.8, 11.97])
    eval_d = np.array([50.0, 150.0, 600.0])
    eval_q = np.array([0.5, 0.7, 0.9])

    part = partials(theta, eval_n, eval_d, eval_q)
    el = elasticities(theta, eval_n, eval_d, eval_q)
    dndq = iso_loss_dn_dq(theta, eval_n, eval_d, eval_q)
    base_loss = fit.predict(eval_n, eval_d, eval_q)

    ensure(TABLES)
    out = TABLES / "q2-substitution.md"
    lines = []
    W = lines.append

    W("# Q2 marginal effects and iso-loss substitution")
    W("")
    W("Generated by `scripts/q2_substitution.py`. Do not edit by hand.")
    W("")
    W("Form: `L(N,D,Q) = E + A N^(-alpha) + B (Q^gamma D)^(-beta)`, with N in")
    W("billions of parameters and D in billions of tokens, as stored in the")
    W("source table.")
    W("")
    W("> **Provenance.** The quality exponent below is estimated from a")
    W("> designed, unreplicated (N, D, Q) grid. The estimator recovers the")
    W("> supplied quality mechanism; it does not establish that real models obey")
    W("> this exponent. See `q2-quality-data-audit.md`.")
    W("")

    W("## Fitted parameters")
    W("")
    W("| Parameter | Value |")
    W("| --- | ---: |")
    for name in ("E", "A", "alpha", "B", "beta", "gamma"):
        W("| " + name + " | " + fmt(p[name]) + " |")
    W("")
    W("Fitted on " + str(fit.n_obs) + " rows. " + str(fit.starts_tried) + " cold")
    W("starting points were screened at low precision, the best "
      + str(fit.starts_refined) + " refined to full precision, and "
      + str(fit.starts_converged) + " of those converged.")
    W("")
    W("Validity box: N " + fmt(fit.validity_box["N"][0]) + " - "
      + fmt(fit.validity_box["N"][1]) + " B params, D "
      + fmt(fit.validity_box["D"][0]) + " - " + fmt(fit.validity_box["D"][1])
      + " B tokens, Q " + fmt(fit.validity_box["Q"][0]) + " - "
      + fmt(fit.validity_box["Q"][1]) + ".")
    W("")

    W("## Marginal effects")
    W("")
    W("All three partials are negative throughout the valid region: more")
    W("parameters, more tokens and better data each reduce loss.")
    W("")
    W("| N (B) | D (B) | Q | L | dL/dN | dL/dD | dL/dQ |")
    W("| ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
    for i in range(len(eval_n)):
        W("| " + fmt(eval_n[i]) + " | " + fmt(eval_d[i]) + " | " + fmt(eval_q[i])
          + " | " + fmt(base_loss[i]) + " | " + fmt(part["dL_dN"][i])
          + " | " + fmt(part["dL_dD"][i]) + " | " + fmt(part["dL_dQ"][i]) + " |")
    W("")

    W("## Elasticities")
    W("")
    W("Three quantities that are easy to conflate, reported separately.")
    W("`dlogL` is the elasticity of TOTAL loss, damped by the irreducible floor")
    W("E. `dlogLex` is the elasticity of EXCESS (reducible) loss, `L - E`, which")
    W("is the quantity that equals `-alpha` in the pure power-law limit. They")
    W("are not interchangeable and the total-loss version is always smaller in")
    W("magnitude.")
    W("")
    W("| N (B) | D (B) | Q | dlogL/dlogN | dlogL/dlogD | dlogL/dlogQ | dlogLex/dlogN | dlogLex/dlogD | dlogLex/dlogQ |")
    W("| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
    for i in range(len(eval_n)):
        W("| " + fmt(eval_n[i]) + " | " + fmt(eval_d[i]) + " | " + fmt(eval_q[i])
          + " | " + fmt(el["dlogL_dlogN"][i]) + " | " + fmt(el["dlogL_dlogD"][i])
          + " | " + fmt(el["dlogL_dlogQ"][i]) + " | " + fmt(el["dlogLex_dlogN"][i])
          + " | " + fmt(el["dlogLex_dlogD"][i]) + " | " + fmt(el["dlogLex_dlogQ"][i]) + " |")
    W("")

    W("## Iso-loss substitution of parameters for data quality")
    W("")
    W("`dN/dQ = -L_Q / L_N`. Both partials are negative, so this is **negative**:")
    W("raising quality lowers the parameter count needed for the same loss.")
    W("")
    W("| N (B) | D (B) | Q | dN/dQ (B params per unit Q) |")
    W("| ---: | ---: | ---: | ---: |")
    for i in range(len(eval_n)):
        W("| " + fmt(eval_n[i]) + " | " + fmt(eval_d[i]) + " | " + fmt(eval_q[i])
          + " | " + fmt(dndq[i]) + " |")
    W("")

    W("## Parameter saving and equivalent capacity")
    W("")
    W("Two different questions about the same quality improvement, which are")
    W("routinely conflated:")
    W("")
    W("* **Parameter saving** `[N^(-alpha) + R/A]^(-1/alpha) - N` - how many")
    W("  parameters can now be *removed* while holding loss constant. Always")
    W("  negative and always finite.")
    W("* **Equivalent capacity** `[N^(-alpha) - R/A]^(-1/alpha) - N` - how many")
    W("  parameters would have been needed to buy the same gain *instead*.")
    W("  Positive, and finite only while `R < A N^(-alpha)`; it diverges at that")
    W("  boundary, which is a result and not a numerical failure.")
    W("")
    W("Here R is the fall in the data/quality term produced by raising Q from")
    W("its base value to the target, holding D fixed.")
    W("")
    W("| N (B) | D (B) | Q base | Q target | R | Parameter saving (B) | Equivalent capacity (B) |")
    W("| ---: | ---: | ---: | ---: | ---: | ---: | ---: |")

    a, b, e, alpha, beta, gamma = theta
    A, B = np.exp(a), np.exp(b)
    for i in range(len(eval_n)):
        n_i, d_i, q_i = eval_n[i], eval_d[i], eval_q[i]
        for q_target in (q_i * 1.1, q_i * 1.5, min(q_i * 3.0, 1.0)):
            if q_target <= q_i:
                continue
            term_base = B * (q_i ** gamma * d_i) ** (-beta)
            term_new = B * (q_target ** gamma * d_i) ** (-beta)
            R = term_base - term_new
            save = float(parameter_saving(theta, np.array([n_i]), np.array([R]))[0])
            try:
                equiv = fmt(float(equivalent_capacity(theta, np.array([n_i]), np.array([R]))[0]))
            except InfeasibleEquivalent:
                headroom = A * n_i ** (-alpha)
                equiv = ("no finite equivalent (R/headroom = "
                         + format(R / headroom, ".4g") + ")")
            W("| " + fmt(n_i) + " | " + fmt(d_i) + " | " + fmt(q_i) + " | "
              + fmt(q_target) + " | " + fmt(R) + " | " + fmt(save) + " | " + equiv + " |")
    W("")
    W("Where the equivalent capacity is reported as having no finite value, the")
    W("quality improvement removes more loss than the parameter term can supply")
    W("at that N: no parameter count, however large, buys the same gain. That")
    W("is stated rather than hidden behind a blank cell.")
    W("")

    W("## Verification")
    W("")
    W("Every formula above is checked by `scripts/selftest_quality.py`, which")
    W("compares each analytic partial against a central finite difference,")
    W("asserts the three monotonicity signs and the negative iso-loss slope,")
    W("checks that the two substitution transforms exactly restore the loss they")
    W("claim to, requires the equivalent-capacity boundary to raise rather than")
    W("return NaN, and finally feeds a deliberately invalid law (negative")
    W("gamma) to confirm the sign checks can fail.")
    W("")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote " + str(out.relative_to(Path.cwd())))
    print("  gamma = " + fmt(p["gamma"]) + "  alpha = " + fmt(p["alpha"])
          + "  beta = " + fmt(p["beta"]))
    print("  dN/dQ at eval points: " + ", ".join(fmt(v) for v in dndq)
          + "  (all must be negative)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
