"""Complementary uncertainty diagnostics for the classic N-D law.

The existing clustered bootstrap is the right resampling unit, but it rests on
only eight trajectory clusters, and the table it resamples is itself close to a
deterministic evaluation of a published law. Its intervals are therefore
extremely narrow for two compounding reasons, neither of which is "real model
scaling is known this precisely".

Two further diagnostics are added, because one interval family presented alone
invites exactly that misreading:

1. **Leave-one-trajectory-out.** Refit with each model dropped in turn. This
   answers "how much does any single trajectory move the answer?", which a
   bootstrap over the same eight clusters cannot: every replicate still draws
   from the same eight.

2. **Profile identifiability.** Fix one parameter away from its estimate,
   re-optimise the rest, and record how fast the objective rises. A parameter
   the data cannot pin down shows a flat profile; a sharply rising profile
   means the data determine it - for whatever mechanism produced that data.

Writes `results/tables/q2-uncertainty-robustness.md`. Regenerate; do not edit.

    python scripts/q2_uncertainty.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.paths import TABLES, ensure  # noqa: E402
from src.scaling import data as bdata  # noqa: E402
from src.scaling import law  # noqa: E402

PARAMS = ("E", "A", "alpha", "B", "beta")
SEED = 20260923


def fmt(x, digits=6):
    return format(float(x), "." + str(digits) + "g")


def warm_starts(anchor):
    a = np.asarray(anchor, float)
    step = np.array([0.5, 0.5, 0.1, 0.02, 0.02])
    return [a, a + step, a - step]


def jackknife(n, d, loss, clusters, anchor):
    """Refit with each trajectory removed in turn."""
    unique = sorted(set(clusters))
    out = {}
    for held in unique:
        mask = np.asarray([c != held for c in clusters])
        fit = law.fit_law(n[mask], d[mask], loss[mask], starts=warm_starts(anchor))
        out[held] = fit.params
    return out


def profile(n, d, loss, anchor, which, factors):
    """Profile the objective in one parameter, re-optimising the others.

    Works in the log parameterisation used by the fitter. ``which`` indexes
    (log A, log B, log E, alpha, beta).
    """
    from scipy.optimize import minimize
    from scipy.special import logsumexp

    log_n, log_d, log_l = np.log(n), np.log(d), np.log(loss)
    anchor = np.asarray(anchor, float)

    def obj_full(theta):
        stack = np.vstack([
            np.full_like(log_n, theta[2]),
            theta[0] - theta[3] * log_n,
            theta[1] - theta[4] * log_d,
        ])
        return law._huber(logsumexp(stack, axis=0) - log_l)

    base = obj_full(anchor)
    bounds = [(-20.0, 40.0), (-20.0, 40.0), (-10.0, 3.0), (1e-3, 3.0), (1e-3, 3.0)]

    rows = []
    for factor in factors:
        theta0 = anchor.copy()
        # A, B, E are held in log space, so a multiplicative change on the
        # natural parameter is an additive change on the log parameter.
        if which in (0, 1, 2):
            fixed = anchor[which] + np.log(factor)
        else:
            fixed = anchor[which] * factor

        free_idx = [i for i in range(5) if i != which]

        def obj_free(free):
            theta = theta0.copy()
            theta[which] = fixed
            for slot, i in enumerate(free_idx):
                theta[i] = free[slot]
            return obj_full(theta)

        res = minimize(
            obj_free,
            anchor[free_idx],
            method="L-BFGS-B",
            bounds=[bounds[i] for i in free_idx],
            options={"maxiter": 20000, "ftol": 1e-15, "gtol": 1e-12},
        )
        rows.append((factor, float(res.fun), float(res.fun / base) if base > 0 else float("inf")))
    return base, rows


def main() -> int:
    b1 = bdata.load_pythia_log()
    frame = b1.frame
    n = frame["N_params_B"].to_numpy(float) * 1e9
    d = frame["D_tokens_B"].to_numpy(float) * 1e9
    loss = frame["val_loss"].to_numpy(float)
    clusters = frame["model_id"].tolist()

    full = law.fit_law(n, d, loss, clusters=clusters)
    anchor = np.asarray(full.raw, float)

    boot = law.cluster_bootstrap(n, d, loss, clusters, replicates=400, seed=SEED)
    jack = jackknife(n, d, loss, clusters, anchor)

    # Profile each parameter over a multiplicative grid.
    factors = [0.90, 0.95, 0.98, 1.0, 1.02, 1.05, 1.10]
    prof = {}
    for slot, name in ((0, "A"), (1, "B"), (2, "E"), (3, "alpha"), (4, "beta")):
        prof[name] = profile(n, d, loss, anchor, slot, factors)

    ensure(TABLES)
    out = TABLES / "q2-uncertainty-robustness.md"
    lines = []
    W = lines.append

    W("# Q2 classic law: uncertainty and robustness")
    W("")
    W("Generated by `scripts/q2_uncertainty.py`. Do not edit by hand.")
    W("")
    W("Three diagnostics for the same five parameters. They answer different")
    W("questions and are reported side by side so that no single interval is")
    W("read as \"the\" uncertainty.")
    W("")
    W("The fit data is " + str(len(frame)) + " checkpoints from "
      + str(len(set(clusters))) + " trajectories of a single model family, and")
    W("its loss column is consistent with a deterministic evaluation of a")
    W("published law (see `q2-classic-fit.md`). Both facts narrow every interval")
    W("below, and neither is a statement about how precisely real model scaling")
    W("is known.")
    W("")

    W("## Point estimate, bootstrap interval, and leave-one-trajectory-out range")
    W("")
    W("| Parameter | Full fit | Bootstrap 95% CI | Bootstrap SD | Leave-one-out min | Leave-one-out max | Max relative shift |")
    W("| --- | ---: | ---: | ---: | ---: | ---: | ---: |")
    for name in PARAMS:
        est = full.params[name]
        b = boot[name]
        vals = [jack[k][name] for k in jack]
        lo, hi = min(vals), max(vals)
        shift = max(abs(v - est) / abs(est) for v in vals)
        W("| " + name + " | " + fmt(est) + " | ["
          + fmt(b["lo2.5"]) + ", " + fmt(b["hi97.5"]) + "] | " + fmt(b["sd"], 4)
          + " | " + fmt(lo) + " | " + fmt(hi) + " | " + format(shift * 100, ".3g") + "% |")
    W("")
    # Compare the two widths rather than asserting a relationship: which is
    # wider is a fact about this data, and hard-coding a sentence about it is
    # how a generated table acquires a claim nobody re-checked.
    wider, narrower = [], []
    for name in PARAMS:
        b = boot[name]
        vals = [jack[k][name] for k in jack]
        boot_w = float(b["hi97.5"] - b["lo2.5"])
        loo_w = float(max(vals) - min(vals))
        (wider if loo_w > boot_w else narrower).append((name, loo_w / boot_w))

    W("| Parameter | Bootstrap CI width | Leave-one-out width | Ratio LOO / bootstrap |")
    W("| --- | ---: | ---: | ---: |")
    for name in PARAMS:
        b = boot[name]
        vals = [jack[k][name] for k in jack]
        boot_w = float(b["hi97.5"] - b["lo2.5"])
        loo_w = float(max(vals) - min(vals))
        W("| " + name + " | " + fmt(boot_w, 4) + " | " + fmt(loo_w, 4)
          + " | " + format(loo_w / boot_w, ".3f") + " |")
    W("")
    W("The leave-one-trajectory-out range is **narrower** than the bootstrap")
    W("interval for " + str(len(narrower)) + " of " + str(len(PARAMS))
      + " parameters. That is the expected direction and not a")
    W("contradiction: the bootstrap draws eight trajectories with replacement,")
    W("so a replicate can contain the same trajectory several times and omit")
    W("others entirely, which is a far harsher perturbation than removing")
    W("exactly one. The two answer different questions, and the leave-one-out")
    W("column is the one that answers \"could a single trajectory be carrying")
    W("this result?\".")
    W("")
    W("It cannot. No single trajectory moves any parameter by more than")
    W(format(max(max(abs(jack[k][name] - full.params[name]) / abs(full.params[name])
                     for k in jack) for name in PARAMS) * 100, ".3g")
      + "% of its estimate.")
    W("")

    W("### Per-trajectory detail")
    W("")
    W("| Trajectory dropped (N, billions) | " + " | ".join(PARAMS) + " |")
    W("| --- | " + " | ".join("---:" for _ in PARAMS) + " |")
    for key in sorted(jack, key=float):
        W("| " + key + " | " + " | ".join(fmt(jack[key][p]) for p in PARAMS) + " |")
    W("")

    W("## Profile identifiability")
    W("")
    W("Each parameter is fixed at a multiple of its estimate and the remaining")
    W("four are re-optimised. The value shown is the objective relative to its")
    W("minimum: 1.00 means the displaced parameter costs nothing and the data")
    W("cannot distinguish it, while a large value means the data pin it down.")
    W("")
    header = "| Parameter | " + " | ".join(format(f, ".2f") + "x" for f in factors) + " |"
    W(header)
    W("| --- | " + " | ".join("---:" for _ in factors) + " |")
    for name in PARAMS:
        base, rows = prof[name]
        cells = []
        for _factor, _value, ratio in rows:
            cells.append(format(ratio, ".4g") if np.isfinite(ratio) else "inf")
        W("| " + name + " | " + " | ".join(cells) + " |")
    W("")
    W("Objective at the optimum: " + fmt(prof["A"][0]) + " (Huber on log L).")
    W("")

    flat = [name for name in PARAMS
            if max(r[2] for r in prof[name][1]) < 1.01]
    if flat:
        W("**Not identified:** " + ", ".join(flat) + " - displacing the parameter")
        W("by 10% costs less than 1% of the objective, so the data do not")
        W("determine it and its interval above should not be believed.")
    else:
        W("Every parameter has a sharply rising profile, so all five are")
        W("determined by this data. What that data *is* remains the limiting")
        W("factor: determining the parameters of a recovered generator is not")
        W("the same as measuring how real models scale.")
    W("")

    W("## What is NOT available here")
    W("")
    W("Leave-one-model-family-out cannot be computed on this table: every")
    W("trajectory in it belongs to the same family, so the family-level")
    W("resampling unit has exactly one level. Cross-family sensitivity is only")
    W("observable through the independent validation tables, not through a")
    W("refit of this one.")
    W("")

    # A trailing empty entry would emit a blank line at end of file, which
    # `git diff --check` reports as an error.
    while lines and lines[-1] == "":
        lines.pop()
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote " + str(out.relative_to(Path.cwd())))
    for name in PARAMS:
        vals = [jack[k][name] for k in jack]
        est = full.params[name]
        print("  " + name.ljust(6) + " est=" + fmt(est)
              + "  LOO shift max=" + format(max(abs(v - est) / abs(est) for v in vals) * 100, ".3g") + "%")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
