"""Generate canonical receipt-bound baseline N-D allocation results.

Writes the selected observed-context baseline allocation for each source-supported
compute budget. The context is a presentation row, not an optimization choice.

Run through the declared environment:
    conda run -n modeling-research-2026 --no-capture-output python scripts/q3_allocate.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Mapping

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from src.alloc import (  # noqa: E402
    BaselineCompute,
    NoValidityBoxAllocation,
    describe_allocation_uncertainty,
    load_classic_if3,
    load_source_receipt,
    solve_baseline,
)
from src.paths import TABLES, ensure  # noqa: E402

PRESENTATION_CONTEXT_TOKENS = 4096


def fmt(value: float, digits: int = 8) -> str:
    return format(float(value), "." + str(digits) + "g")


def result_record(result) -> dict[str, object]:
    labels = result.validity_labels
    return {
        "status": "VALID_ALLOCATION",
        "budget_flops": result.compute.budget_flops,
        "context_tokens": result.compute.context_tokens,
        "kappa_flops_per_parameter_token": result.compute.kappa,
        "n_parameters_raw": result.n_parameters,
        "d_tokens_raw": result.d_tokens,
        "predicted_loss": result.predicted_loss,
        "feasibility_label": result.feasibility_label,
        "active_boundary": result.active_boundary,
        "validity_labels": dict(labels),
        "stationary_residual_dloss_dlog_n": result.stationary_residual,
        "budget_saturation_residual_flops": result.budget_saturation_residual_flops,
        "cost": dict(result.cost),
        "unconstrained_diagnostic": {
            "n_parameters_raw": result.unconstrained_n_parameters,
            "d_tokens_raw": result.unconstrained_d_tokens,
            "predicted_loss": result.unconstrained_predicted_loss,
            "inside_canonical_validity_box": not result.constrained,
        },
    }


def unavailable_record(budget: float) -> dict[str, object]:
    return {
        "status": "NO_VALIDITY_BOX_ALLOCATION",
        "budget_flops": budget,
        "context_tokens": PRESENTATION_CONTEXT_TOKENS,
        "reason": (
            "no point can simultaneously saturate this receipt-supported budget and remain "
            "inside the accepted raw N/D IF3 validity box"
        ),
    }


def solve_record(classic, receipt, budget: float) -> dict[str, object]:
    try:
        return result_record(solve_baseline(
            classic,
            BaselineCompute.create(receipt, budget, PRESENTATION_CONTEXT_TOKENS),
        ))
    except NoValidityBoxAllocation:
        return unavailable_record(budget)


def markdown_table(records: list[Mapping[str, object]], uncertainty: Mapping[str, object]) -> str:
    lines = [
        "# Q3 canonical baseline allocation",
        "",
        "Generated by `scripts/q3_allocate.py`. Do not edit by hand.",
        "",
        "This table uses the accepted classic raw-N/raw-D IF3 law and the frozen",
        "`results/tables/q3-source-receipt.json` gate. Every row is at the semantic",
        "baseline `Q0`, so quality preprocessing compute and quality share are exactly zero.",
        "",
        "The observed `L_ctx = 4096`-token row is selected only for compact presentation; it",
        "is not a preferred empirical regime or an optimized context choice. Full context",
        "sensitivity is in `results/tables/q3-context-sensitivity.md`.",
        "",
        "| Budget (FLOPs) | L_ctx (tokens) | kappa | N (raw parameters) | D (raw tokens) | Predicted loss | Feasibility | Active boundary | Base share | Attention share | Quality share | Budget residual (FLOPs) |",
        "| ---: | ---: | ---: | ---: | ---: | ---: | --- | --- | ---: | ---: | ---: | ---: |",
    ]
    for record in records:
        if record["status"] != "VALID_ALLOCATION":
            lines.append(
                "| " + fmt(record["budget_flops"]) + " | " + str(record["context_tokens"])
                + " | — | — | — | — | unavailable | `NO_VALIDITY_BOX_ALLOCATION`"
                + " | — | — | — | — |"
            )
            continue
        cost = record["cost"]
        assert isinstance(cost, Mapping)
        lines.append(
            "| " + fmt(record["budget_flops"]) + " | " + str(record["context_tokens"])
            + " | " + fmt(record["kappa_flops_per_parameter_token"])
            + " | " + fmt(record["n_parameters_raw"])
            + " | " + fmt(record["d_tokens_raw"])
            + " | " + fmt(record["predicted_loss"])
            + " | " + str(record["feasibility_label"])
            + " | `" + str(record["active_boundary"]) + "`"
            + " | " + fmt(cost["base_share"])
            + " | " + fmt(cost["attention_share"])
            + " | " + fmt(cost["quality_share"])
            + " | " + fmt(cost["budget_residual_flops"]) + " |"
        )
    lines += [
        "",
        "## Validity and diagnostic status",
        "",
        "Canonical rows are inside the accepted raw N/D validity box. If the unconstrained",
        "stationary point lies outside that box, it is retained only as a diagnostic in the",
        "machine-readable companion and is never presented as a canonical allocation.",
        "",
        "Any `NO_VALIDITY_BOX_ALLOCATION` row is explicitly unavailable: no raw-N/raw-D",
        "point can simultaneously saturate that receipt-supported budget and remain inside",
        "the accepted IF3 validity box. It is not silently clipped or extrapolated.",
        "",
        "## Uncertainty evidence",
        "",
        str(uncertainty["limitation"]),
        "",
        "Released representation: `" + str(uncertainty["representation"]) + "`; bootstrap unit: `"
        + str(uncertainty["source_unit"]) + "`; replicates: `" + str(uncertainty["replicates"])
        + "`; clusters: `" + str(uncertainty["n_clusters"]) + "`.",
        "",
        "No numerical nonbaseline quality scenario ran. Cross-scale quality benefit remains prohibited",
        "because the accepted classic IF3 law has no quality-loss term.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    classic = load_classic_if3()
    receipt = load_source_receipt()
    if PRESENTATION_CONTEXT_TOKENS not in receipt.contexts_tokens:
        raise RuntimeError("selected presentation context is not receipt-supported")
    uncertainty = describe_allocation_uncertainty(classic)
    records = [
        solve_record(classic, receipt, budget)
        for budget in receipt.budgets_flops
    ]
    payload = {
        "schema_version": "q3-allocation-v1",
        "purpose": "T-010 canonical baseline N-D allocation; no quality-coordinate optimization",
        "receipt_path": "results/tables/q3-source-receipt.json",
        "classic_if3_sha256": classic.sha256,
        "presentation_context_tokens": PRESENTATION_CONTEXT_TOKENS,
        "presentation_context_role": "observed presentation row only; not a preferred regime or optimized context",
        "quality_coordinate": "Q0",
        "quality_preprocessing_flops": 0.0,
        "cross_scale_quality_benefit": "PROHIBITED",
        "uncertainty_evidence": {
            "representation": uncertainty.representation,
            "source_unit": uncertainty.source_unit,
            "replicates": uncertainty.replicates,
            "n_clusters": uncertainty.n_clusters,
            "seed": uncertainty.seed,
            "parameter_intervals": dict(uncertainty.parameter_intervals),
            "complete_parameter_vectors_released": uncertainty.complete_parameter_vectors_released,
            "allocation_propagation_available": uncertainty.allocation_propagation_available,
            "limitation": uncertainty.limitation,
        },
        "allocations": records,
    }
    out_dir = ensure(TABLES)
    json_path = out_dir / "q3-allocation.json"
    markdown_path = out_dir / "q3-allocation.md"
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    markdown_path.write_text(markdown_table(records, payload["uncertainty_evidence"]), encoding="utf-8", newline="\n")
    print("wrote " + json_path.relative_to(REPO).as_posix())
    print("wrote " + markdown_path.relative_to(REPO).as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
