"""Generate baseline allocations over every source-supported budget and observed context.

``L_ctx`` is exogenous: it enters only through ``kappa = 6 + eta L_ctx`` and is
never optimized.  At a fixed budget, adjacent observed contexts whose regimes
differ *bracket* a regime change; they do not locate a continuous context
threshold, and the C7 grid is neither interpolated nor extended.

Run through the declared environment:
    conda run -n modeling-research-2026 --no-capture-output python scripts/q3_context_sensitivity.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Mapping

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from src.alloc import (  # noqa: E402
    BaselineCompute,
    NoValidityBoxAllocation,
    install_q3_input_guard,
    load_all_accepted_interfaces,
    load_classic_if3,
    load_source_receipt,
    solve_baseline,
)
from src.alloc.report import allocation_record, fmt, infeasible_record, unused_text, write_artifacts  # noqa: E402


def solve_record(classic: Any, receipt: Any, budget: float, context: int) -> dict[str, Any]:
    try:
        return allocation_record(solve_baseline(classic, BaselineCompute.create(receipt, budget, context)))
    except NoValidityBoxAllocation as exc:
        return infeasible_record(budget, context, str(exc))


def brackets(rows: list[Mapping[str, Any]], budgets: tuple[float, ...]) -> list[dict[str, Any]]:
    """Adjacent observed contexts, at one budget, whose regimes differ."""
    output: list[dict[str, Any]] = []
    for budget in budgets:
        members = sorted((row for row in rows if row["budget_flops"] == budget), key=lambda row: row["context_tokens"])
        for low, high in zip(members, members[1:]):
            low_regime = low.get("regime", low["status"])
            high_regime = high.get("regime", high["status"])
            if low_regime != high_regime:
                output.append({
                    "budget_flops": budget,
                    "lower_observed_context_tokens": low["context_tokens"],
                    "upper_observed_context_tokens": high["context_tokens"],
                    "regime_at_lower": low_regime,
                    "regime_at_upper": high_regime,
                    "claim": "observed rows bracket a regime change; no continuous context threshold is identified",
                })
    return output


def markdown(rows: list[Mapping[str, Any]], bracket_rows: list[Mapping[str, Any]], parity: float) -> str:
    lines = [
        "# Q3 baseline context sensitivity",
        "",
        "Generated by `scripts/q3_context_sensitivity.py`. Do not edit by hand.",
        "",
        "Every organizer representative budget crossed with every observed C7 context. `L_ctx` is",
        "exogenous and enters only through `kappa = 6 + eta L_ctx`; it is not optimized, and no preferred",
        "context is implied. Constraint `kappa N D <= C` inside the accepted IF3 box, semantic baseline",
        "`Q0` (quality compute exactly zero). Model-conditional, not observed.",
        "",
        "| Budget C (FLOPs) | L_ctx (tokens) | kappa | N* | D* | Predicted loss | Regime | Unused (FLOPs) | Utilization | Base share of spent | Attention share of spent |",
        "| ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        if row["status"] != "VALID_ALLOCATION":
            lines.append("| " + fmt(row["budget_flops"]) + " | " + str(row["context_tokens"])
                         + " | — | — | — | — | `INFEASIBLE_BELOW_C_MIN` | — | — | — | — |")
            continue
        cost = row["cost"]
        lines.append(
            "| " + fmt(row["budget_flops"]) + " | " + str(row["context_tokens"])
            + " | " + fmt(row["kappa_flops_per_parameter_token"])
            + " | " + fmt(row["n_parameters_raw"]) + " | " + fmt(row["d_tokens_raw"])
            + " | " + fmt(row["predicted_loss"]) + " | `" + row["regime"] + "`"
            + " | " + unused_text(row) + " | " + fmt(cost["compute_utilization"])
            + " | " + fmt(cost["base_share_of_spent"]) + " | " + fmt(cost["attention_share_of_spent"]) + " |"
        )
    lines += [
        "",
        "## Regime changes bracketed by observed contexts",
        "",
    ]
    if bracket_rows:
        lines += [
            "| Budget C (FLOPs) | Between observed L_ctx | Regime below | Regime above |",
            "| ---: | --- | --- | --- |",
        ]
        for item in bracket_rows:
            lines.append("| " + fmt(item["budget_flops"]) + " | " + str(item["lower_observed_context_tokens"])
                         + " and " + str(item["upper_observed_context_tokens"]) + " | `" + item["regime_at_lower"]
                         + "` | `" + item["regime_at_upper"] + "` |")
        lines += [
            "",
            "A larger context raises `kappa`, which lowers the effective budget `C/kappa`; at a fixed budget it",
            "can therefore move the optimum off the `D_max` bound. These rows only bracket where that happens",
            "on the observed grid. No continuous context threshold is identified, and the grid is not",
            "interpolated or extended to locate one.",
        ]
    else:
        lines.append("At every representative budget, all observed contexts share one regime.")
    lines += [
        "",
        "## Cost-parity identity",
        "",
        "`L_ctx = 6 / eta = " + fmt(parity) + "` tokens is where attention and base training compute are equal",
        "(base share of spent = attention share of spent = 0.5). It is a cost identity only: not an optimum,",
        "not a phase or regime transition, and not a critical context found by the optimizer. It is not an",
        "observed C7 value; the observed rows at 8192 and 32768 tokens lie on either side of it.",
        "",
        "Within one context the base and attention shares of spent compute are `6/kappa` and",
        "`eta L_ctx/kappa` at every budget, so budget changes never move the base/attention split.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    install_q3_input_guard()
    load_all_accepted_interfaces()
    classic = load_classic_if3()
    receipt = load_source_receipt()
    rows = [solve_record(classic, receipt, budget, context)
            for budget in receipt.budgets_flops for context in receipt.contexts_tokens]
    bracket_rows = brackets(rows, receipt.budgets_flops)
    payload = {
        "schema_version": "q3-context-sensitivity-v3",
        "purpose": "T-010 full observed-context baseline sensitivity under C_total <= C; no context optimization",
        "receipt_path": "results/tables/q3-source-receipt.json",
        "classic_if3_sha256": classic.sha256,
        "claim_level": "model-conditional; not direct observation",
        "quality_coordinate": "Q0",
        "cross_scale_quality_benefit": "PROHIBITED",
        "context_role": "exogenous observed C7 sensitivity axis; not optimized; not interpolated or extended",
        "parity_tokens": receipt.parity_tokens,
        "parity_role": "base/attention cost-parity identity only",
        "rows": rows,
        "observed_context_brackets": bracket_rows,
    }
    write_artifacts("q3-context-sensitivity", payload, markdown(rows, bracket_rows, receipt.parity_tokens))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
