"""Generate full observed-C7 baseline context sensitivity allocations.

Writes every receipt-supported budget/context combination. Context is an
exogenous observed sensitivity axis, never an interior optimization variable.

Run through the declared environment:
    conda run -n modeling-research-2026 --no-capture-output python scripts/q3_context_sensitivity.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Mapping

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from src.alloc import (  # noqa: E402
    BaselineCompute,
    NoValidityBoxAllocation,
    load_classic_if3,
    load_source_receipt,
    solve_baseline,
)
from src.paths import TABLES, ensure  # noqa: E402


def fmt(value: float, digits: int = 8) -> str:
    return format(float(value), "." + str(digits) + "g")


def record(result) -> dict[str, object]:
    return {
        "status": "VALID_ALLOCATION",
        "budget_flops": result.compute.budget_flops,
        "context_tokens": result.compute.context_tokens,
        "kappa_flops_per_parameter_token": result.compute.kappa,
        "n_parameters_raw": result.n_parameters,
        "d_tokens_raw": result.d_tokens,
        "predicted_loss": result.predicted_loss,
        "feasibility_label": result.feasibility_label,
        "active_boundary": result.active_boundary,
        "cost": dict(result.cost),
    }


def unavailable_record(budget: float, context: int, error: NoValidityBoxAllocation) -> dict[str, object]:
    return {
        "status": "NO_VALIDITY_BOX_ALLOCATION",
        "budget_flops": budget,
        "context_tokens": context,
        "reason": str(error),
    }


def solve_record(classic, receipt, budget: float, context: int) -> dict[str, object]:
    try:
        return record(solve_baseline(classic, BaselineCompute.create(receipt, budget, context)))
    except NoValidityBoxAllocation as exc:
        return unavailable_record(budget, context, exc)


def markdown_table(rows: list[Mapping[str, object]], parity_tokens: float) -> str:
    lines = [
        "# Q3 baseline context sensitivity",
        "",
        "Generated by `scripts/q3_context_sensitivity.py`. Do not edit by hand.",
        "",
        "Every row uses a source-supported compute budget and the full observed C7 context",
        "grid. `L_ctx` is an exogenous sensitivity axis, not an optimized or preferred context",
        "choice. All allocations are at semantic baseline `Q0`, with exactly zero quality compute.",
        "",
        "| Budget (FLOPs) | L_ctx (tokens) | kappa | N (raw parameters) | D (raw tokens) | Predicted loss | Feasibility | Active boundary | Base share | Attention share | Quality share |",
        "| ---: | ---: | ---: | ---: | ---: | ---: | --- | --- | ---: | ---: | ---: |",
    ]
    for row in rows:
        if row["status"] != "VALID_ALLOCATION":
            lines.append(
                "| " + fmt(row["budget_flops"]) + " | " + str(row["context_tokens"])
                + " | — | — | — | — | unavailable | `NO_VALIDITY_BOX_ALLOCATION`"
                + " | — | — | — |"
            )
            continue
        cost = row["cost"]
        assert isinstance(cost, Mapping)
        lines.append(
            "| " + fmt(row["budget_flops"]) + " | " + str(row["context_tokens"])
            + " | " + fmt(row["kappa_flops_per_parameter_token"])
            + " | " + fmt(row["n_parameters_raw"])
            + " | " + fmt(row["d_tokens_raw"])
            + " | " + fmt(row["predicted_loss"])
            + " | " + str(row["feasibility_label"])
            + " | `" + str(row["active_boundary"]) + "`"
            + " | " + fmt(cost["base_share"])
            + " | " + fmt(cost["attention_share"])
            + " | " + fmt(cost["quality_share"]) + " |"
        )
    boundaries = {
        (row["budget_flops"], row["active_boundary"])
        for row in rows
        if row["status"] == "VALID_ALLOCATION"
    }
    unavailable = [row for row in rows if row["status"] != "VALID_ALLOCATION"]
    lines += [
        "",
        "## Cost-parity identity",
        "",
        "`L_ctx = " + fmt(parity_tokens) + "` tokens equals `6 / eta`, so base and attention",
        "compute shares are equal there. This is a cost-parity identity only, not an empirical",
        "optimum, phase transition, critical context length, or optimizer-regime transition.",
        "",
        "## Validity-boundary classification",
        "",
        "The observed grid produces these `(budget, active boundary)` classifications: `"
        + ", ".join("(" + fmt(budget) + ", " + str(boundary) + ")"
                    for budget, boundary in sorted(boundaries)) + "`.",
        "",
        "Any boundary change reported above is a validity-box classification at observed inputs,",
        "not a context optimum or a claimed transition.",
        "",
        "The `NO_VALIDITY_BOX_ALLOCATION` rows are explicitly unavailable: no point can",
        "simultaneously saturate that receipt-supported budget and remain inside the accepted",
        "raw N/D IF3 validity box. They are not silently clipped or extrapolated.",
        "",
        "No numerical nonbaseline quality scenario ran. Cross-scale quality benefit is prohibited",
        "because accepted classic IF3 has no quality-loss term.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    classic = load_classic_if3()
    receipt = load_source_receipt()
    rows = [
        solve_record(classic, receipt, budget, context)
        for budget in receipt.budgets_flops
        for context in receipt.contexts_tokens
    ]
    payload = {
        "schema_version": "q3-context-sensitivity-v1",
        "purpose": "T-010 full observed-context baseline sensitivity; no context optimization",
        "receipt_path": "results/tables/q3-source-receipt.json",
        "classic_if3_sha256": classic.sha256,
        "quality_coordinate": "Q0",
        "quality_preprocessing_flops": 0.0,
        "parity_tokens": receipt.parity_tokens,
        "parity_role": "base/attention cost-parity identity only",
        "context_role": "full observed C7 sensitivity grid; not an optimized context choice",
        "rows": rows,
    }
    out_dir = ensure(TABLES)
    json_path = out_dir / "q3-context-sensitivity.json"
    markdown_path = out_dir / "q3-context-sensitivity.md"
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    markdown_path.write_text(markdown_table(rows, receipt.parity_tokens), encoding="utf-8", newline="\n")
    print("wrote " + json_path.relative_to(REPO).as_posix())
    print("wrote " + markdown_path.relative_to(REPO).as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
