"""Generate the receipt-gated Q3 quality-cost status report.

No numerical nonbaseline quality scenario is evaluated because the source receipt
establishes Q0 semantically but supplies no global numeric Q0.

Run through the declared environment:
    conda run -n modeling-research-2026 --no-capture-output python scripts/q3_quality_cost_sensitivity.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Mapping

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from src.alloc import load_source_receipt  # noqa: E402
from src.paths import TABLES, ensure  # noqa: E402


def terms_by_name(payload: Mapping[str, Any]) -> Mapping[str, Mapping[str, Any]]:
    terms = payload.get("terms")
    if not isinstance(terms, list):
        raise RuntimeError("validated source receipt lacks a term list")
    output: dict[str, Mapping[str, Any]] = {}
    for term in terms:
        if isinstance(term, dict) and isinstance(term.get("name"), str):
            output[term["name"]] = term
    return output


def markdown_report(payload: Mapping[str, Any]) -> str:
    terms = terms_by_name(payload)
    baseline = terms["quality_baseline_Q0"]
    families = terms["quality_cost_families"]
    baseline_support = baseline["supported_value_or_grid"]
    family_support = families["supported_value_or_grid"]
    assert isinstance(baseline_support, Mapping)
    assert isinstance(family_support, Mapping)
    lines = [
        "# Q3 quality-cost sensitivity status",
        "",
        "Generated by `scripts/q3_quality_cost_sensitivity.py`. Do not edit by hand.",
        "",
        "## Gate disposition",
        "",
        "**BLOCKED_UNTIL_Q0_DECLARED.** The frozen source receipt establishes `Q0` as",
        "the semantic baseline in `C_Q = D [g(Q) - g(Q0)]_+`, but its global numeric",
        "value is `null`. No numerical nonbaseline quality-cost scenario or quality",
        "optimization ran.",
        "",
        "At the semantic baseline only, `Q = Q0` and therefore `delta_g(Q0) =",
        "[g(Q0) - g(Q0)]_+ = 0` exactly. Baseline quality preprocessing compute is",
        "exactly zero; this identity needs no numeric global `Q0`.",
        "",
        "## Source-specified quality-cost families",
        "",
        "| Family | Formula | gamma | lambda | Status |",
        "| --- | --- | ---: | ---: | --- |",
    ]
    for name, family in family_support.items():
        assert isinstance(family, Mapping)
        lines.append(
            "| `" + str(name) + "` | `" + str(family["formula"]) + "` | "
            + str(family["gamma"]) + " | " + str(family["lambda"])
            + " | Not numerically evaluated |"
        )
    lines += [
        "",
        "## Required limitation",
        "",
        "The receipt lists `Q0` source options as `"
        + "`; `".join(str(option) for option in baseline_support["source_options"])
        + "`, but does not select or establish a global scalar. IF1 is not substituted",
        "for `Q0`: it is a partial relative proxy, and unmapped mixture mass is not imputed.",
        "",
        "**PROHIBITED:** Cross-scale quality-benefit modeling. The accepted classic IF3",
        "law contains no quality-loss term; the specified `g(Q)` families are cost",
        "expressions, not an accepted loss-benefit model.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    receipt = load_source_receipt()
    payload = receipt.payload
    gates = payload["gates"]
    assert isinstance(gates, Mapping)
    status = {
        "schema_version": "q3-quality-cost-sensitivity-v1",
        "purpose": "T-010 blocked nonbaseline quality-cost status report; no numeric scenario",
        "receipt_path": "results/tables/q3-source-receipt.json",
        "quality_baseline_gate": gates["nonbaseline_quality_cost_scenarios"],
        "cross_scale_quality_benefit_gate": gates["cross_scale_quality_benefit"],
        "baseline_identity": {
            "quality_coordinate": "Q0",
            "delta_g_flops_per_token": 0.0,
            "quality_preprocessing_flops": 0.0,
            "identity": "[g(Q0) - g(Q0)]_+ = 0",
        },
        "numeric_nonbaseline_scenarios_ran": False,
        "quality_optimization_ran": False,
        "quality_cost_families": terms_by_name(payload)["quality_cost_families"]["supported_value_or_grid"],
        "limitation": terms_by_name(payload)["quality_baseline_Q0"]["limitation"],
    }
    out_dir = ensure(TABLES)
    json_path = out_dir / "q3-quality-cost-sensitivity.json"
    markdown_path = out_dir / "q3-quality-cost-sensitivity.md"
    json_path.write_text(json.dumps(status, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    markdown_path.write_text(markdown_report(payload), encoding="utf-8", newline="\n")
    print("wrote " + json_path.relative_to(REPO).as_posix())
    print("wrote " + markdown_path.relative_to(REPO).as_posix())
    print("nonbaseline quality-cost scenarios: " + str(gates["nonbaseline_quality_cost_scenarios"]["result"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
