"""Generate the raw quality-cost family comparison and the quality-lane status.

Uses only the source-verified g(Q) coefficients and Q domain from the Q3 receipt.
Three questions stay separate: (A) the raw g(Q) comparison, done here without any
Q0; (B) nonbaseline D [g(Q) - g(Q0)]_+ allocation, BLOCKED_UNTIL_Q0_DECLARED;
(C) nontrivial Q optimization, unsupported because classic IF3 has no quality term.

Run through the declared environment:
    conda run -n modeling-research-2026 --no-capture-output python scripts/q3_quality_cost_sensitivity.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Mapping

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from src.alloc import (  # noqa: E402
    install_q3_input_guard,
    load_all_accepted_interfaces,
    load_source_receipt,
    raw_family_analysis,
)
from src.alloc.report import fmt, write_artifacts  # noqa: E402

NAMES = {
    "exponential": "exponential gamma e^(lambda Q)",
    "power": "power gamma Q^lambda",
    "logarithmic": "logarithmic-asymptotic gamma ln(1 + lambda Q)",
}


def markdown(payload: Mapping[str, Any]) -> str:
    analysis = payload["raw_family_analysis"]
    lines = [
        "# Q3 quality-cost families",
        "",
        "Generated by `scripts/q3_quality_cost_sensitivity.py`. Do not edit by hand.",
        "",
        "## Three separate questions",
        "",
        "| Question | Status |",
        "| --- | --- |",
        "| A. Compare the raw organizer functions `g(Q)` on the source domain | **DONE** below; needs no `Q0` |",
        "| B. Evaluate nonbaseline `C_Q = D [g(Q) - g(Q0)]_+` in an allocation | **" + payload["nonbaseline_gate"]["result"]
        + "**: the source defines `Q0` semantically but gives no global numeric value |",
        "| C. Optimize a nontrivial `Q` | **UNSUPPORTED**: classic IF3 has no quality term, so the accepted model identifies no benefit to buy |",
        "",
        "At the canonical baseline `Q = Q0`, `[g(Q0) - g(Q0)]_+ = 0` exactly for every family, so quality",
        "compute is zero in every allocation. Under the accepted law, spending compute on `Q > Q0` would",
        "only reduce the budget left for N and D; this is a consequence of the model having no quality",
        "benefit term, not a statement that data quality is unimportant in reality.",
        "",
        "## Source-verified families",
        "",
        "| Family | gamma (FLOPs per token) | lambda | Limit as Q -> 0+ | g(1) (FLOPs per token) |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for name, family in analysis["families"].items():
        lines.append("| " + NAMES[name] + " | " + fmt(family["gamma_flops_per_token"]) + " | "
                     + fmt(family["lambda"]) + " | " + fmt(family["limit_q_to_0_plus_flops_per_token"])
                     + " | " + fmt(family["value_at_q_1_flops_per_token"]) + " |")
    lines += [
        "",
        "Domain `Q in (0, 1]` (verified at `w:body/w:p[31]`); `Q = 0` is not admissible and is never",
        "evaluated, so the `Q -> 0+` column is an analytic limit, not a row. All three families are",
        "strictly increasing on the domain.",
        "",
        "## Pairwise crossings",
        "",
        "| Pair | Shape of ln g_i - ln g_j | Crossings on (0, 1] | Q at crossing | g at crossing (FLOPs per token) | Relative residual |",
        "| --- | --- | ---: | ---: | ---: | ---: |",
    ]
    for pair in analysis["pairs"]:
        crossings = pair["crossings"]
        lines.append(
            "| " + pair["pair"][0] + " vs " + pair["pair"][1] + " | " + pair["log_difference_shape"]
            + (" (stationary at Q = " + fmt(pair["interior_stationary_q"], 6) + ")" if pair["interior_stationary_q"] else "")
            + " | " + str(pair["crossing_count"]) + " | "
            + "; ".join(fmt(item["q"], 10) for item in crossings) + " | "
            + "; ".join(fmt(item["g_value_flops_per_token"], 6) for item in crossings) + " | "
            + "; ".join(format(item["relative_residual"], ".1e") for item in crossings) + " |"
        )
    lines += [
        "",
        "The crossing counts are exact: `ln g_i - ln g_j` is strictly convex (exponential vs power,",
        "exponential vs logarithmic) or strictly increasing (power vs logarithmic) on `(0, 1]`, so the",
        "domain splits into at most two strictly monotone pieces with at most one root each, and a root",
        "exists exactly where the sign differs at the ends of a piece (the `Q -> 0+` end by its analytic",
        "limit). A near-endpoint crossing therefore cannot be missed. Roots are refined by Brent's method",
        "on sign-checked brackets. A geometric grid screen of "
        + str(analysis["grid_screen_cross_check"]["points"]) + " points agrees: "
        + ", ".join(key.replace("_", " ") + " " + str(value) for key, value
                    in analysis["grid_screen_cross_check"]["sign_changes"].items()) + ".",
        "",
        "## Ordering by raw g(Q)",
        "",
        "| Q interval | Ascending raw g(Q) |",
        "| --- | --- |",
    ]
    for item in analysis["interval_ordering"]:
        lines.append("| `" + "(" + fmt(item["interval"][0], 10) + ", " + fmt(item["interval"][1], 10)
                     + ("]" if item["interval"][1] == 1.0 else ")") + "` | "
                     + " < ".join(item["ascending_by_raw_g"]) + " |")
    lines += [
        "",
        "No ordering among the families holds over the whole domain; every claim above is restricted to",
        "the stated interval. The comparison uses the organizer coefficients exactly, with no",
        "normalization, calibration, outcome tuning or chosen `Q0`, and a raw-`g` ordering says nothing",
        "about the ordering of `delta_g(Q;Q0) = [g(Q) - g(Q0)]_+`, which depends on each family's",
        "increment between `Q0` and `Q`. The families are cost expressions, not a loss-benefit model.",
        "",
        "## Q0 and IF1",
        "",
        "The source allows `Q0` from Attachment A quality scores or a reasonable assumption, but no global",
        "numeric value is established. IF1 is a partial-coverage relative domain proxy ("
        + str(payload["if1_identity"]["unmapped_mixture_domains"]) + " of "
        + str(payload["if1_identity"]["mixture_domains"]) + " mixture",
        "domains unmapped, coverage " + fmt(payload["if1_identity"]["coverage_fraction"], 4)
        + "); it is not substituted for `Q0`, and no unmapped mass is imputed.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    install_q3_input_guard()
    if1 = load_all_accepted_interfaces()["IF1"]
    receipt = load_source_receipt()
    gates = receipt.payload["gates"]
    analysis = raw_family_analysis(receipt.quality_families, receipt.quality_domain)
    screen = analysis["grid_screen_cross_check"]["sign_changes"]
    exact = {pair["pair"][0] + "_vs_" + pair["pair"][1]: pair["crossing_count"] for pair in analysis["pairs"]}
    if screen != exact:
        raise RuntimeError("grid screen disagrees with the analytic crossing counts: " + repr((screen, exact)))
    payload = {
        "schema_version": "q3-quality-cost-sensitivity-v3",
        "purpose": "T-010 raw g(Q) family comparison and quality-lane status",
        "receipt_path": "results/tables/q3-source-receipt.json",
        "claim_level": "sensitivity analysis of organizer cost expressions; not a loss-benefit model",
        "raw_g_comparison": "DONE",
        "nonbaseline_gate": gates["nonbaseline_quality_cost_scenarios"],
        "quality_optimization": "UNSUPPORTED: classic IF3 has no quality term",
        "cross_scale_quality_benefit_gate": gates["cross_scale_quality_benefit"],
        "baseline_identity": {"quality_coordinate": "Q0", "delta_g_flops_per_token": 0.0,
                              "identity": "[g(Q0) - g(Q0)]_+ = 0 for every family"},
        "numeric_nonbaseline_scenarios_ran": False,
        "quality_optimization_ran": False,
        "if1_identity": dict(if1.scope),
        "raw_family_analysis": analysis,
    }
    write_artifacts("q3-quality-cost-sensitivity", payload, markdown(payload))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
