"""T-011: Q4 population, loss/benchmark bridge (IF4), decomposition and frontier forecast.

Writes, all regenerable and LF-only:

* ``results/tables/q4-evolution-population.md`` - receipts, score scale, population, time convention, C3 audit;
* ``results/tables/q4-bridge.md``                - anchors, strata, bridge forms, validation, IF4 release;
* ``results/tables/q4-decomposition.md``         - scale / non-scale decompositions, compute-aware subset;
* ``results/tables/q4-frontier-forecast.md``     - frontier, 12-month forecast, 24-month stress, uncertainty;
* ``results/tables/q4-forecast-robustness.md``   - the declared sensitivity matrix;
* ``data_local/problem-f/interfaces/q4-if4-loss-benchmark-bridge.json`` (local-only IF4).

Run:
    conda run -n modeling-research-2026 --no-capture-output python scripts/q4_evolution_run.py
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Dict, List

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from src import interfaces as ifc  # noqa: E402
from src.evolution import auxiliary, bridge, compute, dynamics, population, receipts, scores  # noqa: E402
from src.evolution.config import (  # noqa: E402
    BOOTSTRAP_REPLICATES, BRIDGE_FORMS, BRIDGE_PRIMARY_STRATUM, BRIDGE_STRATA, DATE_CONSISTENCY_TOLERANCE_DAYS,
    EXCLUDED_STRATA, FRONTIER_QUANTILE, GROUP_LABELS, GROUPS, IF4_FILENAME, INTERVAL,
    MIN_BAND_N, MIN_BIN_N, MIN_FRONTIER_SET_N, MIN_ORIGINS, MIN_TRAIN_BINS, PRIMARY_SCENARIO,
    SCENARIOS, SEED, TOP_K,
)
from src.evolution.estimators import interval  # noqa: E402
from src.panel.sources import load_c1  # noqa: E402
from src.paths import PROBLEM_F_INTERFACES, TABLES, ensure  # noqa: E402

GEN = "Generated by `scripts/q4_evolution_run.py`. Do not edit by hand."
SCORE_DIMS = list(scores.DIMENSIONS)


# ---------------------------------------------------------------------------
# Formatting
# ---------------------------------------------------------------------------

def f(x, d: int = 2) -> str:
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "n/a"
    return f"{x:.{d}f}"


def g(x, d: int = 4) -> str:
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "n/a"
    return f"{x:.{d}g}"


def pct(x, d: int = 1) -> str:
    return "n/a" if not np.isfinite(x) else f"{100 * x:.{d}f}%"


def ci(values, d: int = 2) -> str:
    lo, hi = interval(values, *INTERVAL)
    return f"[{f(lo, d)}, {f(hi, d)}]"


def n(x) -> str:
    return f"{int(x):,}"


def date(ts) -> str:
    return pd.Timestamp(ts).strftime("%Y-%m-%d")


def write(name: str, lines: List[str]) -> Path:
    path = ensure(TABLES) / name
    text = "\n".join(lines).rstrip("\n") + "\n"
    if "\r" in text:
        raise ValueError("generated text contains a carriage return")
    trailing = [i + 1 for i, line in enumerate(text.split("\n")) if line != line.rstrip()]
    if trailing:
        raise ValueError(name + " has trailing whitespace on line(s) " + repr(trailing[:5]))
    path.write_text(text, encoding="utf-8", newline="\n")
    return path


CI_LABEL = f"{round(100 * (INTERVAL[1] - INTERVAL[0]))}% month-block bootstrap interval ({BOOTSTRAP_REPLICATES} replicates)"


def share_cell(point: float, draws, total_draws) -> str:
    """A share is shown only when the total trend's interval excludes zero; otherwise it has no meaning."""
    lo, _ = interval(total_draws, *INTERVAL)
    if not (np.isfinite(lo) and lo > 0):
        return "n/a (total trend interval includes 0)"
    return f"{pct(point)} {ci(100 * np.asarray(draws, float), 0)}%"


# ---------------------------------------------------------------------------
# Computation
# ---------------------------------------------------------------------------

def compute_all() -> Dict[str, object]:
    print(f"seed {SEED}")
    out: Dict[str, object] = {}
    out["sources"] = receipts.verify_sources()
    out["if3"] = receipts.load_if3()
    panel = receipts.load_panel()
    out["panel"] = panel
    out["panel_facts"] = receipts.check_panel(panel)
    out["panel_fp"] = receipts.panel_fingerprint(panel)
    out["score_audit"] = scores.audit(panel)
    scores.macro_score(panel, audit_table=out["score_audit"])
    pop = population.build(panel)
    dynamics.check_anchor(pop.frame, pop.anchor)
    out["pop"] = pop
    out["alternatives"] = {name: population.build(panel, name, **kw) for name, kw in population.ALTERNATIVES.items()}
    out["c3"] = auxiliary.audit(panel)

    # Bridge
    c5, c6 = bridge.load_tables()
    rows = bridge.stratify(c5, c6)
    anchors = bridge.match_anchors(rows, panel, load_c1())
    anchors["loss_reuse"] = False
    in_c5 = anchors["in_c5"]
    anchors.loc[in_c5, "loss_reuse"] = bridge.loss_reuse(anchors.loc[in_c5]).to_numpy()
    c5_keys = set((anchors.loc[in_c5, "Val_Loss"].astype(str) + "|" + anchors.loc[in_c5, "N_params_B"].astype(str)))
    s3 = ~in_c5
    s3_key = anchors.loc[s3, "Val_Loss"].astype(str) + "|" + anchors.loc[s3, "N_params_B"].astype(str)
    anchors.loc[s3, "loss_reuse"] = (s3_key.isin(c5_keys) | s3_key.duplicated(keep=False)).to_numpy()
    out["anchors"] = anchors
    out["fingerprint"] = bridge.s1_fingerprint(anchors, out["if3"])
    primary = anchors[(anchors["stratum"] == BRIDGE_PRIMARY_STRATUM) & (anchors["score_record"] == "panel_match")]
    if len(primary) != int((anchors["stratum"] == BRIDGE_PRIMARY_STRATUM).sum()):
        raise bridge.BridgeError("a primary-stratum anchor lacks a clean accepted score record")
    loss = primary["Val_Loss"].to_numpy(float)
    score = primary["panel_macro"].to_numpy(float)
    results = [bridge.leave_one_out(form, loss, score) for form in BRIDGE_FORMS]
    chosen, selection = bridge.select(results)
    out["bridge_results"], out["bridge_chosen"], out["bridge_selection"] = results, chosen, selection
    out["bridge_primary"] = primary
    s2 = anchors[anchors["stratum"] == "S2_cross_family_literature"]
    out["s2_block"] = {form: bridge.leave_one_org_out(form, s2) for form in ("constant", "linear")}
    out["s2"] = s2
    strata_counts = {k: int((anchors["stratum"] == k).sum()) for k in BRIDGE_STRATA}
    fp = out["fingerprint"]
    notes = (
        "PRIMARY STRATUM ONLY: fitted on the " + str(len(primary)) + " organizer-labelled High anchors (Pythia, "
        "same model and validation set); the Medium literature rows and the expanded C6 variant rows are carried "
        "as counts and never pooled. LOSS AXIS: the anchor losses equal the published Chinchilla law evaluated at "
        "their own (N, D) to a maximum absolute difference of " + g(float(np.max(np.abs(fp['val_loss'] - fp['published_law']))), 3)
        + ", the B1 numerical fingerprint T-008 recorded, so this axis is the Attachment-B / classic-IF3 loss scale "
        "and not an independently measured validation loss. SCORE: the anchors' macro scores lie between "
        + f(float(score.min())) + " and " + f(float(score.max())) + " on a 0-100 scale, at the floor of the "
        "benchmark. FORM: chosen by the predeclared leave-one-anchor-out rule; out-of-fold error is in "
        "prediction_error. SUPPORT: only losses within [loss_support_min, loss_support_max] may be translated; "
        "no loss-to-score slope is identified there when the chosen form is constant, and nothing may be "
        "extrapolated beyond it. Any bridge-based score must carry predictive_sd. Classic-IF3 caveat: the B1 fit "
        "supports estimator / generator recovery, not precise real-world scaling. Built by T-011; see "
        "results/tables/q4-bridge.md."
    )
    if4 = bridge.build_if4(chosen, primary, strata_counts, notes)
    path = ifc.save(if4, ensure(PROBLEM_F_INTERFACES) / IF4_FILENAME)
    out["if4_path"] = path
    out["if4_sha"] = hashlib.sha256(path.read_bytes()).hexdigest()
    out["if4_payload"] = json.loads(path.read_text(encoding="utf-8"))

    # Compute-aware subset
    csub = compute.infer_nd(compute.subset(panel, pop.anchor, set(pop.frame["model"])), out["if3"])
    out["compute_subset"] = csub
    a_only = csub[csub["stratum"] == "A"]
    out["log_compute_A"] = compute.log_compute(a_only, "log_compute:A")
    out["log_compute_all"] = compute.log_compute(csub, "log_compute:all")
    inside = csub[csub["inside_if3_box"]]
    out["if3_primary"] = compute.if3_primary(inside, out["if3"])
    out["if3_extrap"] = compute.if3_extrapolation(csub)
    out["compute_sizes"] = compute.sizes(panel, csub, len(csub))
    for key in ("log_compute_A", "log_compute_all"):
        out[key]["sizes"] = compute.sizes(panel, csub, out[key]["n"])
        compute.require_sizes(out[key])

    # Bridge-based pathway inside its support
    if4p = out["if4_payload"]
    lo, hi = if4p["params"]["loss_support_min"], if4p["params"]["loss_support_max"]
    anchors_set = set(primary["Model"])
    check = inside[~inside["model"].isin(anchors_set)].copy()
    check = check[(check["if3_loss"] >= lo) & (check["if3_loss"] <= hi)]
    payload = json.loads(receipts.read_input(receipts.IF3_FILE).read_text(encoding="utf-8"))
    ext_rel = float(payload["validation"]["B4_cross_family_excl_pythia"]["median_abs_rel_err"])
    loss_sd_ext = check["if3_loss"].to_numpy(float) * ext_rel * 1.4826
    if len(check):
        mean_b, sd_b = bridge.bridge_predict(if4p, check["if3_loss"].to_numpy(float), loss_sd_ext)
        check["bridge_mean"], check["bridge_sd"] = mean_b, sd_b
    out["bridge_check"] = check
    out["if3_ext_rel"] = ext_rel

    # Frontier, decomposition, forecast
    out["groups"] = {}
    for name in GROUPS:
        frame = pop.frame[pop.frame["group"] == name]
        comp, boot, bins, fc, framed = dynamics.forecast_table(frame, pop.anchor, "forecast:" + name)
        h, ro, feasible = dynamics.rolling_origin(framed, pop.anchor)
        out["groups"][name] = {
            "frame": framed, "comp": comp, "boot": boot, "bins": bins, "forecast": fc,
            "backtest_h": h, "backtest": ro, "feasible": feasible,
            "matched": dynamics.matched_scale(framed),
            "specs": {s: dynamics.scale_spec_residual(framed, s) for s in
                      ("linear_log10N", "quadratic_log10N", "scale_band_fixed_effects")},
            "dims": dimension_table(framed),
        }
        print(f"  group {name}: n={len(frame)} frontier trend {comp['g_time']:.3f}/yr")

    out["robust"] = robustness(out)
    return out


def dimension_table(frame: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for col, label in scores.DIMENSIONS.items():
        q = dynamics.quantile_split(frame, col)
        m = dynamics.exact_split(frame, col)
        rows.append({"dimension": label, "frontier_level": q["level0"], "frontier_trend": q["g_time"],
                     "mean_trend": m["g_time"], "mean_scale_rate": m["scale_rate"], "mean_resid_rate": m["resid_rate"]})
    return pd.DataFrame(rows)


def robustness(out: Dict[str, object]) -> Dict[str, pd.DataFrame]:
    rows = []
    for name, alt in out["alternatives"].items():
        for grp in GROUPS:
            frame = alt.frame[alt.frame["group"] == grp].copy()
            if len(frame) < MIN_FRONTIER_SET_N:
                rows.append({"population": name, "group": grp, "n": len(frame), "anchor": alt.anchor})
                continue
            frame["frontier_set"] = dynamics.frontier_flags(frame)
            comp = dynamics.components(frame)
            h12 = dynamics.years_between(dynamics.horizon_dates(alt.anchor)["primary_12m"], alt.anchor)
            rows.append({"population": name, "group": grp, "n": len(frame), "anchor": alt.anchor,
                         "level0": comp["level0"], "g_time": comp["g_time"],
                         "mean_scale_rate": comp["mean_scale_rate"], "mean_resid_rate": comp["mean_resid_rate"],
                         "fs_scale_rate": comp["frontier_scale_rate"], "fs_resid_rate": comp["frontier_resid_rate"],
                         "q_consistent": comp["q_consistent"],
                         "f12": dynamics.project(comp, h12, SCENARIOS[PRIMARY_SCENARIO])})
    pop_rows = pd.DataFrame(rows)

    strata_rows = []
    pop = out["pop"]
    for stratum in ("B", "C"):
        frame = pop.frame[pop.frame["stratum"] == stratum].copy()
        frame["frontier_set"] = dynamics.frontier_flags(frame)
        comp = dynamics.components(frame)
        h12 = dynamics.years_between(dynamics.horizon_dates(pop.anchor)["primary_12m"], pop.anchor)
        strata_rows.append({"stratum": stratum, "n": len(frame), "level0": comp["level0"], "g_time": comp["g_time"],
                            "mean_scale_rate": comp["mean_scale_rate"], "mean_resid_rate": comp["mean_resid_rate"],
                            "fs_scale_rate": comp["frontier_scale_rate"], "fs_resid_rate": comp["frontier_resid_rate"],
                            "f12": dynamics.project(comp, h12, SCENARIOS[PRIMARY_SCENARIO])})

    est_rows = []
    for grp, res in out["groups"].items():
        dense = res["bins"][~res["bins"]["sparse"]]
        row = {"group": grp, "dense_bins": len(dense), "quantile_regression": res["comp"]["g_time"]}
        for col in ("p90", "max", "top_k_mean"):
            row[col] = (float(np.polyfit(dense["t_mid"], dense[col], 1)[0]) if len(dense) >= 3 else float("nan"))
        est_rows.append(row)
    return {"population": pop_rows, "strata": pd.DataFrame(strata_rows), "estimators": pd.DataFrame(est_rows)}


# ---------------------------------------------------------------------------
# Rendering: population
# ---------------------------------------------------------------------------

def render_population(o: Dict[str, object]) -> Path:
    if3: receipts.IF3Receipt = o["if3"]
    pop: population.Population = o["pop"]
    panel: pd.DataFrame = o["panel"]
    facts = o["panel_facts"]
    audit = o["score_audit"]
    fr = pop.frame
    L = ["# Q4 evolution: receipts, population and time convention", "", GEN, "",
         "Everything below was fixed from provenance, comparability, completeness, model type and date",
         "availability before any outcome or time model was fitted.", "",
         "## Receipts", "",
         "| Input | Check | Result |", "| --- | --- | --- |",
         f"| classic IF3 `data_local/problem-f/interfaces/IF3_classic.json` | SHA-256 against the tracked T-008 closure table | `{if3.sha256}` - match |",
         "| classic IF3 | `IF3ScalingLaw.validate()`; classic five parameters only; bootstrap unit `model` | PASS |",
         f"| classic IF3 | external units | N raw parameter count, D raw token count (box lower bounds {g(if3.box['N'][0])} and {g(if3.box['D'][0])}) |",
         f"| classic IF3 | validity box | N {g(if3.box['N'][0])} - {g(if3.box['N'][1])}; D {g(if3.box['D'][0])} - {g(if3.box['D'][1])} |",
         "| classic IF3 | Q interval | [1, 1] = no-quality sentinel; no Q argument exists in the T-011 evaluator |",
         f"| T-009 panel | rebuilt through `src.panel.panel.build_panel` | {n(facts['rows'])} rows x {facts['columns']} columns, unique by model |",
         f"| T-009 panel | agreement with the accepted T-009 tables | rows, columns, C4-linked {facts['c4_linked']}, training compute {facts['training_compute']}, dates {n(facts['primary_dates'])} / {n(facts['fallback_dates'])} / {facts['no_date']}: all match |",
         f"| T-009 panel | LF-serialised fingerprint | `{o['panel_fp']}` |",
         ]
    for s in o["sources"]:
        L.append(f"| {s['key']} `{s['path'].split('/')[-1]}` | SHA-256 against the intake manifest | `{s['sha256'][:16]}...` - {'match' if s['match'] else 'MISMATCH'} |")
    L += ["", "The intake manifest itself hashes to the value its intake receipt records. T-011 reads local",
          "inputs only through an allowlist; IF1, IF2, Attachment B (which holds B8) and the C8 per-task",
          "records are not on it.", "",
          "## Score scale and aggregation", "",
          "| Dimension | Min | Max | T-009 status | Spearman vs other five | Direction | Verified |",
          "| --- | ---: | ---: | --- | ---: | --- | --- |"]
    for _, r in audit.iterrows():
        L.append(f"| {r['dimension']} | {f(r['min'])} | {f(r['max'])} | {r['t009_status']} | {f(r['spearman_vs_other_five'], 3)} | {r['declared_direction']} | {'yes' if r['verified'] else 'NO'} |")
    L += ["",
          f"- C1 aggregate header carries the organizer's up-arrow (higher is better): {audit.attrs['average_header_up_arrow']}",
          f"- C1 `Average` minus the equal-weight mean of the six dimensions, max |delta|: {g(audit.attrs['average_minus_mean6_max_abs'], 3)}",
          "",
          "All six dimensions are on the common baseline-rescaled, higher-is-better 0-100 scale, so the",
          "**macro score** is their equal-weight mean (C1 `Average`). It is a transparent summary, not an",
          "outcome-optimised weighting; dimension-level results are kept in `q4-decomposition.md`. MATH Lvl 5",
          "enters only as its C1 summary value; its C8 child records are not read by T-011.", "",
          "## Primary population", "",
          "| Rule | Criterion | Fails alone | Removed in sequence |", "| --- | --- | ---: | ---: |"]
    for _, r in pop.ledger.iterrows():
        L.append(f"| {r['rule']} | {r['criterion']} | {n(r['fails_alone'])} | {n(r['removed_in_sequence'])} |")
    L += ["", f"Retained: **{n(len(fr))}** of {n(len(panel))} panel models.", "",
          "| Group | Definition | Models | Primary date | Fallback date |", "| --- | --- | ---: | ---: | ---: |"]
    for grp in GROUPS:
        sub = fr[fr["group"] == grp]
        L.append(f"| {grp} | {GROUP_LABELS[grp]} | {n(len(sub))} | {n((sub['date_confidence'] == 'primary').sum())} | {n((sub['date_confidence'] == 'fallback').sum())} |")
    L += ["", "Excluded strata:", ""]
    for code, why in EXCLUDED_STRATA.items():
        L.append(f"- {code}: {why}; sensitivity `with_merges` re-admits D." if code == "D" else f"- {code}: {why}.")
    L += ["", "Pretrained (A) and chat / fine-tuned (B, C) models are analysed separately throughout; no",
          "result pools them into one technology frontier. Open weights require a positive T-009 signal",
          "(permissive licence, Epoch open-weights Yes, or unrestricted accessibility); `unknown` is excluded.", ""]
    # Time convention
    lag = population.date_lag_days(panel)
    both = panel[(panel["date_confidence"] == "primary") & panel["submission_date"].notna()]
    lag_b = lag.loc[both.index]
    sub_dates = pd.to_datetime(panel["submission_date"], errors="coerce")
    pub_dates = pd.to_datetime(panel.loc[panel["date_confidence"] == "primary", "analysis_date"])
    removed = pop.ledger.set_index("rule").loc["R7_date_consistent", "removed_in_sequence"]
    cand = population.build(panel, "tmp", consistency_rule=False).frame
    incons = cand[~population.date_consistent(cand)].copy()
    incons["lag"] = population.date_lag_days(incons)
    L += ["## Time convention", "",
          "The canonical row time is the accepted T-009 `analysis_date`: the Epoch AI publication date where",
          "one exists (C2 `pub_date`, else C4 `c4_pub_date`), otherwise the leaderboard submission date. Each",
          "row keeps its `date_source`; a fallback date is a submission (evaluation) date and is never called",
          "a publication date.", "",
          "| Date source | Meaning | Panel rows | Primary-population rows |", "| --- | --- | ---: | ---: |",
          f"| `pub_date` | Epoch publication date via C2 (organizer fuzzy-matched) | {n((panel['date_source'] == 'pub_date').sum())} | {n((fr['date_source'] == 'pub_date').sum())} |",
          f"| `c4_pub_date` | Epoch publication date via the deterministic T-009 C4 link | {n((panel['date_source'] == 'c4_pub_date').sum())} | {n((fr['date_source'] == 'c4_pub_date').sum())} |",
          f"| `submission_date` | leaderboard submission (fallback proxy) | {n((panel['date_source'] == 'submission_date').sum())} | {n((fr['date_source'] == 'submission_date').sum())} |",
          f"| `none` | no date (excluded by R1) | {n((panel['date_source'] == 'none').sum())} | 0 |",
          "",
          f"- Leaderboard submission dates span {date(sub_dates.min())} to {date(sub_dates.max())}: the dense part of the panel is this window.",
          f"- Publication dates span {date(pub_dates.min())} to {date(pub_dates.max())}, but cover only {n(len(pub_dates))} panel rows.",
          f"- Where both exist ({n(len(lag_b))} rows), submission minus publication: median {f(float(-lag_b.median()), 0)} days, "
          f"IQR {f(float(-lag_b.quantile(0.75)), 0)} to {f(float(-lag_b.quantile(0.25)), 0)} days; {n((lag_b > 0).sum())} publication dates fall after the submission.",
          derivative_date_line(panel),
          f"- Date consistency (R7): a publication date more than {DATE_CONSISTENCY_TOLERANCE_DAYS} days after the row's own submission cannot be that model's release date. "
          f"{n(pop.ledger.set_index('rule').loc['R7_date_consistent', 'fails_alone'])} panel rows fail it; of the rows passing R1-R6, {n(len(incons))} fail it and {n(removed)} are removed:",
          "", "| Model | Stratum | Publication date | Submission date | Days after submission |", "| --- | --- | --- | --- | ---: |"]
    for _, r in incons.sort_values("lag", ascending=False).iterrows():
        L.append(f"| `{r['model']}` | {r['stratum']} | {date(r['analysis_date'])} | {date(r['submission_date'])} | {n(r['lag'])} |")
    L += ["",
          f"**Forecast anchor: {date(pop.anchor)}**, the final observed date of the frozen primary population. The",
          f"latest `analysis_date` anywhere in the panel is {date(pd.to_datetime(panel['analysis_date']).max())}, a date-inconsistent row removed by R7; no",
          "forecast is anchored to the machine date.", "",
          "## Predeclared alternative populations", "",
          "| Alternative | Change | Models | A | BC | Own final date |", "| --- | --- | ---: | ---: | ---: | --- |"]
    change = {"primary": "-", "publication_date_only": "primary-dated rows only", "fallback_date_only": "submission-dated rows only",
              "with_merges": "adds stratum D to group BC", "open_weights_relaxed": "drops R6", "date_inconsistent_kept": "drops R7"}
    for name, alt in o["alternatives"].items():
        fa = alt.frame
        L.append(f"| `{name}` | {change[name]} | {n(len(fa))} | {n((fa['group'] == 'A').sum())} | {n((fa['group'] == 'BC').sum())} | {date(alt.anchor)} |")
    c3 = o["c3"]
    L += ["", "## C3 (auxiliary timeseries) audit", "",
          "C3 is used as an auxiliary source only; none of its rows becomes a panel observation.", "",
          f"- rows: {n(c3['rows'])} = {n(c3['leaderboard_rows'])} Open LLM Leaderboard + {n(c3['historical_rows'])} historical (papers / reports, {c3['historical_years'][0]}-{c3['historical_years'][1]})",
          f"- leaderboard rows whose `Year` equals the panel submission year: {pct(c3['year_equals_submission_year'])} of {n(c3['leaderboard_rows_shared_with_panel'])}",
          f"- rows whose submission and publication years differ ({n(c3['year_equals_sub_year_where_they_differ'] + c3['year_equals_pub_year_where_they_differ'])} with both known and differing): `Year` follows the submission year in {n(c3['year_equals_sub_year_where_they_differ'])}, the publication year in {n(c3['year_equals_pub_year_where_they_differ'])}",
          f"- duplicate model rows (distinct score vectors, per T-009): {n(c3['duplicate_model_rows'])}",
          f"- historical rows that are panel models: {n(c3['historical_models_in_panel'])}",
          f"- historical rows whose `Average` differs from the mean of their six dimensions by more than one point: {n(c3['historical_rows_average_not_mean6'])} of {n(c3['historical_rows'])} (max |delta| {f(c3['historical_average_minus_mean6_max_abs'])})",
          f"- historical rows with at least one dimension recorded as exactly 0: {n(c3['historical_rows_with_zero_filled_dimension'])}",
          "",
          ("C3's `Year` is the leaderboard submission year, not a release year, so C3 adds no independent"
           if c3["year_equals_submission_year"] == 1.0 and c3["year_equals_pub_year_where_they_differ"] == 0 else
           "C3's `Year` does not consistently follow the submission year, so it is not used as a"),
          "release clock.",
          ("Its historical rows are not on the leaderboard v2 scale (their `Average` is not the mean of their"
           if c3["historical_rows_average_not_mean6"] > 0 else "Its historical rows are consistent with the v2 scale"),
          ("dimensions and unmeasured dimensions are zero-filled), so they are not used as frontier observations."
           if c3["historical_rows_average_not_mean6"] > 0 else "but remain auxiliary."),
          ""]
    return write("q4-evolution-population.md", L)


def derivative_date_line(panel: pd.DataFrame) -> str:
    """Evidence that C2 publication dates on derivative models are shared family dates."""
    der = panel[(panel["date_source"] == "pub_date") & panel["stratum"].isin(["C", "D"])]
    counts = der["analysis_date"].value_counts()
    shared = der["analysis_date"].map(counts)
    top = counts.head(3)
    listing = "; ".join(f"{date(d)} x {c} ({der.loc[der['analysis_date'] == d, 'org'].mode().iloc[0]})"
                        for d, c in top.items())
    return (f"- C2's fuzzy-matched publication date on a fine-tune or merge is typically the upstream base family's date: "
            f"the {n(len(der))} C2-dated rows in strata C and D carry only {n(counts.size)} distinct dates, and "
            f"{n((shared >= 10).sum())} of them share their date with at least nine other derivative rows "
            f"(most common: {listing}).")


# ---------------------------------------------------------------------------
# Rendering: bridge
# ---------------------------------------------------------------------------

def render_bridge(o: Dict[str, object]) -> Path:
    a: pd.DataFrame = o["anchors"]
    fp: pd.DataFrame = o["fingerprint"]
    results = o["bridge_results"]
    chosen = o["bridge_chosen"]
    sel = o["bridge_selection"]
    prim: pd.DataFrame = o["bridge_primary"]
    p = o["if4_payload"]
    L = ["# Q4 loss-to-benchmark bridge (IF4)", "", GEN, "",
         "## Anchors", "",
         f"C5 holds {n(a['in_c5'].sum())} rows and the expanded C6 {n(len(a))}; every C5 row is in C6 with identical values,",
         "so the union is C6 with a flag for C5 membership. Anchors link to the T-009 panel by exact model",
         "path, then the T-009 normalised key if unique on both sides, then an explicit (empty) alias map.", "",
         "| Identity tier | Anchors |", "| --- | ---: |"]
    for tier, cnt in a["identity_tier"].value_counts().sort_index().items():
        L.append(f"| {tier} | {n(cnt)} |")
    L += ["", "No two anchors link to one panel model. The benchmark value used is the accepted T-009 panel",
          "score (the first C1 row for the model path).", "",
          "| Stratum | Definition (organizer metadata) | Anchors | Loss kinds | Loss value shared with another model | Evaluated model's T-009 strata | Duplicate C1 evaluations |",
          "| --- | --- | ---: | --- | ---: | --- | ---: |"]
    for code, text in BRIDGE_STRATA.items():
        sub = a[a["stratum"] == code]
        kinds = "; ".join(f"{k} {v}" for k, v in sub["loss_kind"].value_counts().sort_index().items())
        strata = ", ".join(f"{k} {v}" for k, v in sub["t009_stratum"].value_counts().sort_index().items())
        dup = int(sub["score_record"].str.startswith("duplicate").sum())
        L.append(f"| `{code}` | {text} | {n(len(sub))} | {kinds} | {n(sub['loss_reuse'].sum())} | {strata} | {n(dup)} |")
    dups = a[a["score_record"].str.startswith("duplicate")]
    L += ["", f"Duplicate C1 evaluations: for {n(len(dups))} anchors C1 holds more than one evaluation row for the same",
          "model path with different scores; the bridge row's scores equal a C1 row other than the one the",
          "T-009 panel keeps. None is in the primary stratum. Models: " + ", ".join(f"`{m}`" for m in sorted(dups["Model"])) + ".", "",
          "Loss values shared with another model (same loss and parameter count, different model) mark a",
          "chat, instruct or long-context variant carrying its base model's reported loss: the loss and the",
          "score then describe different models.", "",
          "## Primary stratum: loss-axis fingerprint", "",
          "| Model | N (raw) | D (raw) | Loss (C5) | Published Chinchilla law | Classic IF3 | Inside IF3 box |",
          "| --- | ---: | ---: | ---: | ---: | ---: | --- |"]
    for _, r in fp.iterrows():
        L.append(f"| `{r['model']}` | {g(r['n_raw'])} | {g(r['d_raw'])} | {f(r['val_loss'], 4)} | {f(r['published_law'], 5)} | {f(r['classic_if3'], 5)} | {'yes' if r['inside_if3_box'] else 'no'} |")
    dmax = float(np.max(np.abs(fp["val_loss"] - fp["published_law"])))
    L += ["", f"Max |loss - published law| = {g(dmax, 3)}; the loss column is stored to 4 decimals. The primary",
          "anchors' losses are therefore the published law evaluated at (N, D), the B1 fingerprint T-008",
          "recorded: this stratum is on the classic-IF3 loss scale, and its loss is not an independent",
          "measurement. Its benchmark scores are the accepted C1 values.", "",
          "## Candidate forms and validation (primary stratum)", "",
          "Declared before any error was compared (`src/evolution/config.py`): `constant`; `linear` with",
          "slope <= 0; `logit_linear` = 100 / (1 + exp(-(a + b loss))) with b <= 0. Validation is",
          f"leave-one-anchor-out over the {n(len(prim))} anchors (one family, so no family block-out is possible).",
          "Selection rule: a form with a slope is eligible only if its slope is off the monotonicity boundary in",
          "the full fit and every fold; among eligible forms take the fewest parameters whose out-of-fold RMSE",
          "is within one standard error of the best.", "",
          "| Form | Full-fit parameters | LOAO RMSE | SE | MAE | Max abs error | Eligible |",
          "| --- | --- | ---: | ---: | ---: | ---: | --- |"]
    for r in results:
        params = ", ".join(f"{k} {g(v, 4)}" for k, v in r.params.items())
        L.append(f"| `{r.form}` | {params} | {f(r.rmse, 3)} | {f(r.rmse_se, 3)} | {f(float(np.mean(np.abs(r.errors))), 3)} | {f(float(np.max(np.abs(r.errors))), 3)} | {'yes' if r.stable else 'no'} |")
    L += ["", f"Best out-of-fold RMSE: `{sel['best_form']}` {f(sel['best_rmse'], 3)}; one-SE threshold {f(sel['one_se_threshold'], 3)};",
          f"within it: {', '.join('`' + x + '`' for x in sel['within_one_se'])}. **Chosen: `{chosen.form}`.**", "",
          "| Anchor | Loss | Macro score | Out-of-fold prediction (chosen form) |", "| --- | ---: | ---: | ---: |"]
    for (_, r), pred in zip(prim.iterrows(), chosen.fold_pred):
        L.append(f"| `{r['Model']}` | {f(r['Val_Loss'], 4)} | {f(r['panel_macro'])} | {f(pred)} |")
    s2 = o["s2"]
    rho = float(spearmanr(s2["Val_Loss"], s2["panel_macro"]).statistic)
    blk = o["s2_block"]
    L += ["", "## Diagnostic: the cross-family literature stratum (not a release candidate)", "",
          f"- anchors: {n(len(s2))} from {n(s2['org'].nunique())} organisations; Spearman(loss, macro) = {f(rho, 3)}",
          f"- leave-one-organisation-out RMSE: `constant` {f(blk['constant']['rmse'])}, `linear` {f(blk['linear']['rmse'])} (n = {blk['linear']['n']})",
          "",
          "| Organisation (>= 3 anchors) | Anchors | Spearman(loss, macro) |", "| --- | ---: | ---: |"]
    within = []
    for org, sub in s2.groupby("org"):
        if len(sub) >= 3:
            r = float(spearmanr(sub["Val_Loss"], sub["panel_macro"]).statistic)
            within.append(r)
            L.append(f"| `{org}` | {len(sub)} | {f(r, 3)} |")
    L += ["",
          ("Within an organisation, lower reported loss goes with a higher score (Spearman "
           + f(min(within), 3) + " to " + f(max(within), 3) + ")." if within and max(within) < 0 else
           "Within organisations the association is mixed."),
          ("Across families, the same losses predict an unseen family's score no better than a constant."
           if blk["linear"]["rmse"] >= blk["constant"]["rmse"] else
           "Across families a linear loss term improves on a constant out of family."),
          "The losses come from different validation sets, tokenizers and loss definitions (training,",
          "validation, \"final\"), so each family sits on its own loss scale: the ordering transfers within a",
          "family, the level does not transfer across families. This stratum is carried as a count only and",
          "is never pooled with the primary stratum."]
    L += ["", "## IF4 release", "",
          "| Gate | Evidence | Result |", "| --- | --- | --- |",
          f"| anchor identities reconciled | {n((a['identity_tier'] == 'exact').sum())} exact, one-to-one; primary anchors all `panel_match` | PASS |",
          f"| primary stratum defensible | organizer label High; same family and validation set; on the IF3 loss scale | PASS |",
          f"| positive anchor count | {p['n_anchor_models']} | PASS |",
          f"| out-of-fold error | leave-one-anchor-out RMSE {f(p['prediction_error']['loao_rmse'], 3)} | PASS |",
          "| score scale explicit | `score_scale` field | PASS |",
          "| provenance explicit | `provenance` field, incl. the fingerprint and support caveats | PASS |",
          f"| uncertainty for propagation | `predictive_sd` = {f(p['prediction_error']['predictive_sd'], 3)} score points | PASS |",
          "| `.validate()` | `IF4LossBenchmarkBridge.validate()` | PASS |", "",
          f"- path: `data_local/problem-f/interfaces/{IF4_FILENAME}` (local-only)",
          f"- SHA-256: `{o['if4_sha']}`",
          f"- form: {p['form'].split(';')[0]}; parameters " + ", ".join(f"{k} {g(v, 6)}" for k, v in p['params'].items()),
          f"- strata: " + ", ".join(f"{k} {v}" for k, v in p["strata"].items()) + f"; primary `{p['primary_stratum']}`",
          "",
          ("**What IF4 says.** On the classic-IF3 loss scale, between loss "
           + f(p['params']['loss_support_min'], 4) + " and " + f(p['params']['loss_support_max'], 4)
           + ", the macro score is " + (f"constant at {f(p['params']['c'])}" if chosen.form == "constant" else "described by the chosen form")
           + f" with out-of-fold error {f(p['prediction_error']['loao_rmse'], 2)} points. "
           + ("No loss-to-score slope is identified: the benchmark sits at its floor throughout the support. "
              if chosen.form == "constant" else "")
           + "IF4 cannot translate any loss outside that interval."), ""]
    chk = o["bridge_check"]
    csub = o["compute_subset"]
    L += ["## Bridge-based translation", "",
          "A bridge-based score needs a loss on the IF4 scale inside the IF4 support; the loss of a real",
          "model comes from the classic IF3, which is accepted only inside its box.", "",
          f"- compute-bearing C4 rows with inferred (N, D) inside the IF3 box: {n(csub['inside_if3_box'].sum())}; of these, non-anchor rows whose IF3 loss lies inside the IF4 support: {n(len(chk))}",
          ]
    if len(chk):
        L += ["", "| Model | IF3 loss | Bridge score | Bridge band SD | Observed macro |", "| --- | ---: | ---: | ---: | ---: |"]
        for _, r in chk.iterrows():
            L.append(f"| `{r['model']}` | {f(r['if3_loss'], 4)} | {f(r['bridge_mean'])} | {f(r['bridge_sd'])} | {f(r['macro'])} |")
        L += ["", "Band SD = root sum of squares of the IF4 predictive SD and the propagated loss uncertainty.",
              f"The loss uncertainty is the classic IF3's observed external error (B4 with Pythia excluded,",
              f"median abs. rel. error {f(o['if3_ext_rel'], 4)}, scaled to an SD by 1.4826); the B1 bootstrap intervals are",
              "not used because they measure generator recovery, not real-world precision. "
              + ("With a constant bridge the loss uncertainty contributes nothing to the score, so the IF4 error is the whole band: bridge uncertainty dominates."
                 if chosen.form == "constant" else "")]
    lo_support = p["params"]["loss_support_min"]
    has_loss = csub["if3_loss"].notna()
    capable = csub[has_loss & (csub["macro"] > float(prim["panel_macro"].max()) + 3 * p["prediction_error"]["predictive_sd"])]
    fs_bc = o["groups"]["BC"]["frame"]
    fs_bc = fs_bc[fs_bc["frontier_set"]]
    L += ["",
          f"**Frontier translation is not admissible.** Of the {n(has_loss.sum())} compute-bearing rows with an inferred D,",
          f"{n(len(capable))} score more than three bridge SDs above the anchors' highest score; "
          f"{n((~capable['inside_if3_box']).sum())} of those lie outside the IF3 box and {n((capable['if3_loss'] < lo_support).sum())} have an",
          f"(extrapolated) IF3 loss below the IF4 support minimum {f(lo_support, 4)}. The BC frontier set's median size is",
          f"{f(float(fs_bc['params_b'].median()))}B parameters against a box maximum of {f(o['if3'].box['N'][1] / 1e9)}B. Wherever the benchmark",
          "moves off its floor, a bridge-based score would need an IF3 extrapolation and a bridge extrapolation",
          "together, so none is produced: every frontier forecast in `q4-frontier-forecast.md` is direct",
          "score-based.", ""]
    return write("q4-bridge.md", L)


# ---------------------------------------------------------------------------
# Rendering: decomposition
# ---------------------------------------------------------------------------

def render_decomposition(o: Dict[str, object]) -> Path:
    L = ["# Q4 scale versus non-scale decomposition", "", GEN, "",
         "Language: direct panel summaries are observed / descriptive. The residual time component is a",
         "**non-scale-associated historical trend** (a conditional time association): it holds everything that",
         "moved with calendar time at fixed parameter count, including training-data and compute growth that",
         "parameter count does not measure. It is not called algorithmic or technical progress, and nothing",
         "here establishes a causal effect of calendar time.", "",
         f"Uncertainty: {CI_LABEL}; whole calendar months are resampled.", "",
         "## A. Broad panel, parameter scale", "",
         "### Mean capability (exact split, all models)", "",
         "OLS: `macro = a + b log10 N + g t`, and `log10 N = c + s t`. By the omitted-variable identity the",
         "time-only slope equals `g + b s` exactly (checked to 1e-8), so the change in mean score per year",
         "splits into a scale-associated part `b s` and a non-scale-associated part `g`.", "",
         "| Group | n | Time-only trend (pts/yr) | b (pts per decade of N) | s (decades of N per yr) | Scale-associated (pts/yr) | Non-scale-associated (pts/yr) | Scale share |",
         "| --- | ---: | --- | --- | --- | --- | --- | --- |"]
    for grp, r in o["groups"].items():
        c, b = r["comp"], r["boot"]
        L.append(f"| {grp} | {n(c['mean_n'])} | {f(c['mean_g_time'])} {ci(b['mean_g_time'])} | {f(c['mean_b_scale'])} {ci(b['mean_b_scale'])} | "
                 f"{f(c['mean_scale_growth'], 3)} {ci(b['mean_scale_growth'], 3)} | {f(c['mean_scale_rate'])} {ci(b['mean_scale_rate'])} | "
                 f"{f(c['mean_resid_rate'])} {ci(b['mean_resid_rate'])} | {share_cell(c['mean_share_scale'], b['mean_share_scale'], b['mean_g_time'])} |")
    L += ["", "A share is reported only when the time-only trend's interval excludes zero; otherwise the two",
          "components (in points per year) are the result and a percentage split would be meaningless."]
    L += ["", "### Frontier", "",
          f"The frontier is the conditional {int(100 * FRONTIER_QUANTILE)}th percentile of the macro score (linear quantile regression on time).",
          "", "**Predeclared additive quantile decomposition - consistency check.** `Q_0.9(macro | log10 N, t) = a + b log10 N + g t`",
          "with the frontier scale path `Q_0.9(log10 N | t) = c + s t`. Quantiles obey no exact identity, so its",
          "decomposed total `b s + g` is checked against the direct frontier trend.", "",
          "| Group | Direct frontier trend | b | g | s | Decomposed total b s + g | Gap | Consistent |",
          "| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |"]
    for grp, r in o["groups"].items():
        c = r["comp"]
        L.append(f"| {grp} | {f(c['g_time'])} | {f(c['q_b_scale'])} | {f(c['q_resid_rate'])} | {f(c['q_scale_growth'], 3)} | {f(c['q_decomposed_total'])} | {f(c['q_consistency_gap'])} | {'yes' if c['q_consistent'] else 'NO'} |")
    any_fail = any(not r["comp"]["q_consistent"] for r in o["groups"].values())
    if any_fail:
        L += ["", "The additive quantile decomposition fails its own check: its decomposed total does not reproduce",
              "the direct frontier trend. The matched-scale diagnostic below shows why - the frontier's time trend",
              "differs strongly by scale band, which one additive slope cannot represent. It is therefore **not**",
              "used to split the frontier trend."]
    L += ["", "**Frontier-set split (used for the forecast).** The frontier set is the models at or above their own",
          f"month's {int(100 * FRONTIER_QUANTILE)}th-percentile score, in months with at least {MIN_BIN_N} models. The exact OLS split above is",
          f"applied to it when it holds at least {MIN_FRONTIER_SET_N} models over at least {MIN_TRAIN_BINS} months.", "",
          "| Group | Frontier-set models | Months | Time-only trend | b | s (decades/yr) | Scale-associated | Non-scale-associated | Scale share |",
          "| --- | ---: | ---: | --- | --- | --- | --- | --- | --- |"]
    for grp, r in o["groups"].items():
        c, b = r["comp"], r["boot"]
        if c["split_identified"]:
            L.append(f"| {grp} | {n(c['fs_n'])} | {n(c['fs_months'])} | {f(c['fs_g_time'])} {ci(b['fs_g_time'])} | {f(c['fs_b_scale'])} {ci(b['fs_b_scale'])} | "
                     f"{f(c['fs_scale_growth'], 3)} {ci(b['fs_scale_growth'], 3)} | {f(c['fs_scale_rate'])} {ci(b['fs_scale_rate'])} | "
                     f"{f(c['fs_resid_rate'])} {ci(b['fs_resid_rate'])} | {share_cell(c['fs_share_scale'], b['fs_share_scale'], b['fs_g_time'])} |")
        else:
            L.append(f"| {grp} | {n(c['fs_n'])} | {n(c['fs_months'])} | not identified (below the size rule) | | | | | |")
    L += ["", "### Matched-scale diagnostic", "",
          f"Time trend within fixed parameter bands (bands with at least {MIN_BAND_N} models). Positive within-band",
          "trends mean performance changed at fixed scale.", "",
          "| Group | Band | Models | Months | Frontier trend (pts/yr) | Mean trend (pts/yr) |", "| --- | --- | ---: | ---: | ---: | ---: |"]
    for grp, r in o["groups"].items():
        for _, m in r["matched"].iterrows():
            L.append(f"| {grp} | {m['band']} | {n(m['n'])} | {n(m['months'])} | {f(m['frontier_time_trend'])} | {f(m['mean_time_trend'])} |")
    L += ["", "### Scale specification", "",
          "Non-scale-associated mean trend `g` (pts/yr) under three declared scale representations.", "",
          "| Group | linear log10 N | + quadratic log10 N | scale-band fixed effects |", "| --- | ---: | ---: | ---: |"]
    for grp, r in o["groups"].items():
        s = r["specs"]
        L.append(f"| {grp} | {f(s['linear_log10N'])} | {f(s['quadratic_log10N'])} | {f(s['scale_band_fixed_effects'])} |")
    L += ["", "### Dimension-level results", "",
          "The macro score is never the only view: each dimension's frontier and mean movement.", "",
          "| Group | Dimension | Frontier level at anchor | Frontier trend | Mean trend | Mean scale-associated | Mean non-scale-associated |",
          "| --- | --- | ---: | ---: | ---: | ---: | ---: |"]
    for grp, r in o["groups"].items():
        for _, d in r["dims"].iterrows():
            L.append(f"| {grp} | {d['dimension']} | {f(d['frontier_level'])} | {f(d['frontier_trend'])} | {f(d['mean_trend'])} | {f(d['mean_scale_rate'])} | {f(d['mean_resid_rate'])} |")
    # Compute-aware
    cs: pd.DataFrame = o["compute_subset"]
    sz = o["compute_sizes"]
    L += ["", "## B. Compute-aware subset (C4-linked)", "",
          "| Quantity | Value |", "| --- | ---: |",
          f"| panel models | {n(sz['n_panel'])} |", f"| deterministically linked to C4 | {n(sz['n_linked'])} |",
          f"| with a C4 training-compute estimate | {n(sz['n_compute'])} |",
          f"| compute subset (compute, dated, not a test upload) | {n(sz['n_subset'])} |",
          f"| of which in the primary population | {n(cs['in_primary'].sum())} |",
          f"| strata | " + ", ".join(f"{k} {v}" for k, v in cs["stratum"].value_counts().sort_index().items()) + " |",
          f"| date sources | " + ", ".join(f"{k} {v}" for k, v in cs["date_source"].value_counts().sort_index().items()) + " |",
          f"| D inferred as C/(6N) (compute estimated by operation counting) | {n(cs['d_inferred'].notna().sum())} |",
          f"| D not inferred (other estimation methods) | {n(cs['d_inferred'].isna().sum())} |",
          f"| inferred (N, D) inside the classic IF3 box | {n(cs['inside_if3_box'].sum())} |",
          "",
          f"**Selection bias.** The subset is {pct(sz['n_subset'] / sz['n_panel'])} of the panel and is concentrated in pretrained base",
          "models that Epoch AI records; fine-tunes and merges almost never link. It is not representative of",
          "the panel and nothing here is generalised to it. Where C4 also records a dataset size, inferred D",
          f"divided by it has median {f(float(cs['d_vs_dataset_size'].median()), 3)} (n = {n(cs['d_vs_dataset_size'].notna().sum())}).", "",
          "### Log compute", "",
          "OLS `macro = a + k log10 C + g t` (C = C4 training compute in FLOP) with `log10 C = c + s t`; the",
          "time-only slope splits exactly into a compute-associated part `k s` and a non-compute-associated part",
          "`g`. Training compute moves with both parameters and tokens, so this is the decomposition in which",
          "data growth counts as scale.", "",
          "| Rows | n | Months | Time-only trend | k (pts per decade of compute) | s (decades of compute per yr) | Compute-associated (pts/yr) | Non-compute-associated (pts/yr) | Compute share |",
          "| --- | ---: | ---: | --- | --- | --- | --- | --- | --- |"]
    for label, key in (("stratum A only", "log_compute_A"), ("all compute rows", "log_compute_all")):
        r = o[key]
        pt, bt = r["point"], r["boot"]
        L.append(f"| {label} | {n(r['n'])} | {n(r['months'])} | {f(pt['g_time'])} {ci(bt['g_time'])} | {f(pt['slope_scale'])} {ci(bt['slope_scale'])} | "
                 f"{f(pt['scale_growth'], 3)} {ci(bt['scale_growth'], 3)} | {f(pt['scale_rate'])} {ci(bt['scale_rate'])} | "
                 f"{f(pt['slope_time'])} {ci(bt['slope_time'])} | {share_cell(pt['share_scale'], bt['share_scale'], bt['g_time'])} |")
    L += ["", "These rows span several years of publication dates, unlike the leaderboard window, and are almost",
          "all pretrained base models: the compute share describes this subset only."]
    ip, ie = o["if3_primary"], o["if3_extrap"]
    L += ["", "### Classic IF3", "",
          f"- primary IF3 decomposition (inside-box rows only): **{ip['status']}** - n = {ip['n']}"
          + (f"; {ip['reason']}; all of them score between {f(float(cs.loc[cs['inside_if3_box'], 'macro'].min()))} and {f(float(cs.loc[cs['inside_if3_box'], 'macro'].max()))}, at the benchmark floor" if ip['status'] != 'estimated' else ""),
          f"- extrapolation sensitivity (all D-inferred rows, {ie['n_outside']} of {ie['n']} outside the box - **extrapolation**): "
          f"`macro = a + k L_IF3 + g t` gives k = {f(ie['point']['slope_scale'])} pts per unit loss, g = {f(ie['point']['slope_time'])} pts/yr",
          "",
          "Classic-IF3 caveat, carried from T-008: the principal B1 fit supports estimator / generator recovery,",
          "not precise real-world scaling; external support is B4 with the overlapping Pythia rows excluded and",
          "B5. The IF3 loss above is a model-conditional scale index, and outside the box an extrapolation.", "",
          "## Detailed-task analysis", "",
          "Omitted. The accepted T-009 per-task aggregation (`q4-detailed-task-analysis.md`, BBH and MUSR)",
          "already satisfies the per-task requirement, and the dimension-level table above shows the movement a",
          "macro average could hide. No C8 child record is read by T-011, so the MATH quarantine is untouched.", ""]
    return write("q4-decomposition.md", L)


# ---------------------------------------------------------------------------
# Rendering: forecast
# ---------------------------------------------------------------------------

def render_forecast(o: Dict[str, object]) -> Path:
    pop = o["pop"]
    hd = dynamics.horizon_dates(pop.anchor)
    L = ["# Q4 frontier and forecast", "", GEN, "",
         "## Definitions", "",
         f"- Frontier: the conditional {int(100 * FRONTIER_QUANTILE)}th percentile of the macro score, by linear quantile regression on",
         "  calendar time (level at the anchor and trend). Fixed before any forecast was evaluated; not tuned.",
         f"- Descriptive frontier: the monthly {int(100 * FRONTIER_QUANTILE)}th percentile, reported only for months with at least {MIN_BIN_N} models",
         f"  (smaller months are flagged sparse). Sensitivities: the monthly maximum and top-{TOP_K} mean.",
         f"- **Anchor: {date(pop.anchor)}**, the final observed date of the primary population.",
         f"- **12-month primary horizon: {date(hd['primary_12m'])}. 24-month stress horizon: {date(hd['stress_24m'])}** (stress / longer-horizon",
         "  extrapolation; never co-equal evidence).",
         "- Split: the frontier trend is divided into scale-associated and non-scale-associated parts by the",
         "  frontier-set shares (`q4-decomposition.md`).",
         f"- Scenarios (the problem asks for slowing compute growth): the scale-associated part is multiplied by "
         + ", ".join(f"{k} = {v:g}" for k, v in SCENARIOS.items()) + f"; primary `{PRIMARY_SCENARIO}`. A slowdown only",
         "  removes a positive scale-associated part; where that part is not positive the scenario is non-binding.",
         "- The non-scale-associated part is assumed to continue linearly over the horizon. That is an",
         "  assumption, not a finding; nothing supports it beyond the observed window.", ""]
    for grp, r in o["groups"].items():
        bins = r["bins"]
        c = r["comp"]
        L += [f"## Group {grp}: {GROUP_LABELS[grp]}", "", "### Historical frontier", "",
              "| Month | Models | Sparse | P90 | Max | Top-k mean | Median | Frontier models' median params (B) |",
              "| --- | ---: | --- | ---: | ---: | ---: | ---: | ---: |"]
        for _, b in bins.iterrows():
            L.append(f"| {b['month']} | {n(b['n'])} | {'yes' if b['sparse'] else 'no'} | {f(b['p90'])} | {f(b['max'])} | {f(b['top_k_mean'])} | {f(b['median'])} | {f(b['frontier_median_params_b'])} |")
        dense = bins[~bins["sparse"]]
        L += ["", f"Non-sparse months: {n(len(dense))}. Frontier level at the anchor {f(c['level0'])} {ci(r['boot']['level0'])}; "
              f"frontier trend {f(c['g_time'])} {ci(r['boot']['g_time'])} pts/yr.", ""]
        if c["split_identified"]:
            L.append(f"Split: scale-associated {f(c['frontier_scale_rate'])} pts/yr, non-scale-associated {f(c['frontier_resid_rate'])} pts/yr "
                     f"(frontier-set scale share {pct(c['fs_share_scale'])}).")
        else:
            L.append(f"Split: **not identified** (frontier set of {n(c['fs_n'])} models over {n(c['fs_months'])} months is below the size rule); every scenario equals the time-only trend.")
        fc = r["forecast"]
        L += ["", "### Forecast", ""]
        if r["backtest_h"] == 0:
            L += ["**UNVALIDATED EXTRAPOLATION.** This group has too few non-sparse months for any out-of-time",
                  "check (see below); its numbers are shown for completeness and are not a supported forecast.", ""]
        L += [
              "| Horizon | Date | Scenario | Binding | Point | Bootstrap 90% | Predictive 90% | Predictive 90% incl. backtest error |",
              "| --- | --- | --- | --- | ---: | --- | --- | --- |"]
        bt = r["backtest"]
        bt_rmse = float(np.sqrt(np.mean(bt.loc[bt["method"] == "time_only", "error"] ** 2))) if len(bt) else float("nan")
        for _, row in fc.iterrows():
            infl = (f"[{f(row['point'] - dynamics.Z90 * np.sqrt(row['sd_total'] ** 2 + bt_rmse ** 2))}, "
                    f"{f(row['point'] + dynamics.Z90 * np.sqrt(row['sd_total'] ** 2 + bt_rmse ** 2))}]") if np.isfinite(bt_rmse) else "n/a (no backtest)"
            label = "12-month forecast" if row["horizon"] == "primary_12m" else "24-month STRESS extrapolation"
            L.append(f"| {label} | {date(row['date'])} | `{row['scenario']}` | {'yes' if row['binding'] else 'no'} | {f(row['point'])} | "
                     f"[{f(row['boot_lo'])}, {f(row['boot_hi'])}] | [{f(row['pred_lo'])}, {f(row['pred_hi'])}] | {infl} |")
        L += ["", "### Uncertainty components (SD, score points; primary scenario)", "",
              "| Horizon | Frontier level at anchor | Trend increment | Joint bootstrap | Monthly frontier scatter | Total predictive | Classic IF3 | IF4 bridge |",
              "| --- | ---: | ---: | ---: | ---: | ---: | --- | --- |"]
        for _, row in fc[fc["scenario"] == PRIMARY_SCENARIO].iterrows():
            L.append(f"| {row['horizon']} | {f(row['sd_level'])} | {f(row['sd_increment'])} | {f(row['sd_boot'])} | {f(row['sd_bin_noise'])} | {f(row['sd_total'])} | not used | not used |")
        L += ["",
              "- *Bootstrap 90%*: month-block bootstrap of the whole frontier fit (level, trend and split) - estimation",
              "  uncertainty of the frontier line only.",
              "- *Predictive 90%*: adds the scatter of monthly frontier points around the fitted line, i.e. what a",
              "  single future month's frontier may show. Normal approximation.",
              "- *incl. backtest error*: adds, in quadrature, the time-only method's RMSE at the backtest horizon below.",
              "- Scenario spread is not a probability and is not folded into any band.",
              "- Classic IF3 and IF4 do not enter: the forecast is direct score-based, because a bridge-based",
              "  frontier forecast is not admissible (`q4-bridge.md`). No band here conditions on a bridge.", ""]
        L += ["### Rolling-origin validation", ""]
        feas = ", ".join(f"{h}m: {k}" for h, k in r["feasible"].items())
        if r["backtest_h"] == 0:
            L += [f"No horizon has at least {MIN_ORIGINS} origins with {MIN_TRAIN_BINS} non-sparse training months and a non-sparse target",
                  f"(origins by horizon - {feas}). **No out-of-time validation is possible for this group**; its forecast is",
                  "an unvalidated extrapolation.", ""]
        else:
            L += [f"Longest horizon with at least {MIN_ORIGINS} origins (each with {MIN_TRAIN_BINS}+ non-sparse training months and a",
                  f"non-sparse target): **{r['backtest_h']} months** (origins by horizon - {feas}). A 12-month backtest is not",
                  "possible on this history and none is claimed.", "",
                  "| Origin | Target | Method | Forecast | Observed P90 | Error |", "| --- | --- | --- | ---: | ---: | ---: |"]
            for _, e in bt.iterrows():
                L.append(f"| {e['origin']} | {e['target']} | {e['method']} | {f(e['forecast'])} | {f(e['observed'])} | {f(e['error'])} |")
            L += ["", "| Method | Origins | MAE | Mean error (bias) | RMSE |", "| --- | ---: | ---: | ---: | ---: |"]
            for method, sub in bt.groupby("method", sort=False):
                e = sub["error"].to_numpy(float)
                L.append(f"| {method} | {len(e)} | {f(float(np.mean(np.abs(e))))} | {f(float(np.mean(e)))} | {f(float(np.sqrt(np.mean(e ** 2))))} |")
            errs = bt.loc[bt["method"] == "time_only", "error"]
            direction = "under" if (errs < 0).all() else "over" if (errs > 0).all() else None
            L += ["",
                  (f"Every time-only backtest forecast {direction}-predicted the observed frontier (mean error {f(float(errs.mean()))}):"
                   if direction else f"Time-only backtest errors change sign (mean error {f(float(errs.mean()))}):"),
                  "the model-based bands are conditional on a linear trend that the backtest does not fully bear out,",
                  "so the band including backtest error is the more honest one.", ""]
        L += sensitivity_lines(o, grp, r)
    return write("q4-frontier-forecast.md", L)


def sensitivity_lines(o: Dict[str, object], grp: str, r: Dict[str, object]) -> List[str]:
    """Date-clock and compute-aware sensitivities of this group's headline forecast."""
    rb = o["robust"]["population"]
    L = ["### Sensitivity of the headline", "",
         f"12-month point under `{PRIMARY_SCENARIO}` when the date clock changes (each anchored at its own final date):", "",
         "| Population | Frontier trend (pts/yr) | 12-month point |", "| --- | ---: | ---: |"]
    for name in ("primary", "publication_date_only", "fallback_date_only"):
        row = rb[(rb["population"] == name) & (rb["group"] == grp)]
        if len(row) and "g_time" in row and np.isfinite(row["g_time"].iloc[0]):
            L.append(f"| `{name}` | {f(float(row['g_time'].iloc[0]))} | {f(float(row['f12'].iloc[0]))} |")
    L.append("")
    pc = o["log_compute_A"]
    share, draws, total = pc["point"]["share_scale"], pc["boot"]["share_scale"], pc["boot"]["g_time"]
    lo_total, _ = interval(total, *INTERVAL)
    c = r["comp"]
    L += ["Compute-aware slowdown (transfer assumption, sensitivity only): the parameter-scale split puts",
          "training-data growth into the non-scale part, so the scenarios above cannot express a compute",
          "slowdown that acts through training data. Here the frontier trend is instead split by the compute",
          "share of the stratum-A compute subset",
          "(`q4-decomposition.md`, section B) and that share is slowed. The subset is small and not",
          "representative, and its share is transferred to this group's frontier unchanged.", ""]
    if not (np.isfinite(share) and share > 0 and np.isfinite(lo_total) and lo_total > 0):
        L += ["Not computed: the compute share is not positive or its total trend interval includes zero.", ""]
        return L
    lo_s, hi_s = interval(draws, *INTERVAL)
    L += [f"Compute share {pct(share)} (interval {pct(max(lo_s, 0.0))} to {pct(min(hi_s, 1.0))}).", "",
          "| Horizon | Compute-growth multiplier | Point | Range over the share interval |", "| --- | ---: | ---: | --- |"]
    for horizon, dte in dynamics.horizon_dates(o["pop"].anchor).items():
        h = dynamics.years_between(dte, o["pop"].anchor)
        for m in (0.5, 0.0):
            def at(sh: float) -> float:
                return c["level0"] + c["g_time"] * (1.0 - (1.0 - m) * sh) * h
            vals = [at(max(lo_s, 0.0)), at(min(hi_s, 1.0))]
            label = "12-month" if horizon == "primary_12m" else "24-month stress"
            L.append(f"| {label} | {m:g} | {f(at(share))} | [{f(min(vals))}, {f(max(vals))}] |")
    L.append("")
    return L


# ---------------------------------------------------------------------------
# Rendering: robustness
# ---------------------------------------------------------------------------

def render_robustness(o: Dict[str, object]) -> Path:
    rb = o["robust"]
    L = ["# Q4 forecast and decomposition robustness", "", GEN, "",
         "A small matrix declared in advance (`src/evolution/population.py`, `src/evolution/dynamics.py`).",
         "No specification below was chosen for its result; point estimates only.", "",
         "## Population alternatives", "",
         f"All rates in points per year. Scale / non-scale columns are the additive components (a share of a",
         f"small total is unstable, so none is shown). 12-month point under `{PRIMARY_SCENARIO}`, anchored at each",
         "alternative's own final observed date.", "",
         "| Population | Group | n | Final date | Frontier level | Frontier trend | Frontier scale-assoc. | Frontier non-scale | Mean scale-assoc. | Mean non-scale | Additive quantile consistent | 12-month point |",
         "| --- | --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: |"]
    for _, r in rb["population"].iterrows():
        if "level0" not in r or not np.isfinite(r.get("level0", np.nan)):
            L.append(f"| `{r['population']}` | {r['group']} | {n(r['n'])} | {date(r['anchor'])} | too few rows | | | | | | | |")
            continue
        L.append(f"| `{r['population']}` | {r['group']} | {n(r['n'])} | {date(r['anchor'])} | {f(r['level0'])} | {f(r['g_time'])} | "
                 f"{f(r['fs_scale_rate'])} | {f(r['fs_resid_rate'])} | {f(r['mean_scale_rate'])} | {f(r['mean_resid_rate'])} | "
                 f"{'yes' if r['q_consistent'] else 'no'} | {f(r['f12'])} |")
    L += ["", "`n/a` in the frontier columns: the frontier-set split is not identified (size rule).", "",
          "## T-009 strata B and C separately (primary rules)", "",
          "| Stratum | n | Frontier level | Frontier trend | Frontier scale-assoc. | Frontier non-scale | Mean scale-assoc. | Mean non-scale | 12-month point |",
          "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"]
    for _, r in rb["strata"].iterrows():
        L.append(f"| {r['stratum']} | {n(r['n'])} | {f(r['level0'])} | {f(r['g_time'])} | {f(r['fs_scale_rate'])} | {f(r['fs_resid_rate'])} | "
                 f"{f(r['mean_scale_rate'])} | {f(r['mean_resid_rate'])} | {f(r['f12'])} |")
    L += ["", "## Frontier estimator", "",
          "Trend (pts/yr) of the frontier under each estimator: the primary quantile regression, and OLS",
          f"slopes through the non-sparse monthly P90, maximum and top-k mean (shown only with at least {MIN_ORIGINS}",
          "non-sparse months; fewer cannot support a slope).", "",
          "| Group | Non-sparse months | Quantile regression (primary) | Monthly P90 | Monthly max | Monthly top-k mean |",
          "| --- | ---: | ---: | ---: | ---: | ---: |"]
    for _, r in rb["estimators"].iterrows():
        ok = r["dense_bins"] >= MIN_ORIGINS
        cells = [f(r[c]) if ok else "too few months" for c in ("p90", "max", "top_k_mean")]
        L.append(f"| {r['group']} | {n(r['dense_bins'])} | {f(r['quantile_regression'])} | {' | '.join(cells)} |")
    L += ["", "Scale-specification and date-source sensitivities are in `q4-decomposition.md` and in the",
          "`publication_date_only` / `fallback_date_only` rows above.", ""]
    return write("q4-forecast-robustness.md", L)


def main() -> int:
    out = compute_all()
    paths = [render_population(out), render_bridge(out), render_decomposition(out),
             render_forecast(out), render_robustness(out)]
    for p in paths:
        print("wrote " + p.relative_to(REPO).as_posix())
    print("wrote IF4 " + out["if4_path"].relative_to(REPO).as_posix() + " sha256 " + out["if4_sha"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
