"""T-011 reproduction: two complete passes, byte-identical artifacts, inputs untouched.

Runs ``scripts/q4_evolution_run.py`` twice and requires every T-011 artifact to be
byte-identical across the passes and LF-only. Around both passes it also
requires that:

* the restored Attachment-C tree still matches the intake manifest, and is
  unchanged in content, size and modification time;
* the accepted classic IF3 bytes are unchanged;
* every accepted T-009 table still equals its committed blob;
* the direct runtime equals the versions pinned in ``environment.yml``.

Writes ``results/tables/q4-evolution-reproduction.md``. Regenerate; do not edit by hand.

    conda run -n modeling-research-2026 --no-capture-output python scripts/q4_evolution_reproduce.py
"""

from __future__ import annotations

import hashlib
import platform
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

import numpy  # noqa: E402
import pandas  # noqa: E402
import scipy  # noqa: E402
import yaml  # noqa: E402

from src.evolution import receipts  # noqa: E402
from src.evolution.config import IF4_FILENAME, SEED  # noqa: E402
from src.paths import ATT_C, PROBLEM_F_INTERFACES, TABLES, ensure  # noqa: E402

GENERATOR = REPO / "scripts" / "q4_evolution_run.py"
ARTIFACTS = [TABLES / name for name in (
    "q4-evolution-population.md", "q4-bridge.md", "q4-decomposition.md",
    "q4-frontier-forecast.md", "q4-forecast-robustness.md")] + [PROBLEM_F_INTERFACES / IF4_FILENAME]
T009_TABLES = ["q4-c8-reconciliation.md", "q4-c8-diagnosis.md", "q4-detailed-task-analysis.md",
               "q4-panel-schema.md", "q4-panel-coverage.md", "q4-model-strata.md", "q4-date-coverage.md",
               "q4-c4-metadata-coverage.md", "q4-eligibility.md"]


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rel(path: Path) -> str:
    return path.relative_to(REPO).as_posix()


def c_tree_state():
    return {p.relative_to(REPO).as_posix(): (sha(p), p.stat().st_size, p.stat().st_mtime_ns)
            for p in sorted(ATT_C.rglob("*")) if p.is_file()}


def git(*args: str) -> str:
    return subprocess.run(["git", "-C", str(REPO), *args], check=True, capture_output=True, text=True).stdout.strip()


def t009_unchanged():
    out = {}
    for name in T009_TABLES:
        path = "results/tables/" + name
        out[name] = git("hash-object", path) == git("rev-parse", "HEAD:" + path)
    return out


def pinned_runtime():
    env = yaml.safe_load((REPO / "environment.yml").read_text(encoding="utf-8"))
    pins = {}
    for dep in env["dependencies"]:
        if isinstance(dep, str) and "=" in dep:
            name, version = dep.split("=", 1)
            pins[name.strip()] = version.strip()
    actual = {"python": platform.python_version(), "numpy": numpy.__version__, "scipy": scipy.__version__,
              "pandas": pandas.__version__, "pyyaml": yaml.__version__}
    return pins, actual


def run_pass(label: str):
    print(label + ": " + rel(GENERATOR), flush=True)
    subprocess.run([sys.executable, str(GENERATOR)], cwd=REPO, check=True, stdout=subprocess.DEVNULL)
    return ({rel(p): sha(p) for p in ARTIFACTS}, [rel(p) for p in ARTIFACTS if b"\r" in p.read_bytes()])


def main() -> int:
    print(f"seed {SEED}")
    pins, actual = pinned_runtime()
    runtime_ok = all(pins.get(k) == v for k, v in actual.items())
    tree = receipts.verify_c_tree()
    before = c_tree_state()
    if3_before = sha(receipts.IF3_FILE)
    t009_before = t009_unchanged()

    first, cr1 = run_pass("pass 1")
    second, cr2 = run_pass("pass 2")

    after = c_tree_state()
    if3_after = sha(receipts.IF3_FILE)
    t009_after = t009_unchanged()
    identical = first == second
    lf_only = not cr1 and not cr2
    raw_ok = before == after and tree["missing"] == tree["extra"] == tree["mismatched"] == 0
    if3_ok = if3_before == if3_after == receipts.accepted_if3_sha256()
    t009_ok = all(t009_before.values()) and all(t009_after.values())
    ok = identical and lf_only and raw_ok and if3_ok and t009_ok and runtime_ok

    L = ["# Q4 evolution reproduction", "",
         "Generated by `scripts/q4_evolution_reproduce.py`. Do not edit by hand.", "",
         "Two complete passes of `scripts/q4_evolution_run.py`. Hashes are of the bytes as generated; every",
         "artifact must be LF-only, which is also the form git stores, so a tracked table's hash can be checked",
         "on any platform with `git show HEAD:<path> | sha256sum`.", "",
         f"Seed: {SEED} (month-block bootstrap only).", "",
         "| Artifact | SHA-256, pass 1 | Pass 2 identical |", "| --- | --- | --- |"]
    for path, digest in first.items():
        L.append(f"| `{path}` | `{digest}` | {'yes' if second.get(path) == digest else 'NO'} |")
    L += ["", "| Check | Result |", "| --- | --- |",
          f"| all artifacts byte-identical across passes | {'PASS' if identical else 'FAIL'} |",
          f"| all artifacts LF-only | {'PASS' if lf_only else 'FAIL'} |",
          f"| Attachment-C tree vs intake manifest ({tree['manifest_rows']:,} files: missing {tree['missing']}, extra {tree['extra']}, mismatched {tree['mismatched']}) | {'PASS' if tree['missing'] == tree['extra'] == tree['mismatched'] == 0 else 'FAIL'} |",
          f"| Attachment-C tree unchanged in content, size and modification time across both passes | {'PASS' if before == after else 'FAIL'} |",
          f"| accepted classic IF3 bytes unchanged (`{if3_after[:16]}...`) | {'PASS' if if3_ok else 'FAIL'} |",
          f"| accepted T-009 tables equal their committed blobs, before and after ({len(T009_TABLES)} tables) | {'PASS' if t009_ok else 'FAIL'} |",
          f"| direct runtime equals `environment.yml` | {'PASS' if runtime_ok else 'FAIL'} |",
          "", "| Package | This run | environment.yml |", "| --- | --- | --- |"]
    for k in sorted(actual):
        L.append(f"| {k} | {actual[k]} | {pins.get(k, 'not pinned')} |")
    L += ["", f"**Reproduction: {'PASS' if ok else 'FAIL'}.**", ""]
    path = ensure(TABLES) / "q4-evolution-reproduction.md"
    text = "\n".join(L)
    path.write_text(text, encoding="utf-8", newline="\n")
    print("wrote " + rel(path))
    print("REPRODUCTION: " + ("PASS" if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
