"""Q4 step 4: the detailed task-level aggregation.

The task statement requires at least one per-task aggregation that goes beyond
the summary table. This script builds the model x subtask matrix of normalised
scores for the grouped dimensions that record per-subtask results (BBH, MATH
Lvl 5, MUSR) and then decomposes, for each, how much of the variance in a
subtask score is *between models* versus *within a model* — the one-way
intraclass correlation.

It writes ``results/tables/q4-detailed-task-analysis.md``.

Run:  python scripts/q4_panel_detail.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.panel.detail import extract_subtasks, load_payloads, variance_decomposition  # noqa: E402
from src.panel.leaderboard import load_detailed_results  # noqa: E402
from src.paths import ATT_C, RESULTS, ensure, require  # noqa: E402


def main() -> int:
    detailed = require(ATT_C / "detailed_results")

    print("parsing per-task records ...")
    records, damaged = load_detailed_results(detailed)
    payloads = load_payloads(detailed)
    print(f"  records: {len(records):,}   payloads: {len(payloads):,}")

    long = extract_subtasks(records, payloads)
    print(f"  subtask observations: {len(long):,}")
    print(f"  dimensions with subtasks: {sorted(long['dimension'].unique())}")

    decomp = variance_decomposition(long)
    print("\nvariance decomposition (between-model fraction of subtask-score variance):")
    for _, row in decomp.iterrows():
        print(f"  {row['dimension']:<12} n_models {row['n_models']:>5,}  "
              f"n_subtasks {row['n_subtasks']:>3}  ICC {row['icc']:.3f}")

    tables = ensure(RESULTS / "tables")
    lines = [
        "# Q4 detailed task-level analysis",
        "",
        "Generated by `scripts/q4_panel_detail.py`. Do not edit by hand.",
        "",
        "The summary table averages each grouped benchmark into one number. This",
        "page keeps the per-subtask normalised scores and asks one question of the",
        "resulting model x subtask matrix: **how much of the variance in a subtask",
        "score is between models, versus within a model?**",
        "",
        "A high between-model fraction (the intraclass correlation, ICC) means a",
        "model's average subtask score predicts its individual subtask scores — the",
        "benchmark is measuring one underlying ability. A low ICC means the",
        "subtasks are heterogeneous enough that they are measuring different",
        "things, and averaging them hides that.",
        "",
        f"- parsed records: {len(records):,}",
        f"- subtask-score observations: {len(long):,}",
        f"- dimensions with a subtask breakdown: {', '.join(sorted(long['dimension'].unique()))}",
        "",
        "## Variance decomposition",
        "",
        "One-way analysis of variance with model as the grouping factor, on the",
        "normalised per-subtask score. Only models with at least two subtasks in a",
        "dimension contribute (a single subtask has no within-model term).",
        "",
        "| Dimension | Models | Subtasks | Observations | Grand mean | Between SS | Within SS | ICC |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for _, row in decomp.iterrows():
        lines.append(
            f"| {row['dimension']} | {row['n_models']:,} | {row['n_subtasks']:,} | "
            f"{row['n_observations']:,} | {row['grand_mean']:.1f} | "
            f"{row['between_ss']:,.0f} | {row['within_ss']:,.0f} | {row['icc']:.3f} |"
        )
    lines += [
        "",
        "ICC is the fraction of total sum of squares explained by model identity",
        "(between SS / total SS). It ranges from 0 (all variation is within-model,",
        "so subtasks differ more than models do) to 1 (all variation is between",
        "models, so every subtask ranks models the same way).",
        "",
        "MATH Lvl 5's per-subtask records are the ones the diagnosis in",
        "`q4-c8-diagnosis.md` quarantines (a source mismatch), so its row here is",
        "descriptive of the C8 corpus only and must not be read as a claim about",
        "the models' math ability.",
        "",
    ]
    out = tables / "q4-detailed-task-analysis.md"
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"\nwrote {out.relative_to(Path(__file__).resolve().parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
