"""Q4 step 3: build the canonical panel and write the six schema/coverage tables.

This is the assembly entry point. It builds the panel once (``src.panel.panel``)
and emits the tracked, regenerable reports a reviewer needs to judge whether the
panel is a defensible foundation for Q4:

* ``q4-panel-schema.md``      — how C1/C2/C3/C4 relate, and the panel schema;
* ``q4-panel-coverage.md``    — C4 metadata linkage coverage, by stratum;
* ``q4-model-strata.md``      — the A-E model-type strata and their coverage;
* ``q4-date-coverage.md``     — primary/fallback date convention coverage;
* ``q4-c4-metadata-coverage.md`` — parameters/compute coverage among linked models;
* ``q4-eligibility.md``       — open-model eligibility counts.

It also writes the derived panel CSV under ``data_local/problem-f/derived/``
(local-only), which is the hand-off object for the downstream Q4 task.

Run:  python scripts/q4_panel_build.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict, List

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.panel.c4_link import link_summary  # noqa: E402
from src.panel.dates import date_coverage  # noqa: E402
from src.panel.eligibility import eligibility_counts  # noqa: E402
from src.panel.panel import build_panel, panel_columns, panel_shape, write_panel  # noqa: E402
from src.panel.sources import load_c1, load_c2, load_c3, load_c4, relationship  # noqa: E402
from src.panel.strata import STRATUM_LABELS, stratum_coverage  # noqa: E402
from src.paths import RESULTS, ensure  # noqa: E402

LINKED = "link_method != 'unlinked'"


def _write(path: Path, lines: List[str]) -> None:
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def schema_report(c1, c2, c3, c4, panel) -> Path:
    rel = relationship(c1, c2, c3)
    shape = panel_shape(panel)
    linked = int((panel["link_method"] != "unlinked").sum())

    cols_by_source = [
        ("leaderboard (C1/C2)", ["model", "params_b", "submission_date", "hub_license",
                                 "type", "average"] + [f"score_{d}" for d in
                                                       ("ifeval", "bbh", "math_lvl5", "gpqa", "musr", "mmlu_pro")]),
        ("Epoch AI via C2", ["pub_date", "org", "open_weights_epoch"]),
        ("Epoch AI via C4 (linked rows only)", [c for c in panel.columns if c.startswith("c4_")] + ["link_method"]),
        ("derived", ["type_coarse", "stratum", "stratum_source", "analysis_date", "date_source",
                     "date_confidence", "open_weights", "params_known", "score_available",
                     "date_available", "compute_available", "test_flag"]),
    ]

    lines = [
        "# Q4 panel schema and source relationship",
        "",
        "Generated by `scripts/q4_panel_build.py`. Do not edit by hand.",
        "",
        "The panel is one row per unique leaderboard model. This page records (a)",
        "how the four C tables relate to one another and (b) the panel's column",
        "schema by provenance, so a downstream reader never mistakes one table for",
        "an independent observation of another.",
        "",
        "## Source relationship",
        "",
        f"- C1 rows: {rel['c1_rows']:,}   C2 rows: {rel['c2_rows']:,}   C3 rows: {rel['c3_rows']:,}   C4 rows: {len(c4):,}",
        f"- C1 and C2 share the same model order: {rel['c1_c2_same_model_order']}",
        f"- C2 adds exactly these columns over C1: {', '.join(rel['c2_only_extra_columns'])}",
        f"- C1 vs C2 on shared numeric columns: {rel['c1_c2_differing_rows']} rows differ, "
        f"max |delta| {rel['c1_c2_max_numeric_abs_delta']}",
        f"- C1 models absent from C3: {len(rel['c1_models_absent_from_c3'])}; "
        f"C3 models absent from C1: {len(rel['c3_models_absent_from_c1'])}",
        f"- C1/C3 shared leaderboard models: {rel['c1_c3_shared_models']:,}, score "
        f"comparisons {rel['c1_c3_score_comparisons']:,}, mismatches {rel['c1_c3_score_mismatches']}",
        "",
        "C2 is C1 with three Epoch AI columns appended (same rows, same order); the",
        "numeric deltas are floating-point rounding noise. C3 re-expresses the",
        "leaderboard as a timeseries with mixed historical provenance, so it is",
        "reported here but not folded into the leaderboard panel.",
        "",
        "## Panel schema",
        "",
        f"Rows: {shape['rows']:,} (unique models). Columns: {shape['columns']:,}. "
        f"C4-linked rows: {linked:,}.",
        "",
    ]
    for group, cols in cols_by_source:
        present = [c for c in cols if c in panel.columns]
        lines.append(f"### {group}")
        lines.append("")
        for c in present:
            lines.append(f"- `{c}`")
        lines.append("")
    lines += [
        "## Join policy (recap)",
        "",
        "Leaderboard models are linked to C4 by a deterministic priority ladder:",
        "`hf_id` (normalised `Hugging Face developer id / Model`), `org`",
        "(normalised `Organization / Model`), `name` (normalised name unique on",
        "both sides), then an explicit (currently empty) alias map. No fuzzy",
        "matching; unlinked models are counted, not guessed. See",
        "`src/panel/c4_link.py`.",
        "",
    ]
    path = ensure(RESULTS / "tables") / "q4-panel-schema.md"
    _write(path, lines)
    return path


def coverage_report(panel) -> Path:
    summary = link_summary(panel)
    total = len(panel)
    by_stratum: List[str] = []
    for code in sorted(STRATUM_LABELS):
        sub = panel[panel["stratum"] == code]
        if sub.empty:
            continue
        linked = int((sub["link_method"] != "unlinked").sum())
        by_stratum.append(
            f"| {code} | {STRATUM_LABELS[code]} | {len(sub):,} | {linked:,} | {linked / len(sub):.1%} |"
        )
    lines = [
        "# Q4 C4 metadata linkage coverage",
        "",
        "Generated by `scripts/q4_panel_build.py`. Do not edit by hand.",
        "",
        "How many leaderboard models link to Epoch AI metadata (C4), and through",
        "which tier. The linkage is deliberately conservative: only deterministic",
        "name matches are used, so a low number is a real property of the two",
        "tables' naming schemes, not a missed opportunity.",
        "",
        "## Overall",
        "",
        f"- leaderboard models: {total:,}",
        f"- linked to C4: {total - summary.get('unlinked', 0):,} "
        f"({(total - summary.get('unlinked', 0)) / total:.2%})",
    ]
    for method in ("hf_id", "org", "name", "alias"):
        if method in summary:
            lines.append(f"- via `{method}`: {summary[method]:,}")
    lines.append(f"- unlinked: {summary.get('unlinked', 0):,}")
    lines += [
        "",
        "## By stratum",
        "",
        "| Stratum | Label | Models | C4-linked | Linked % |",
        "| --- | --- | ---: | ---: | ---: |",
    ] + by_stratum + [
        "",
        "Stratum A (pretrained / continuously pretrained base models) dominates",
        "the linkage, which is expected: Epoch AI's database records foundation",
        "models, while the leaderboard's fine-tunes and merges (C and D) rarely",
        "appear there under a matching name.",
        "",
    ]
    path = ensure(RESULTS / "tables") / "q4-panel-coverage.md"
    _write(path, lines)
    return path


def strata_report(panel) -> Path:
    cov = stratum_coverage(panel)
    lines = [
        "# Q4 model-type strata (A-E)",
        "",
        "Generated by `scripts/q4_panel_build.py`. Do not edit by hand.",
        "",
        "Each model is assigned to one of five analytical strata from the",
        "organizer's own `Type` field (collapsed to a coarse class and then to the",
        "A-E axis). The raw `Type` is preserved verbatim in a separate column; the",
        "name-keyword inference exists only as a fallback for rows with no",
        "organizer `Type`, and every leaderboard row here carries one.",
        "",
        "| Stratum | Label | Models | % of panel | Params known | Date known | Score known |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for code in sorted(cov):
        r = cov[code]
        lines.append(
            f"| {code} | {r['label']} | {r['count']:,} | {r['pct_of_panel']:.1f}% | "
            f"{r['params_known']:,} | {r['date_known']:,} | {r['score_known']:,} |"
        )
    lines += [
        "",
        "The strata are: A = pretrained / continuously pretrained; B = chat /",
        "instruction-tuned; C = fine-tuned; D = model merges; E = other /",
        "multimodal. The mapping from the organizer's raw `Type` labels to these",
        "strata is in `src/panel/config.py` (`C1_TYPE_TO_COARSE` and",
        "`COARSE_TO_STRATUM`).",
        "",
    ]
    path = ensure(RESULTS / "tables") / "q4-model-strata.md"
    _write(path, lines)
    return path


def date_report(panel) -> Path:
    cov = date_coverage(panel)
    lines = [
        "# Q4 date convention coverage",
        "",
        "Generated by `scripts/q4_panel_build.py`. Do not edit by hand.",
        "",
        "The analysis date is the Epoch AI publication date when available (C2, then",
        "C4), and the leaderboard submission date otherwise. Every row records",
        "which source its date came from, so the proxy is never mistaken for the",
        "release.",
        "",
        f"- primary (Epoch publication date): {cov['primary_count']:,} ({cov['primary_fraction']:.1%})",
        f"- fallback (submission date): {cov['fallback_count']:,} ({cov['fallback_fraction']:.1%})",
        f"- none: {cov['none_count']:,} ({cov['none_fraction']:.1%})",
        "",
        "## By stratum",
        "",
        "| Stratum | Primary | Fallback | None | Primary % |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for code in sorted(cov.get("by_stratum", {})):
        r = cov["by_stratum"][code]
        lines.append(
            f"| {code} | {r['primary']:,} | {r['fallback']:,} | {r['none']:,} | {r['primary_frac']:.1%} |"
        )
    lines += [
        "",
        "Most leaderboard models carry only a submission date, so the fallback is",
        "the dominant source; the primary publication date is concentrated in the",
        "base-model stratum that Epoch AI records directly.",
        "",
    ]
    path = ensure(RESULTS / "tables") / "q4-date-coverage.md"
    _write(path, lines)
    return path


def c4_metadata_report(panel) -> Path:
    linked = panel.query(LINKED)
    total_linked = len(linked)
    lines = [
        "# Q4 C4 metadata coverage",
        "",
        "Generated by `scripts/q4_panel_build.py`. Do not edit by hand.",
        "",
        "Of the models that link to C4, how many actually carry the metadata Q4",
        "needs: a parameter count, a training-compute estimate, a training-dataset",
        "size, and an open-weights accessibility field.",
        "",
        f"- C4-linked models: {total_linked:,}",
        f"- parameters non-null: {int(linked['c4_params'].notna().sum()):,}",
        f"- training compute (FLOP) non-null: {int(linked['c4_compute_flop'].notna().sum()):,}",
        f"- training dataset size non-null: {int(linked['c4_dataset_size'].notna().sum()):,}",
        f"- accessibility non-null: {int(linked['c4_accessibility'].notna().sum()):,}",
        "",
        "## By stratum",
        "",
        "| Stratum | Linked | Params | Compute | Dataset size | Accessibility |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for code in sorted(STRATUM_LABELS):
        sub = linked[linked["stratum"] == code]
        if sub.empty:
            continue
        lines.append(
            f"| {code} | {len(sub):,} | {int(sub['c4_params'].notna().sum()):,} | "
            f"{int(sub['c4_compute_flop'].notna().sum()):,} | {int(sub['c4_dataset_size'].notna().sum()):,} | "
            f"{int(sub['c4_accessibility'].notna().sum()):,} |"
        )
    lines += [
        "",
        "Parameters and accessibility are nearly complete among linked models;",
        "training compute is the scarcer field (about two thirds of linked rows),",
        "which bounds what a compute-conditioned forecast can use.",
        "",
    ]
    path = ensure(RESULTS / "tables") / "q4-c4-metadata-coverage.md"
    _write(path, lines)
    return path


def eligibility_report(panel) -> Path:
    ec = eligibility_counts(panel)
    ow = ec["open_weights"]
    lines = [
        "# Q4 open-model eligibility",
        "",
        "Generated by `scripts/q4_panel_build.py`. Do not edit by hand.",
        "",
        "T-011 needs a defensible frontier population of *open* models. T-009 only",
        "defines the fields and rules that distinguish them and reports counts; the",
        "choice of the primary population is left to T-011.",
        "",
        "A model counts as open only on a positive signal — a permissive Hub",
        "licence, an Epoch \"Open model weights? == Yes\", or unrestricted weight",
        "access — never on the mere fact of appearing on a public leaderboard. A",
        "model with no licence and no Epoch row is `unknown`, not `closed`.",
        "",
        f"- total models: {ec['total_rows']:,}",
        f"- open_weights yes: {ow['yes']:,}   no: {ow['no']:,}   unknown: {ow['unknown']:,}",
        f"- parameters known: {ec['params_known']:,}",
        f"- all six scores available: {ec['score_available']:,}",
        f"- date available: {ec['date_available']:,}",
        f"- training compute available: {ec['compute_available']:,}",
        f"- flagged as test/spam uploads: {ec['test_flag']:,}",
        f"- open AND params AND scores AND date: {ec['open_and_params_and_score_and_date']:,}",
        "",
        "The conjunction row is the *ceiling* for a population that requires open",
        "weights, a parameter count, full scores and a date; it is reported as a",
        "count, not adopted as the population. The permissive-licence set is in",
        "`src/panel/config.py` (`OPEN_LICENSES`); the test-upload patterns are in",
        "`TEST_MODEL_PATTERNS`.",
        "",
    ]
    path = ensure(RESULTS / "tables") / "q4-eligibility.md"
    _write(path, lines)
    return path


def main() -> int:
    print("loading C tables ...")
    c1, c2, c3, c4 = load_c1(), load_c2(), load_c3(), load_c4()

    print("building panel ...")
    panel = build_panel()
    derived = write_panel(panel)
    print(f"  panel: {panel_shape(panel)}")
    print(f"  wrote {derived.relative_to(Path(__file__).resolve().parent.parent)}")

    print("writing reports ...")
    reports = [
        schema_report(c1, c2, c3, c4, panel),
        coverage_report(panel),
        strata_report(panel),
        date_report(panel),
        c4_metadata_report(panel),
        eligibility_report(panel),
    ]
    root = Path(__file__).resolve().parent.parent
    for path in reports:
        print(f"  wrote {path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
