"""Q4 step 4: detailed C8 task-level evidence for reconciled dimensions.

The summary table averages grouped benchmarks into a single score.  This script
preserves the C8 per-subtask normalised scores only where the C8 corpus has
passed reconciliation against C1, then describes their availability,
distribution and model-vs-subtask variance.  MATH Lvl 5 is deliberately
excluded from the primary result because its C8 records are source-mismatched;
this script makes that exclusion visible rather than reporting a convenient but
invalid MATH ICC.

Run:  python scripts/q4_panel_detail.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.panel.detail import (  # noqa: E402
    QUARANTINED_DIMENSIONS,
    extract_subtasks,
    load_payloads,
    subtask_profile,
    variance_decomposition,
    within_model_imbalance,
)
from src.panel.leaderboard import load_detailed_results  # noqa: E402
from src.paths import ATT_C, RESULTS, ensure, require  # noqa: E402


def main() -> int:
    detailed = require(ATT_C / "detailed_results")

    print("parsing per-task records ...")
    records, damaged = load_detailed_results(detailed)
    payloads = load_payloads(detailed)
    print(f"  records: {len(records):,}   payloads: {len(payloads):,}")

    primary = extract_subtasks(records, payloads)
    profile = subtask_profile(primary, expected_models=len(records))
    decomp = variance_decomposition(primary)
    imbalance = within_model_imbalance(primary)
    print(f"  primary subtask observations: {len(primary):,}")
    print(f"  primary dimensions: {', '.join(sorted(primary['dimension'].unique()))}")
    print(f"  excluded from primary analysis: {', '.join(sorted(QUARANTINED_DIMENSIONS))}")

    tables = ensure(RESULTS / "tables")
    lines = [
        "# Q4 detailed C8 task-level analysis",
        "",
        "Generated by `scripts/q4_panel_detail.py`. Do not edit by hand.",
        "",
        "The summary table averages grouped benchmarks into one number. This page",
        "keeps the per-subtask normalised scores **only for C8 dimensions that pass",
        "the C1 reconciliation acceptance test**, so a downstream reader can see",
        "availability, score dispersion and within-model unevenness that a summary",
        "average hides.",
        "",
        "- parsed C8 records: " + f"{len(records):,}",
        "- primary subtask-score observations: " + f"{len(primary):,}",
        "- primary dimensions with an actual subtask breakdown: " + ", ".join(sorted(primary["dimension"].unique())),
        "",
        "## Primary per-subtask profile",
        "",
        "`Models` is the number of C8 records with a normalised score for that",
        "subtask. `Missing` is relative to all parsed C8 records, not to a selected",
        "frontier population. Scores are on the leaderboard's 0–100 normalised",
        "scale; variance and SD are across models.",
        "",
        "| Dimension | Subtask | Models | Missing | Missing % | Median | IQR | Variance | SD |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for _, row in profile.iterrows():
        lines.append(
            f"| {row['dimension']} | `{row['subtask']}` | {row['n_models']:,} | "
            f"{row['missing_models']:,} | {row['missing_rate']:.1%} | {row['median']:.2f} | "
            f"{row['iqr']:.2f} | {row['variance']:.2f} | {row['sd']:.2f} |"
        )

    lines += [
        "",
        "## Model-versus-subtask variance",
        "",
        "One-way variance decomposition uses model identity as the group on each",
        "dimension's normalised per-subtask scores. Only models with at least two",
        "subtasks contribute. ICC is between-model SS / total SS: it is a",
        "descriptive fraction, not a causal or forecasting result. The final columns",
        "describe each model's own subtask SD, then summarise that distribution; a",
        "larger value means more uneven performance across the benchmark's subtasks.",
        "",
        "| Dimension | Models | Subtasks | Observations | Grand mean | Between SS | Within SS | ICC | Median within-model SD | IQR within-model SD |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    imbalance_by_dimension = imbalance.set_index("dimension")
    for _, row in decomp.iterrows():
        within = imbalance_by_dimension.loc[row["dimension"]]
        lines.append(
            f"| {row['dimension']} | {row['n_models']:,} | {row['n_subtasks']:,} | "
            f"{row['n_observations']:,} | {row['grand_mean']:.2f} | "
            f"{row['between_ss']:,.0f} | {row['within_ss']:,.0f} | {row['icc']:.3f} | "
            f"{within['median_within_sd']:.2f} | {within['iqr_within_sd']:.2f} |"
        )

    lines += [
        "",
        "## Reconciled dimensions without a primary subtask matrix",
        "",
        "IFEval, GPQA and MMLU-PRO are reconciled for their published aggregate",
        "scores. In this C8 corpus they do not expose a valid grouped subtask matrix",
        "for this analysis: IFEval and MMLU-PRO are stored as aggregate blocks, and",
        "GPQA's published score is defined by pooling its children before rescaling.",
        "The GPQA child records therefore cannot be averaged as a task-level result",
        "even though they support the aggregation-rule diagnosis.",
        "",
        "## Quarantined/excluded diagnostic",
        "",
        "**MATH Lvl 5 is excluded from every primary table above.** The C8 diagnosis",
        "finds 154 models with `exact_match = 0` in every MATH child, including 119",
        "whose C1 summary MATH score is above zero. This is a C1/C8 source mismatch,",
        "not a normalisation problem. Its C8 child records must not be used by T-011",
        "or read as evidence about model mathematical ability. See",
        "`results/tables/q4-c8-diagnosis.md`.",
        "",
    ]
    out = tables / "q4-detailed-task-analysis.md"
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {out.relative_to(Path(__file__).resolve().parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
